package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * AllergiesHistory generated by hbm2java
 */
public class AllergiesHistory implements java.io.Serializable {

	private String id;
	private String personalInfoId;
	private Integer allergiesId;

	public AllergiesHistory() {
	}

	public AllergiesHistory(String personalInfoId, Integer allergiesId) {
		this.personalInfoId = personalInfoId;
		this.allergiesId = allergiesId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPersonalInfoId() {
		return this.personalInfoId;
	}

	public void setPersonalInfoId(String personalInfoId) {
		this.personalInfoId = personalInfoId;
	}

	public Integer getAllergiesId() {
		return this.allergiesId;
	}

	public void setAllergiesId(Integer allergiesId) {
		this.allergiesId = allergiesId;
	}

}
