package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * BornStatus generated by hbm2java
 */
public class BabyIllnessScreen implements java.io.Serializable {

	private String id;
	private String babyVisitId;
	private Integer babyIllnessScreenId;

	public BabyIllnessScreen() {
	}

	public BabyIllnessScreen(String babyVisitId, Integer babyIllnessScreenId) {
		this.babyVisitId = babyVisitId;
		this.babyIllnessScreenId = babyIllnessScreenId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBabyVisitId() {
		return this.babyVisitId;
	}

	public void setBabyVisitId(String babyVisitId) {
		this.babyVisitId = babyVisitId;
	}

	public Integer getBabyIllnessScreenId() {
		return babyIllnessScreenId;
	}

	public void setBabyIllnessScreenId(Integer babyIllnessScreenId) {
		this.babyIllnessScreenId = babyIllnessScreenId;
	}


}
