package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * BasicInformation generated by hbm2java
 */
public class BasicInformation implements java.io.Serializable {

	private Integer id;
	private Integer number;
	private String name;
	private String namePng;
	private Integer type;
	private Integer state;
	private Integer isMain;
	private Integer isBeforehand;
	private String isInputValue;
	private Integer printPage;
	
	public BasicInformation() {
	}

	public BasicInformation(Integer id, Integer number, String name,
			String namePng, Integer type, Integer state, Integer isMain,
			Integer isBeforehand, String isInputValue,Integer printPage) {
		this.id = id;
		this.number = number;
		this.name = name;
		this.namePng = namePng;
		this.type = type;
		this.state = state;
		this.isMain = isMain;
		this.isBeforehand = isBeforehand;
		this.isInputValue = isInputValue;
		this.printPage = printPage;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNamePng() {
		return this.namePng;
	}

	public void setNamePng(String namePng) {
		this.namePng = namePng;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Integer getIsMain() {
		return this.isMain;
	}

	public void setIsMain(Integer isMain) {
		this.isMain = isMain;
	}

	public Integer getIsBeforehand() {
		return this.isBeforehand;
	}

	public void setIsBeforehand(Integer isBeforehand) {
		this.isBeforehand = isBeforehand;
	}

	public String getIsInputValue() {
		return this.isInputValue;
	}

	public void setIsInputValue(String isInputValue) {
		this.isInputValue = isInputValue;
	}

	public Integer getPrintPage() {
		return printPage;
	}

	public void setPrintPage(Integer printPage) {
		this.printPage = printPage;
	}

}
