package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * BloodTrans generated by hbm2java
 */
public class BloodTrans implements java.io.Serializable {

	private String id;
	private String personalInfoId;
	private String reason;
	private String transDate;

	public BloodTrans() {
	}

	public BloodTrans(String personalInfoId, String reason, String transDate) {
		this.personalInfoId = personalInfoId;
		this.reason = reason;
		this.transDate = transDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPersonalInfoId() {
		return this.personalInfoId;
	}

	public void setPersonalInfoId(String personalInfoId) {
		this.personalInfoId = personalInfoId;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getTransDate() {
		return this.transDate;
	}

	public void setTransDate(String transDate) {
		this.transDate = transDate;
	}

}
