package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * BornStatus generated by hbm2java
 */
public class BornStatus implements java.io.Serializable {

	private String id;
	private String babyVisitId;
	private Integer bornStatusId;

	public BornStatus() {
	}

	public BornStatus(String babyVisitId, Integer bornStatusId) {
		this.babyVisitId = babyVisitId;
		this.bornStatusId = bornStatusId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBabyVisitId() {
		return this.babyVisitId;
	}

	public void setBabyVisitId(String babyVisitId) {
		this.babyVisitId = babyVisitId;
	}

	public Integer getBornStatusId() {
		return this.bornStatusId;
	}

	public void setBornStatusId(Integer bornStatusId) {
		this.bornStatusId = bornStatusId;
	}

}
