package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * BusinessName generated by hbm2java
 */
public class BusinessName implements java.io.Serializable {

	private Integer id;
	private String name;

	public BusinessName() {
	}

	public BusinessName(Integer id) {
		this.id = id;
	}

	public BusinessName(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
