package cn.net.tongfang.framework.security.vo;

// Generated 2013-11-10 1:20:52 by Hibernate Tools 3.4.0.CR1

/**
 * CfgFilesearch generated by hbm2java
 */
public class CfgFilesearch implements java.io.Serializable {

	private int id;
	private String name;
	private String othertable;
	private String params;
	private String cols;

	public CfgFilesearch() {
	}

	public CfgFilesearch(int id, String name, String othertable, String params, String cols) {
		this.id = id;
		this.name = name;
		this.othertable = othertable;
		this.params = params;
		this.cols = cols;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOthertable() {
		return this.othertable;
	}

	public void setOthertable(String othertable) {
		this.othertable = othertable;
	}

	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	public String getCols() {
		return this.cols;
	}

	public void setCols(String cols) {
		this.cols = cols;
	}

}
