package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * CheckDirect generated by hbm2java
 */
public class CheckDirect implements java.io.Serializable {

	private String id;
	private String childrenMediExamId;
	private Integer checkDirectId;

	public CheckDirect() {
	}

	public CheckDirect(String childrenMediExamId, Integer checkDirectId) {
		this.childrenMediExamId = childrenMediExamId;
		this.checkDirectId = checkDirectId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getChildrenMediExamId() {
		return this.childrenMediExamId;
	}

	public void setChildrenMediExamId(String childrenMediExamId) {
		this.childrenMediExamId = childrenMediExamId;
	}

	public Integer getCheckDirectId() {
		return this.checkDirectId;
	}

	public void setCheckDirectId(Integer checkDirectId) {
		this.checkDirectId = checkDirectId;
	}

}
