package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * CheckSickness generated by hbm2java
 */
public class CheckSickness implements java.io.Serializable {

	private String id;
	private String childrenMediExam3id;
	private Integer checkSicknessId;

	public CheckSickness() {
	}

	public CheckSickness(String childrenMediExam3id, Integer checkSicknessId) {
		this.childrenMediExam3id = childrenMediExam3id;
		this.checkSicknessId = checkSicknessId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getChildrenMediExam3id() {
		return this.childrenMediExam3id;
	}

	public void setChildrenMediExam3id(String childrenMediExam3id) {
		this.childrenMediExam3id = childrenMediExam3id;
	}

	public Integer getCheckSicknessId() {
		return this.checkSicknessId;
	}

	public void setCheckSicknessId(Integer checkSicknessId) {
		this.checkSicknessId = checkSicknessId;
	}

}
