package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * CheckDirect3 generated by hbm2java
 */
public class CheckDirect3 implements java.io.Serializable {

	private String id;
	private String childrenMediExam3id;
	private Integer checkDirect3id;

	public CheckDirect3() {
	}

	public CheckDirect3(String id, String childrenMediExam3id,
			Integer checkDirect3id) {
		this.id = id;
		this.childrenMediExam3id = childrenMediExam3id;
		this.checkDirect3id = checkDirect3id;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getChildrenMediExam3id() {
		return this.childrenMediExam3id;
	}

	public void setChildrenMediExam3id(String childrenMediExam3id) {
		this.childrenMediExam3id = childrenMediExam3id;
	}

	public Integer getCheckDirect3id() {
		return this.checkDirect3id;
	}

	public void setCheckDirect3id(Integer checkDirect3id) {
		this.checkDirect3id = checkDirect3id;
	}

}
