package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * ChildrenMediExam generated by hbm2java
 */
public class ChildrenMediExam implements java.io.Serializable {

	private String id;
	private String fileNo;
	private String inputPersonId;
	private Timestamp inputDate;
	private Integer dataType;
	private String checkItem;
	private Timestamp visitDate;
	private BigDecimal weight;
	private String weightScore;
	private BigDecimal height;
	private String heightScore;
	private String face;
	private String faceOther;
	private String eyes;
	private String eyesOther;
	private String ears;
	private String earsOther;
	private String heart;
	private String heartOther;
	private String walk;
	private String walkOther;
	private String other;
	private String transfer;
	private String transReason;
	private String transUnit;
	private String directOther;
	private String nextVisitDate;
	private String visitDoctor;
	private String exam01;
	private String exam01other;
	private String exam02;
	private BigDecimal exam03;
	private BigDecimal exam04;
	private Integer exam05;
	private String exam06;
	private String exam06other;
	private String exam07;
	private String exam07other;
	private String exam08;
	private String exam08other;
	private String exam09;
	private String exam10;
	private String exam11;
	private String exam11other;
	private String exam12;
	private BigDecimal activityTime;
	private BigDecimal wdcount;
	private String evaluate;
	private String state;
	private BigDecimal head;
	private Integer exam13;
	private String exam14;
	private String exam15;
	private String exam15Other;
	private String exam16;
	private String exam16Other;
	private Integer exam17;
	private String highRisk;
	private String highRiskRemark;
	private String execDistrictNum;
	private String evaluateOther;
	private String highRiskSearch;
	private String breastMilk;
	private String foreignId;
	public ChildrenMediExam() {
	}

	public ChildrenMediExam(String fileNo, String inputPersonId,
			Timestamp inputDate, Integer dataType, String checkItem) {
		this.fileNo = fileNo;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
		this.dataType = dataType;
		this.checkItem = checkItem;
	}

	

	public ChildrenMediExam(String id, String fileNo, String inputPersonId,
			Timestamp inputDate, Integer dataType, String checkItem,
			Timestamp visitDate, BigDecimal weight, String weightScore,
			BigDecimal height, String heightScore, String face,
			String faceOther, String eyes, String eyesOther, String ears,
			String earsOther, String heart, String heartOther, String walk,
			String walkOther, String other, String transfer,
			String transReason, String transUnit, String directOther,
			String nextVisitDate, String visitDoctor, String exam01,
			String exam01other, String exam02, BigDecimal exam03,
			BigDecimal exam04, Integer exam05, String exam06,
			String exam06other, String exam07, String exam07other,
			String exam08, String exam08other, String exam09, String exam10,
			String exam11, String exam11other, String exam12,
			BigDecimal activityTime, BigDecimal wdcount, String evaluate,
			String state, BigDecimal head, Integer exam13, String exam14,
			String exam15, String exam15Other, String exam16, String exam16Other,Integer exam17,
			String highRisk,String highRiskRemark,String execDistrictNum,
			String evaluateOther,String highRiskSearch,String breastMilk,
			String foreignId) {
		super();
		this.id = id;
		this.fileNo = fileNo;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
		this.dataType = dataType;
		this.checkItem = checkItem;
		this.visitDate = visitDate;
		this.weight = weight;
		this.weightScore = weightScore;
		this.height = height;
		this.heightScore = heightScore;
		this.face = face;
		this.faceOther = faceOther;
		this.eyes = eyes;
		this.eyesOther = eyesOther;
		this.ears = ears;
		this.earsOther = earsOther;
		this.heart = heart;
		this.heartOther = heartOther;
		this.walk = walk;
		this.walkOther = walkOther;
		this.other = other;
		this.transfer = transfer;
		this.transReason = transReason;
		this.transUnit = transUnit;
		this.directOther = directOther;
		this.nextVisitDate = nextVisitDate;
		this.visitDoctor = visitDoctor;
		this.exam01 = exam01;
		this.exam01other = exam01other;
		this.exam02 = exam02;
		this.exam03 = exam03;
		this.exam04 = exam04;
		this.exam05 = exam05;
		this.exam06 = exam06;
		this.exam06other = exam06other;
		this.exam07 = exam07;
		this.exam07other = exam07other;
		this.exam08 = exam08;
		this.exam08other = exam08other;
		this.exam09 = exam09;
		this.exam10 = exam10;
		this.exam11 = exam11;
		this.exam11other = exam11other;
		this.exam12 = exam12;
		this.activityTime = activityTime;
		this.wdcount = wdcount;
		this.evaluate = evaluate;
		this.state = state;
		this.head = head;
		this.exam13 = exam13;
		this.exam14 = exam14;
		this.exam15 = exam15;
		this.exam15Other = exam15Other;
		this.exam16 = exam16;
		this.exam16Other = exam16Other;
		this.exam17 = exam17;
		this.highRisk = highRisk;
		this.highRiskRemark = highRiskRemark;
		this.execDistrictNum = execDistrictNum;
		this.highRiskSearch = highRiskSearch;
		this.breastMilk = breastMilk;
		this.foreignId = foreignId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public String getInputPersonId() {
		return this.inputPersonId;
	}

	public void setInputPersonId(String inputPersonId) {
		this.inputPersonId = inputPersonId;
	}

	public Timestamp getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
	}

	public Integer getDataType() {
		return this.dataType;
	}

	public void setDataType(Integer dataType) {
		this.dataType = dataType;
	}

	public String getCheckItem() {
		return this.checkItem;
	}

	public void setCheckItem(String checkItem) {
		this.checkItem = checkItem;
	}

	public Timestamp getVisitDate() {
		return this.visitDate;
	}

	public void setVisitDate(Timestamp visitDate) {
		this.visitDate = visitDate;
	}

	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	public String getWeightScore() {
		return this.weightScore;
	}

	public void setWeightScore(String weightScore) {
		this.weightScore = weightScore;
	}

	public BigDecimal getHeight() {
		return this.height;
	}

	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	public String getHeightScore() {
		return this.heightScore;
	}

	public void setHeightScore(String heightScore) {
		this.heightScore = heightScore;
	}

	public String getFace() {
		return this.face;
	}

	public void setFace(String face) {
		this.face = face;
	}

	public String getFaceOther() {
		return this.faceOther;
	}

	public void setFaceOther(String faceOther) {
		this.faceOther = faceOther;
	}

	public String getEyes() {
		return this.eyes;
	}

	public void setEyes(String eyes) {
		this.eyes = eyes;
	}

	public String getEyesOther() {
		return this.eyesOther;
	}

	public void setEyesOther(String eyesOther) {
		this.eyesOther = eyesOther;
	}

	public String getEars() {
		return this.ears;
	}

	public void setEars(String ears) {
		this.ears = ears;
	}

	public String getEarsOther() {
		return this.earsOther;
	}

	public void setEarsOther(String earsOther) {
		this.earsOther = earsOther;
	}

	public String getHeart() {
		return this.heart;
	}

	public void setHeart(String heart) {
		this.heart = heart;
	}

	public String getHeartOther() {
		return this.heartOther;
	}

	public void setHeartOther(String heartOther) {
		this.heartOther = heartOther;
	}

	public String getWalk() {
		return this.walk;
	}

	public void setWalk(String walk) {
		this.walk = walk;
	}

	public String getWalkOther() {
		return this.walkOther;
	}

	public void setWalkOther(String walkOther) {
		this.walkOther = walkOther;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public String getTransfer() {
		return this.transfer;
	}

	public void setTransfer(String transfer) {
		this.transfer = transfer;
	}

	public String getTransReason() {
		return this.transReason;
	}

	public void setTransReason(String transReason) {
		this.transReason = transReason;
	}

	public String getTransUnit() {
		return this.transUnit;
	}

	public void setTransUnit(String transUnit) {
		this.transUnit = transUnit;
	}

	public String getDirectOther() {
		return this.directOther;
	}

	public void setDirectOther(String directOther) {
		this.directOther = directOther;
	}

	public String getNextVisitDate() {
		return this.nextVisitDate;
	}

	public void setNextVisitDate(String nextVisitDate) {
		this.nextVisitDate = nextVisitDate;
	}

	public String getVisitDoctor() {
		return this.visitDoctor;
	}

	public void setVisitDoctor(String visitDoctor) {
		this.visitDoctor = visitDoctor;
	}

	public String getExam01() {
		return this.exam01;
	}

	public void setExam01(String exam01) {
		this.exam01 = exam01;
	}

	public String getExam01other() {
		return this.exam01other;
	}

	public void setExam01other(String exam01other) {
		this.exam01other = exam01other;
	}

	public String getExam02() {
		return this.exam02;
	}

	public void setExam02(String exam02) {
		this.exam02 = exam02;
	}

	public BigDecimal getExam03() {
		return this.exam03;
	}

	public void setExam03(BigDecimal exam03) {
		this.exam03 = exam03;
	}

	public BigDecimal getExam04() {
		return this.exam04;
	}

	public void setExam04(BigDecimal exam04) {
		this.exam04 = exam04;
	}

	public Integer getExam05() {
		return this.exam05;
	}

	public void setExam05(Integer exam05) {
		this.exam05 = exam05;
	}

	public String getExam06() {
		return this.exam06;
	}

	public void setExam06(String exam06) {
		this.exam06 = exam06;
	}

	public String getExam06other() {
		return this.exam06other;
	}

	public void setExam06other(String exam06other) {
		this.exam06other = exam06other;
	}

	public String getExam07() {
		return this.exam07;
	}

	public void setExam07(String exam07) {
		this.exam07 = exam07;
	}

	public String getExam07other() {
		return this.exam07other;
	}

	public void setExam07other(String exam07other) {
		this.exam07other = exam07other;
	}

	public String getExam08() {
		return this.exam08;
	}

	public void setExam08(String exam08) {
		this.exam08 = exam08;
	}

	public String getExam08other() {
		return this.exam08other;
	}

	public void setExam08other(String exam08other) {
		this.exam08other = exam08other;
	}

	public String getExam09() {
		return this.exam09;
	}

	public void setExam09(String exam09) {
		this.exam09 = exam09;
	}

	public String getExam10() {
		return this.exam10;
	}

	public void setExam10(String exam10) {
		this.exam10 = exam10;
	}

	public String getExam11() {
		return this.exam11;
	}

	public void setExam11(String exam11) {
		this.exam11 = exam11;
	}

	public String getExam11other() {
		return this.exam11other;
	}

	public void setExam11other(String exam11other) {
		this.exam11other = exam11other;
	}

	public String getExam12() {
		return this.exam12;
	}

	public void setExam12(String exam12) {
		this.exam12 = exam12;
	}

	public BigDecimal getActivityTime() {
		return this.activityTime;
	}

	public void setActivityTime(BigDecimal activityTime) {
		this.activityTime = activityTime;
	}

	public BigDecimal getWdcount() {
		return this.wdcount;
	}

	public void setWdcount(BigDecimal wdcount) {
		this.wdcount = wdcount;
	}

	public String getEvaluate() {
		return this.evaluate;
	}

	public void setEvaluate(String evaluate) {
		this.evaluate = evaluate;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public BigDecimal getHead() {
		return head;
	}

	public void setHead(BigDecimal head) {
		this.head = head;
	}

	public Integer getExam13() {
		return exam13;
	}

	public void setExam13(Integer exam13) {
		this.exam13 = exam13;
	}

	public String getExam14() {
		return exam14;
	}

	public void setExam14(String exam14) {
		this.exam14 = exam14;
	}

	public String getExam15() {
		return exam15;
	}

	public void setExam15(String exam15) {
		this.exam15 = exam15;
	}

	public String getExam15Other() {
		return exam15Other;
	}

	public void setExam15Other(String exam15Other) {
		this.exam15Other = exam15Other;
	}

	public String getExam16() {
		return exam16;
	}

	public void setExam16(String exam16) {
		this.exam16 = exam16;
	}

	public String getExam16Other() {
		return exam16Other;
	}

	public void setExam16Other(String exam16Other) {
		this.exam16Other = exam16Other;
	}

	public Integer getExam17() {
		return exam17;
	}

	public void setExam17(Integer exam17) {
		this.exam17 = exam17;
	}

	public String getHighRisk() {
		return highRisk;
	}

	public void setHighRisk(String highRisk) {
		this.highRisk = highRisk;
	}

	public String getHighRiskRemark() {
		return highRiskRemark;
	}

	public void setHighRiskRemark(String highRiskRemark) {
		this.highRiskRemark = highRiskRemark;
	}

	public String getExecDistrictNum() {
		return execDistrictNum;
	}

	public void setExecDistrictNum(String execDistrictNum) {
		this.execDistrictNum = execDistrictNum;
	}

	public String getEvaluateOther() {
		return evaluateOther;
	}

	public void setEvaluateOther(String evaluateOther) {
		this.evaluateOther = evaluateOther;
	}

	public String getHighRiskSearch() {
		return highRiskSearch;
	}

	public void setHighRiskSearch(String highRiskSearch) {
		this.highRiskSearch = highRiskSearch;
	}

	public String getBreastMilk() {
		return breastMilk;
	}

	public void setBreastMilk(String breastMilk) {
		this.breastMilk = breastMilk;
	}

	public String getForeignId() {
		return foreignId;
	}

	public void setForeignId(String foreignId) {
		this.foreignId = foreignId;
	}
	
}
