package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * ChildrenMediExam3 generated by hbm2java
 */
public class ChildrenMediExam3 implements java.io.Serializable {

	private String id;
	private String fileNo;
	private String inputPersonId;
	private Timestamp inputDate;
	private Timestamp visitDate;
	private BigDecimal weight;
	private String weightScore;
	private BigDecimal height;
	private String heightScore;
	private String body;
	private String face;
	private String faceOther;
	private String eyes;
	private String eyesOther;
	private String ears;
	private String earsOther;
	private String heart;
	private String heartOther;
	private String liver;
	private String liverOther;
	private String walk;
	private String walkOther;
	private String behaiviour;
	private String behaiviourOther;
	private String sociality;
	private String socialityOther;
	private String sickness;
	private String sicknessOther;
	private String allergy;
	private String allergyOther;
	private String other;
	private Integer transfer;
	private String transReason;
	private String transUnit;
	private String directOther;
	private String visitDoctor;
	private String highRiskSearch;
	public ChildrenMediExam3() {
	}

	public ChildrenMediExam3(String fileNo, String inputPersonId,
			Timestamp inputDate) {
		this.fileNo = fileNo;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
	}

	public ChildrenMediExam3(String fileNo, String inputPersonId,
			Timestamp inputDate, Timestamp visitDate, BigDecimal weight,
			String weightScore, BigDecimal height, String heightScore,
			String body, String face, String faceOther, String eyes,
			String eyesOther, String ears, String earsOther, String heart,
			String heartOther, String liver, String liverOther, String walk,
			String walkOther, String behaiviour, String behaiviourOther,
			String sociality, String socialityOther, String sickness,
			String sicknessOther, String allergy, String allergyOther,
			String other, Integer transfer, String transReason,
			String transUnit, String directOther, String visitDoctor,
			String highRiskSearch) {
		this.fileNo = fileNo;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
		this.visitDate = visitDate;
		this.weight = weight;
		this.weightScore = weightScore;
		this.height = height;
		this.heightScore = heightScore;
		this.body = body;
		this.face = face;
		this.faceOther = faceOther;
		this.eyes = eyes;
		this.eyesOther = eyesOther;
		this.ears = ears;
		this.earsOther = earsOther;
		this.heart = heart;
		this.heartOther = heartOther;
		this.liver = liver;
		this.liverOther = liverOther;
		this.walk = walk;
		this.walkOther = walkOther;
		this.behaiviour = behaiviour;
		this.behaiviourOther = behaiviourOther;
		this.sociality = sociality;
		this.socialityOther = socialityOther;
		this.sickness = sickness;
		this.sicknessOther = sicknessOther;
		this.allergy = allergy;
		this.allergyOther = allergyOther;
		this.other = other;
		this.transfer = transfer;
		this.transReason = transReason;
		this.transUnit = transUnit;
		this.directOther = directOther;
		this.visitDoctor = visitDoctor;
		this.highRiskSearch = highRiskSearch;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public String getInputPersonId() {
		return this.inputPersonId;
	}

	public void setInputPersonId(String inputPersonId) {
		this.inputPersonId = inputPersonId;
	}

	public Timestamp getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
	}

	public Timestamp getVisitDate() {
		return this.visitDate;
	}

	public void setVisitDate(Timestamp visitDate) {
		this.visitDate = visitDate;
	}

	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	public String getWeightScore() {
		return this.weightScore;
	}

	public void setWeightScore(String weightScore) {
		this.weightScore = weightScore;
	}

	public BigDecimal getHeight() {
		return this.height;
	}

	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	public String getHeightScore() {
		return this.heightScore;
	}

	public void setHeightScore(String heightScore) {
		this.heightScore = heightScore;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public String getFace() {
		return this.face;
	}

	public void setFace(String face) {
		this.face = face;
	}

	public String getFaceOther() {
		return this.faceOther;
	}

	public void setFaceOther(String faceOther) {
		this.faceOther = faceOther;
	}

	public String getEyes() {
		return this.eyes;
	}

	public void setEyes(String eyes) {
		this.eyes = eyes;
	}

	public String getEyesOther() {
		return this.eyesOther;
	}

	public void setEyesOther(String eyesOther) {
		this.eyesOther = eyesOther;
	}

	public String getEars() {
		return this.ears;
	}

	public void setEars(String ears) {
		this.ears = ears;
	}

	public String getEarsOther() {
		return this.earsOther;
	}

	public void setEarsOther(String earsOther) {
		this.earsOther = earsOther;
	}

	public String getHeart() {
		return this.heart;
	}

	public void setHeart(String heart) {
		this.heart = heart;
	}

	public String getHeartOther() {
		return this.heartOther;
	}

	public void setHeartOther(String heartOther) {
		this.heartOther = heartOther;
	}

	public String getLiver() {
		return this.liver;
	}

	public void setLiver(String liver) {
		this.liver = liver;
	}

	public String getLiverOther() {
		return this.liverOther;
	}

	public void setLiverOther(String liverOther) {
		this.liverOther = liverOther;
	}

	public String getWalk() {
		return this.walk;
	}

	public void setWalk(String walk) {
		this.walk = walk;
	}

	public String getWalkOther() {
		return this.walkOther;
	}

	public void setWalkOther(String walkOther) {
		this.walkOther = walkOther;
	}

	public String getBehaiviour() {
		return this.behaiviour;
	}

	public void setBehaiviour(String behaiviour) {
		this.behaiviour = behaiviour;
	}

	public String getBehaiviourOther() {
		return this.behaiviourOther;
	}

	public void setBehaiviourOther(String behaiviourOther) {
		this.behaiviourOther = behaiviourOther;
	}

	public String getSociality() {
		return this.sociality;
	}

	public void setSociality(String sociality) {
		this.sociality = sociality;
	}

	public String getSocialityOther() {
		return this.socialityOther;
	}

	public void setSocialityOther(String socialityOther) {
		this.socialityOther = socialityOther;
	}

	public String getSickness() {
		return this.sickness;
	}

	public void setSickness(String sickness) {
		this.sickness = sickness;
	}

	public String getSicknessOther() {
		return this.sicknessOther;
	}

	public void setSicknessOther(String sicknessOther) {
		this.sicknessOther = sicknessOther;
	}

	public String getAllergy() {
		return this.allergy;
	}

	public void setAllergy(String allergy) {
		this.allergy = allergy;
	}

	public String getAllergyOther() {
		return this.allergyOther;
	}

	public void setAllergyOther(String allergyOther) {
		this.allergyOther = allergyOther;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public Integer getTransfer() {
		return this.transfer;
	}

	public void setTransfer(Integer transfer) {
		this.transfer = transfer;
	}

	public String getTransReason() {
		return this.transReason;
	}

	public void setTransReason(String transReason) {
		this.transReason = transReason;
	}

	public String getTransUnit() {
		return this.transUnit;
	}

	public void setTransUnit(String transUnit) {
		this.transUnit = transUnit;
	}

	public String getDirectOther() {
		return this.directOther;
	}

	public void setDirectOther(String directOther) {
		this.directOther = directOther;
	}

	public String getVisitDoctor() {
		return this.visitDoctor;
	}

	public void setVisitDoctor(String visitDoctor) {
		this.visitDoctor = visitDoctor;
	}

	public String getHighRiskSearch() {
		return highRiskSearch;
	}

	public void setHighRiskSearch(String highRiskSearch) {
		this.highRiskSearch = highRiskSearch;
	}

}
