package cn.net.tongfang.framework.security.vo;

// Generated 2013-11-10 17:36:55 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * CodMedicalPublicarea generated by hbm2java
 */
public class CodMedicalPublicarea implements java.io.Serializable {

	private long id;
	private String orgname;
	private String regaddress;
	private Timestamp startdate;
	private Timestamp enddate;
	private String legalman;
	private String tel;

	public CodMedicalPublicarea() {
	}

	public CodMedicalPublicarea(String orgname, String regaddress, Timestamp startdate, Timestamp enddate, String legalman, String tel) {
		this.orgname = orgname;
		this.regaddress = regaddress;
		this.startdate = startdate;
		this.enddate = enddate;
		this.legalman = legalman;
		this.tel = tel;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getRegaddress() {
		return this.regaddress;
	}

	public void setRegaddress(String regaddress) {
		this.regaddress = regaddress;
	}

	public Timestamp getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Timestamp startdate) {
		this.startdate = startdate;
	}

	public Timestamp getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Timestamp enddate) {
		this.enddate = enddate;
	}

	public String getLegalman() {
		return this.legalman;
	}

	public void setLegalman(String legalman) {
		this.legalman = legalman;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

}
