package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * ConsultationOrg generated by hbm2java
 */
public class ConsultationOrg implements java.io.Serializable {

	private String id;
	private String consultationId;
	private String orgName;
	private String doctor;

	public ConsultationOrg() {
	}

	public ConsultationOrg(String consultationId) {
		this.consultationId = consultationId;
	}

	public ConsultationOrg(String consultationId, String orgName, String doctor) {
		this.consultationId = consultationId;
		this.orgName = orgName;
		this.doctor = doctor;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getConsultationId() {
		return this.consultationId;
	}

	public void setConsultationId(String consultationId) {
		this.consultationId = consultationId;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

}
