package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;

/**
 * Consultation generated by hbm2java
 */
public class Consultation implements java.io.Serializable {

	private String id;
	private String fileNo;
	private Timestamp date;
	private String reason;
	private String notion;
	private String doctor;
	private String inputPersonId;
	private Timestamp inputDate;
	private String execDistrictNum;

	public Consultation() {
	}

	public Consultation(String fileNo, Timestamp date, String inputPersonId,
			Timestamp inputDate) {
		this.fileNo = fileNo;
		this.date = date;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
	}

	public Consultation(String fileNo, Timestamp date, String reason,
			String notion, String doctor, String inputPersonId,
			Timestamp inputDate,String execDistrictNum) {
		this.fileNo = fileNo;
		this.date = date;
		this.reason = reason;
		this.notion = notion;
		this.doctor = doctor;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
		this.execDistrictNum =execDistrictNum;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public Timestamp getDate() {
		return this.date;
	}

	public void setDate(Timestamp date) {
		this.date = date;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getNotion() {
		return this.notion;
	}

	public void setNotion(String notion) {
		this.notion = notion;
	}

	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

	public String getInputPersonId() {
		return this.inputPersonId;
	}

	public void setInputPersonId(String inputPersonId) {
		this.inputPersonId = inputPersonId;
	}

	public Timestamp getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
	}

	public String getExecDistrictNum() {
		return execDistrictNum;
	}

	public void setExecDistrictNum(String execDistrictNum) {
		this.execDistrictNum = execDistrictNum;
	}

}
