package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * DangerControl generated by hbm2java
 */
public class DangerControl implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private Integer dangerControlId;

	public DangerControl() {
	}

	public DangerControl(String medicalExamId, Integer dangerControlId) {
		this.medicalExamId = medicalExamId;
		this.dangerControlId = dangerControlId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public Integer getDangerControlId() {
		return this.dangerControlId;
	}

	public void setDangerControlId(Integer dangerControlId) {
		this.dangerControlId = dangerControlId;
	}

}
