package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * DiabetesMedications generated by hbm2java
 */
public class DiabetesMedications implements java.io.Serializable {

	private String id;
	private String diabetesVisitId;
	private String drugName;
	private String usage;
	private String dosage;

	public DiabetesMedications() {
	}

	public DiabetesMedications(String diabetesVisitId, String drugName,
			String usage, String dosage) {
		this.diabetesVisitId = diabetesVisitId;
		this.drugName = drugName;
		this.usage = usage;
		this.dosage = dosage;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDiabetesVisitId() {
		return this.diabetesVisitId;
	}

	public void setDiabetesVisitId(String diabetesVisitId) {
		this.diabetesVisitId = diabetesVisitId;
	}

	public String getDrugName() {
		return this.drugName;
	}

	public void setDrugName(String drugName) {
		this.drugName = drugName;
	}

	public String getUsage() {
		return this.usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	public String getDosage() {
		return this.dosage;
	}

	public void setDosage(String dosage) {
		this.dosage = dosage;
	}

}
