package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * DisabilityStatus generated by hbm2java
 */
public class DisabilityStatus implements java.io.Serializable {

	private String id;
	private String personalInfoId;
	private Integer disabilityStatusId;

	public DisabilityStatus() {
	}

	public DisabilityStatus(String personalInfoId, Integer disabilityStatusId) {
		this.personalInfoId = personalInfoId;
		this.disabilityStatusId = disabilityStatusId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPersonalInfoId() {
		return this.personalInfoId;
	}

	public void setPersonalInfoId(String personalInfoId) {
		this.personalInfoId = personalInfoId;
	}

	public Integer getDisabilityStatusId() {
		return this.disabilityStatusId;
	}

	public void setDisabilityStatusId(Integer disabilityStatusId) {
		this.disabilityStatusId = disabilityStatusId;
	}

}
