package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * DiseaseHistory generated by hbm2java
 */
public class DiseaseHistory implements java.io.Serializable {

	private String id;
	private String personalInfoId;
	private Integer diseaseId;
	private String remark;
	private String confirmDate;

	public DiseaseHistory() {
	}

	public DiseaseHistory(String personalInfoId, Integer diseaseId,
			String remark, String confirmDate) {
		this.personalInfoId = personalInfoId;
		this.diseaseId = diseaseId;
		this.remark = remark;
		this.confirmDate = confirmDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPersonalInfoId() {
		return this.personalInfoId;
	}

	public void setPersonalInfoId(String personalInfoId) {
		this.personalInfoId = personalInfoId;
	}

	public Integer getDiseaseId() {
		return this.diseaseId;
	}

	public void setDiseaseId(Integer diseaseId) {
		this.diseaseId = diseaseId;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getConfirmDate() {
		return this.confirmDate;
	}

	public void setConfirmDate(String confirmDate) {
		this.confirmDate = confirmDate;
	}

}
