package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * DocumentSave generated by hbm2java
 */
public class DocumentSave implements java.io.Serializable {

	private String id;
	private String healthEducatId;
	private Integer documentId;

	public DocumentSave() {
	}

	public DocumentSave(String healthEducatId, Integer documentId) {
		this.healthEducatId = healthEducatId;
		this.documentId = documentId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getHealthEducatId() {
		return this.healthEducatId;
	}

	public void setHealthEducatId(String healthEducatId) {
		this.healthEducatId = healthEducatId;
	}

	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

}
