package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * EatHabit generated by hbm2java
 */
public class EatHabit implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private Integer eatHabitId;

	public EatHabit() {
	}

	public EatHabit(String medicalExamId, Integer eatHabitId) {
		this.medicalExamId = medicalExamId;
		this.eatHabitId = eatHabitId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public Integer getEatHabitId() {
		return this.eatHabitId;
	}

	public void setEatHabitId(Integer eatHabitId) {
		this.eatHabitId = eatHabitId;
	}

}
