package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * ExamSymptom generated by hbm2java
 */
public class ExamSymptom implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private Integer examSymptomId;

	public ExamSymptom() {
	}

	public ExamSymptom(String medicalExamId, Integer examSymptomId) {
		this.medicalExamId = medicalExamId;
		this.examSymptomId = examSymptomId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public Integer getExamSymptomId() {
		return this.examSymptomId;
	}

	public void setExamSymptomId(Integer examSymptomId) {
		this.examSymptomId = examSymptomId;
	}

}
