package cn.net.tongfang.framework.security.vo;

// Generated 2013-11-3 23:13:22 by Hibernate Tools 3.4.0.CR1

/**
 * ExamQueryCfg generated by hbm2java
 */
public class ExamQueryCfg implements java.io.Serializable {

	private int id;
	private String name;
	private String col;
	private String coltype;
	private boolean display;
	private String examname;
	private boolean encflag;
	private Boolean isitem;
	private Boolean isquery;
	private Integer ord;

	public ExamQueryCfg() {
	}

	public ExamQueryCfg(int id, String name, String col, String coltype,
			boolean display, String examname, boolean encflag) {
		this.id = id;
		this.name = name;
		this.col = col;
		this.coltype = coltype;
		this.display = display;
		this.examname = examname;
		this.encflag = encflag;
	}

	public ExamQueryCfg(int id, String name, String col, String coltype,
			boolean display, String examname, boolean encflag, Boolean isitem,
			Boolean isquery, Integer ord) {
		this.id = id;
		this.name = name;
		this.col = col;
		this.coltype = coltype;
		this.display = display;
		this.examname = examname;
		this.encflag = encflag;
		this.isitem = isitem;
		this.isquery = isquery;
		this.ord = ord;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCol() {
		return this.col;
	}

	public void setCol(String col) {
		this.col = col;
	}

	public String getColtype() {
		return this.coltype;
	}

	public void setColtype(String coltype) {
		this.coltype = coltype;
	}

	public boolean isDisplay() {
		return this.display;
	}

	public void setDisplay(boolean display) {
		this.display = display;
	}

	public String getExamname() {
		return this.examname;
	}

	public void setExamname(String examname) {
		this.examname = examname;
	}

	public boolean isEncflag() {
		return this.encflag;
	}

	public void setEncflag(boolean encflag) {
		this.encflag = encflag;
	}

	public Boolean getIsitem() {
		return this.isitem;
	}

	public void setIsitem(Boolean isitem) {
		this.isitem = isitem;
	}

	public Boolean getIsquery() {
		return this.isquery;
	}

	public void setIsquery(Boolean isquery) {
		this.isquery = isquery;
	}

	public Integer getOrd() {
		return this.ord;
	}

	public void setOrd(Integer ord) {
		this.ord = ord;
	}

}
