package cn.net.tongfang.framework.security.vo;

// Generated 2013-11-10 23:30:07 by Hibernate Tools 3.4.0.CR1

/**
 * ExamQuerySql generated by hbm2java
 */
public class ExamQuerySql implements java.io.Serializable {

	private String examname;
	private String sql;
	private String wherestr;
	private String orderby;

	public ExamQuerySql() {
	}

	public ExamQuerySql(String examname, String sql) {
		this.examname = examname;
		this.sql = sql;
	}

	public ExamQuerySql(String examname, String sql, String wherestr, String orderby) {
		this.examname = examname;
		this.sql = sql;
		this.wherestr = wherestr;
		this.orderby = orderby;
	}

	public String getExamname() {
		return this.examname;
	}

	public void setExamname(String examname) {
		this.examname = examname;
	}

	public String getSql() {
		return this.sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

	public String getWherestr() {
		return this.wherestr;
	}

	public void setWherestr(String wherestr) {
		this.wherestr = wherestr;
	}

	public String getOrderby() {
		return this.orderby;
	}

	public void setOrderby(String orderby) {
		this.orderby = orderby;
	}

}
