package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * ExamMedications generated by hbm2java
 */
public class ExamMedications implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private String drugName;
	private String usageWay;
	private String dosage;
	private String drugTime;
	private String dependency;

	public ExamMedications() {
	}

	public ExamMedications(String medicalExamId, String drugName) {
		this.medicalExamId = medicalExamId;
		this.drugName = drugName;
	}

	public ExamMedications(String medicalExamId, String drugName,
			String usageWay, String dosage, String drugTime, String dependency) {
		this.medicalExamId = medicalExamId;
		this.drugName = drugName;
		this.usageWay = usageWay;
		this.dosage = dosage;
		this.drugTime = drugTime;
		this.dependency = dependency;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public String getDrugName() {
		return this.drugName;
	}

	public void setDrugName(String drugName) {
		this.drugName = drugName;
	}

	public String getUsageWay() {
		return this.usageWay;
	}

	public void setUsageWay(String usageWay) {
		this.usageWay = usageWay;
	}

	public String getDosage() {
		return this.dosage;
	}

	public void setDosage(String dosage) {
		this.dosage = dosage;
	}

	public String getDrugTime() {
		return this.drugTime;
	}

	public void setDrugTime(String drugTime) {
		this.drugTime = drugTime;
	}

	public String getDependency() {
		return this.dependency;
	}

	public void setDependency(String dependency) {
		this.dependency = dependency;
	}

}
