package cn.net.tongfang.framework.security.vo;

// Generated 2013-11-10 1:20:52 by Hibernate Tools 3.4.0.CR1

/**
 * ExamExamcfgFileno generated by hbm2java
 */
public class ExamExamcfgFileno implements java.io.Serializable {

	private int id;
	private String examname;
	private String itemname;
	private boolean isfileno;
	private int ord;
	private String querytype;

	public ExamExamcfgFileno() {
	}

	public ExamExamcfgFileno(int id, String examname, String itemname, boolean isfileno, int ord) {
		this.id = id;
		this.examname = examname;
		this.itemname = itemname;
		this.isfileno = isfileno;
		this.ord = ord;
	}

	public ExamExamcfgFileno(int id, String examname, String itemname, boolean isfileno, int ord, String querytype) {
		this.id = id;
		this.examname = examname;
		this.itemname = itemname;
		this.isfileno = isfileno;
		this.ord = ord;
		this.querytype = querytype;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getExamname() {
		return this.examname;
	}

	public void setExamname(String examname) {
		this.examname = examname;
	}

	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	public boolean isIsfileno() {
		return this.isfileno;
	}

	public void setIsfileno(boolean isfileno) {
		this.isfileno = isfileno;
	}

	public int getOrd() {
		return this.ord;
	}

	public void setOrd(int ord) {
		this.ord = ord;
	}

	public String getQuerytype() {
		return this.querytype;
	}

	public void setQuerytype(String querytype) {
		this.querytype = querytype;
	}

}
