package cn.net.tongfang.framework.security.vo;

// Generated 2013-11-5 13:35:18 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * ExportMain generated by hbm2java
 */
public class ExportMain implements java.io.Serializable {

	private int id;
	private String name;
	private String sql;
	private Serializable orderby;
	private Serializable groupby;

	public ExportMain() {
	}

	public ExportMain(int id, String name, String sql) {
		this.id = id;
		this.name = name;
		this.sql = sql;
	}

	public ExportMain(int id, String name, String sql, Serializable orderby,
			Serializable groupby) {
		this.id = id;
		this.name = name;
		this.sql = sql;
		this.orderby = orderby;
		this.groupby = groupby;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSql() {
		return this.sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

	public Serializable getOrderby() {
		return this.orderby;
	}

	public void setOrderby(Serializable orderby) {
		this.orderby = orderby;
	}

	public Serializable getGroupby() {
		return this.groupby;
	}

	public void setGroupby(Serializable groupby) {
		this.groupby = groupby;
	}

}
