package cn.net.tongfang.framework.security.vo;

// Generated 2013-11-5 13:35:18 by Hibernate Tools 3.4.0.CR1

/**
 * ExportSub generated by hbm2java
 */
public class ExportSub implements java.io.Serializable {

	private int id;
	private int mainid;
	private String name;
	private String colstr;
	private String type;
	private Integer ord;

	public ExportSub() {
	}

	public ExportSub(int id, int mainid, String name, String colstr, String type) {
		this.id = id;
		this.mainid = mainid;
		this.name = name;
		this.colstr = colstr;
		this.type = type;
	}

	public ExportSub(int id, int mainid, String name, String colstr,
			String type, Integer ord) {
		this.id = id;
		this.mainid = mainid;
		this.name = name;
		this.colstr = colstr;
		this.type = type;
		this.ord = ord;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getMainid() {
		return this.mainid;
	}

	public void setMainid(int mainid) {
		this.mainid = mainid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getColstr() {
		return this.colstr;
	}

	public void setColstr(String colstr) {
		this.colstr = colstr;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getOrd() {
		return this.ord;
	}

	public void setOrd(Integer ord) {
		this.ord = ord;
	}

}
