package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * EyeSick generated by hbm2java
 */
public class EyeSick implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private Integer eyeSickId;

	public EyeSick() {
	}

	public EyeSick(String medicalExamId, Integer eyeSickId) {
		this.medicalExamId = medicalExamId;
		this.eyeSickId = eyeSickId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public Integer getEyeSickId() {
		return this.eyeSickId;
	}

	public void setEyeSickId(Integer eyeSickId) {
		this.eyeSickId = eyeSickId;
	}

}
