package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * FaceColor generated by hbm2java
 */
public class FaceColor implements java.io.Serializable {

	private String id;
	private String babyVisitId;
	private Integer faceColorId;

	public FaceColor() {
	}

	public FaceColor(String babyVisitId, Integer faceColorId) {
		this.babyVisitId = babyVisitId;
		this.faceColorId = faceColorId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBabyVisitId() {
		return this.babyVisitId;
	}

	public void setBabyVisitId(String babyVisitId) {
		this.babyVisitId = babyVisitId;
	}

	public Integer getFaceColorId() {
		return this.faceColorId;
	}

	public void setFaceColorId(Integer faceColorId) {
		this.faceColorId = faceColorId;
	}

}
