package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * FemeFamilyHistory generated by hbm2java
 */
public class FemeFamilyHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String firstVistBeforeBornId;
	private Integer femeFamilyHistoryId;

	public FemeFamilyHistory() {
	}

	public FemeFamilyHistory(String firstVistBeforeBornId,
			Integer femeFamilyHistoryId) {
		this.firstVistBeforeBornId = firstVistBeforeBornId;
		this.femeFamilyHistoryId = femeFamilyHistoryId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFirstVistBeforeBornId() {
		return this.firstVistBeforeBornId;
	}

	public void setFirstVistBeforeBornId(String firstVistBeforeBornId) {
		this.firstVistBeforeBornId = firstVistBeforeBornId;
	}

	public Integer getFemeFamilyHistoryId() {
		return this.femeFamilyHistoryId;
	}

	public void setFemeFamilyHistoryId(Integer femeFamilyHistoryId) {
		this.femeFamilyHistoryId = femeFamilyHistoryId;
	}

}
