package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * FemeSecretion generated by hbm2java
 */
public class FemeSecretion implements java.io.Serializable {

	private String id;
	private String firstVistBeforeBornId;
	private Integer femeSecretionId;

	public FemeSecretion() {
	}

	public FemeSecretion(String firstVistBeforeBornId, Integer femeSecretionId) {
		this.firstVistBeforeBornId = firstVistBeforeBornId;
		this.femeSecretionId = femeSecretionId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFirstVistBeforeBornId() {
		return this.firstVistBeforeBornId;
	}

	public void setFirstVistBeforeBornId(String firstVistBeforeBornId) {
		this.firstVistBeforeBornId = firstVistBeforeBornId;
	}

	public Integer getFemeSecretionId() {
		return this.femeSecretionId;
	}

	public void setFemeSecretionId(Integer femeSecretionId) {
		this.femeSecretionId = femeSecretionId;
	}

}
