package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * FemePastHistory generated by hbm2java
 */
public class FemePastHistory implements java.io.Serializable {

	private String id;
	private String firstVistBeforeBornId;
	private Integer femePastHistoryId;

	public FemePastHistory() {
	}

	public FemePastHistory(String firstVistBeforeBornId,
			Integer femePastHistoryId) {
		this.firstVistBeforeBornId = firstVistBeforeBornId;
		this.femePastHistoryId = femePastHistoryId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFirstVistBeforeBornId() {
		return this.firstVistBeforeBornId;
	}

	public void setFirstVistBeforeBornId(String firstVistBeforeBornId) {
		this.firstVistBeforeBornId = firstVistBeforeBornId;
	}

	public Integer getFemePastHistoryId() {
		return this.femePastHistoryId;
	}

	public void setFemePastHistoryId(Integer femePastHistoryId) {
		this.femePastHistoryId = femePastHistoryId;
	}

}
