package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * FuriousSymptom generated by hbm2java
 */
public class FuriousSymptom implements java.io.Serializable {

	private String id;
	private String furiousInfoId;
	private Integer furiousSymptomId;

	public FuriousSymptom() {
	}

	public FuriousSymptom(String furiousInfoId, Integer furiousSymptomId) {
		this.furiousInfoId = furiousInfoId;
		this.furiousSymptomId = furiousSymptomId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFuriousInfoId() {
		return this.furiousInfoId;
	}

	public void setFuriousInfoId(String furiousInfoId) {
		this.furiousInfoId = furiousInfoId;
	}

	public Integer getFuriousSymptomId() {
		return this.furiousSymptomId;
	}

	public void setFuriousSymptomId(Integer furiousSymptomId) {
		this.furiousSymptomId = furiousSymptomId;
	}

}
