package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * FuriousHealing generated by hbm2java
 */
public class FuriousHealing implements java.io.Serializable {

	private String id;
	private String furiousVisitId;
	private Integer furiousHealingId;

	public FuriousHealing() {
	}

	public FuriousHealing(String furiousVisitId, Integer furiousHealingId) {
		this.furiousVisitId = furiousVisitId;
		this.furiousHealingId = furiousHealingId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFuriousVisitId() {
		return this.furiousVisitId;
	}

	public void setFuriousVisitId(String furiousVisitId) {
		this.furiousVisitId = furiousVisitId;
	}

	public Integer getFuriousHealingId() {
		return this.furiousHealingId;
	}

	public void setFuriousHealingId(Integer furiousHealingId) {
		this.furiousHealingId = furiousHealingId;
	}

}
