package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * FuriousVisitSymptom generated by hbm2java
 */
public class FuriousVisitSymptom implements java.io.Serializable {

	private String id;
	private String furiousVisitId;
	private Integer furiousVisitSymptomId;

	public FuriousVisitSymptom() {
	}

	public FuriousVisitSymptom(String furiousVisitId,
			Integer furiousVisitSymptomId) {
		this.furiousVisitId = furiousVisitId;
		this.furiousVisitSymptomId = furiousVisitSymptomId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFuriousVisitId() {
		return this.furiousVisitId;
	}

	public void setFuriousVisitId(String furiousVisitId) {
		this.furiousVisitId = furiousVisitId;
	}

	public Integer getFuriousVisitSymptomId() {
		return this.furiousVisitSymptomId;
	}

	public void setFuriousVisitSymptomId(Integer furiousVisitSymptomId) {
		this.furiousVisitSymptomId = furiousVisitSymptomId;
	}

}
