package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * Galactophore generated by hbm2java
 */
public class Galactophore implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private Integer galactophoreId;

	public Galactophore() {
	}

	public Galactophore(String medicalExamId, Integer galactophoreId) {
		this.medicalExamId = medicalExamId;
		this.galactophoreId = galactophoreId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public Integer getGalactophoreId() {
		return this.galactophoreId;
	}

	public void setGalactophoreId(Integer galactophoreId) {
		this.galactophoreId = galactophoreId;
	}

}
