package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * HarnsSick generated by hbm2java
 */
public class HarnsSick implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private Integer harnsSickId;

	public HarnsSick() {
	}

	public HarnsSick(String medicalExamId, Integer harnsSickId) {
		this.medicalExamId = medicalExamId;
		this.harnsSickId = harnsSickId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public Integer getHarnsSickId() {
		return this.harnsSickId;
	}

	public void setHarnsSickId(Integer harnsSickId) {
		this.harnsSickId = harnsSickId;
	}

}
