package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * HealthFileKey generated by hbm2java
 */
public class HealthFileKey implements java.io.Serializable {

	private String districtNumber;
	private Integer maxKey;

	public HealthFileKey() {
	}

	public HealthFileKey(String districtNumber, Integer maxKey) {
		this.districtNumber = districtNumber;
		this.maxKey = maxKey;
	}

	public String getDistrictNumber() {
		return this.districtNumber;
	}

	public void setDistrictNumber(String districtNumber) {
		this.districtNumber = districtNumber;
	}

	public Integer getMaxKey() {
		return this.maxKey;
	}

	public void setMaxKey(Integer maxKey) {
		this.maxKey = maxKey;
	}

}
