package cn.net.tongfang.framework.security.vo;

// Generated 2013-11-7 2:58:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * HealthFileHistory2 generated by hbm2java
 */
public class HealthFileHistory2 implements java.io.Serializable {

	private long id;
	private String filename;
	private String name;
	private String sex;
	private String idcard;
	private Date birthday;
	private String fileno;
	private String pastname;
	private String address;
	private String raddress;
	private String tel;
	private String xz;
	private String cwh;
	private String jddw;
	private String jdr;
	private String zrys;
	private Date jdrq;
	private String districtId;
	private String linkFileno;

	public HealthFileHistory2() {
	}

	public HealthFileHistory2(long id) {
		this.id = id;
	}

	public HealthFileHistory2(long id, String filename, String name,
			String sex, String idcard, Date birthday, String fileno,
			String pastname, String address, String raddress, String tel,
			String xz, String cwh, String jddw, String jdr, String zrys,
			Date jdrq, String districtId, String linkFileno) {
		this.id = id;
		this.filename = filename;
		this.name = name;
		this.sex = sex;
		this.idcard = idcard;
		this.birthday = birthday;
		this.fileno = fileno;
		this.pastname = pastname;
		this.address = address;
		this.raddress = raddress;
		this.tel = tel;
		this.xz = xz;
		this.cwh = cwh;
		this.jddw = jddw;
		this.jdr = jdr;
		this.zrys = zrys;
		this.jdrq = jdrq;
		this.districtId = districtId;
		this.linkFileno = linkFileno;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getFileno() {
		return this.fileno;
	}

	public void setFileno(String fileno) {
		this.fileno = fileno;
	}

	public String getPastname() {
		return this.pastname;
	}

	public void setPastname(String pastname) {
		this.pastname = pastname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getRaddress() {
		return this.raddress;
	}

	public void setRaddress(String raddress) {
		this.raddress = raddress;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getXz() {
		return this.xz;
	}

	public void setXz(String xz) {
		this.xz = xz;
	}

	public String getCwh() {
		return this.cwh;
	}

	public void setCwh(String cwh) {
		this.cwh = cwh;
	}

	public String getJddw() {
		return this.jddw;
	}

	public void setJddw(String jddw) {
		this.jddw = jddw;
	}

	public String getJdr() {
		return this.jdr;
	}

	public void setJdr(String jdr) {
		this.jdr = jdr;
	}

	public String getZrys() {
		return this.zrys;
	}

	public void setZrys(String zrys) {
		this.zrys = zrys;
	}

	public Date getJdrq() {
		return this.jdrq;
	}

	public void setJdrq(Date jdrq) {
		this.jdrq = jdrq;
	}

	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	public String getLinkFileno() {
		return this.linkFileno;
	}

	public void setLinkFileno(String linkFileno) {
		this.linkFileno = linkFileno;
	}

}
