package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * HealthDirect generated by hbm2java
 */
public class HealthDirect implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private Integer healthDirectId;

	public HealthDirect() {
	}

	public HealthDirect(String medicalExamId, Integer healthDirectId) {
		this.medicalExamId = medicalExamId;
		this.healthDirectId = healthDirectId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public Integer getHealthDirectId() {
		return this.healthDirectId;
	}

	public void setHealthDirectId(Integer healthDirectId) {
		this.healthDirectId = healthDirectId;
	}

}
