package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;

/**
 * HealthFile generated by hbm2java
 */
public class HealthFile implements java.io.Serializable {

	private String fileNo;
	private String name;
	private String address;
	private String residenceAddress;
	private String tel;
	private String township;
	private String village;
	private String buildUnit;
	private String buildPerson;
	private String doctor;
	private Timestamp buildDate;
	private String districtNumber;
	private String namePng;
	private String inputPersonId;
	private Timestamp inputDate;
	private Timestamp lastModifyDate;
	private String modifyPerson;
	private String barCode;
	private Integer isOverCount;
	private Integer isModifyOrNew;
	private PersonalInfo personalInfo;
	private VaccineImmune vaccineImmune;
	private String paperFileNo;
	private Integer status;
	private String nation;
	public HealthFile() {
	}

	public HealthFile(String fileNo, String name) {
		this.fileNo = fileNo;
		this.name = name;
	}

	public HealthFile(String fileNo, String name, String address,
			String residenceAddress, String tel, String township,
			String village, String buildUnit, String buildPerson,
			String doctor, Timestamp buildDate, String districtNumber,
			String namePng, String inputPersonId, Timestamp inputDate,
			Timestamp lastModifyDate, String modifyPerson,
			PersonalInfo personalInfo,String barCode,Integer isOverCount,
			Integer isModifyOrNew,String paperFileNo,VaccineImmune vaccineImmune,
			Integer status) {
		this.fileNo = fileNo;
		this.name = name;
		this.address = address;
		this.residenceAddress = residenceAddress;
		this.tel = tel;
		this.township = township;
		this.village = village;
		this.buildUnit = buildUnit;
		this.buildPerson = buildPerson;
		this.doctor = doctor;
		this.buildDate = buildDate;
		this.districtNumber = districtNumber;
		this.namePng = namePng;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
		this.lastModifyDate = lastModifyDate;
		this.modifyPerson = modifyPerson;
		this.personalInfo = personalInfo;
		this.barCode = barCode;
		this.isOverCount = isOverCount;
		this.isModifyOrNew = isModifyOrNew;
		this.paperFileNo = paperFileNo;
		this.vaccineImmune = vaccineImmune;
		this.status = status;
	}

	public Timestamp getLastModifyDate() {
		return lastModifyDate;
	}

	public void setLastModifyDate(Timestamp lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public String getModifyPerson() {
		return modifyPerson;
	}

	public void setModifyPerson(String modifyPerson) {
		this.modifyPerson = modifyPerson;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getResidenceAddress() {
		return this.residenceAddress;
	}

	public void setResidenceAddress(String residenceAddress) {
		this.residenceAddress = residenceAddress;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getTownship() {
		return this.township;
	}

	public void setTownship(String township) {
		this.township = township;
	}

	public String getVillage() {
		return this.village;
	}

	public void setVillage(String village) {
		this.village = village;
	}

	public String getBuildUnit() {
		return this.buildUnit;
	}

	public void setBuildUnit(String buildUnit) {
		this.buildUnit = buildUnit;
	}

	public String getBuildPerson() {
		return this.buildPerson;
	}

	public void setBuildPerson(String buildPerson) {
		this.buildPerson = buildPerson;
	}

	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

	public Timestamp getBuildDate() {
		return this.buildDate;
	}

	public void setBuildDate(Timestamp buildDate) {
		this.buildDate = buildDate;
	}

	public String getDistrictNumber() {
		return this.districtNumber;
	}

	public void setDistrictNumber(String districtNumber) {
		this.districtNumber = districtNumber;
	}

	public String getNamePng() {
		return this.namePng;
	}

	public void setNamePng(String namePng) {
		this.namePng = namePng;
	}

	public String getInputPersonId() {
		return this.inputPersonId;
	}

	public void setInputPersonId(String inputPersonId) {
		this.inputPersonId = inputPersonId;
	}

	public Timestamp getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
	}

	public PersonalInfo getPersonalInfo() {
		return personalInfo;
	}

	public void setPersonalInfo(PersonalInfo personalInfo) {
		this.personalInfo = personalInfo;
	}

	public String getBarCode() {
		return barCode;
	}

	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}

	public Integer getIsOverCount() {
		return isOverCount;
	}

	public void setIsOverCount(Integer isOverCount) {
		this.isOverCount = isOverCount;
	}

	public Integer getIsModifyOrNew() {
		return isModifyOrNew;
	}

	public void setIsModifyOrNew(Integer isModifyOrNew) {
		this.isModifyOrNew = isModifyOrNew;
	}

	public String getPaperFileNo() {
		return paperFileNo;
	}

	public void setPaperFileNo(String paperFileNo) {
		this.paperFileNo = paperFileNo;
	}

	public VaccineImmune getVaccineImmune() {
		return vaccineImmune;
	}

	public void setVaccineImmune(VaccineImmune vaccineImmune) {
		this.vaccineImmune = vaccineImmune;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public String getNation() {
		return nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

}
