package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * HeartSick generated by hbm2java
 */
public class HeartSick implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private Integer heartSickId;

	public HeartSick() {
	}

	public HeartSick(String medicalExamId, Integer heartSickId) {
		this.medicalExamId = medicalExamId;
		this.heartSickId = heartSickId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public Integer getHeartSickId() {
		return this.heartSickId;
	}

	public void setHeartSickId(Integer heartSickId) {
		this.heartSickId = heartSickId;
	}

}
