package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * HypertensionSymptom generated by hbm2java
 */
public class HypertensionSymptom implements java.io.Serializable {

	private String id;
	private String hypertensionVisitId;
	private Integer hypertensionSymptomId;

	public HypertensionSymptom() {
	}

	public HypertensionSymptom(String hypertensionVisitId,
			Integer hypertensionSymptomId) {
		this.hypertensionVisitId = hypertensionVisitId;
		this.hypertensionSymptomId = hypertensionSymptomId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getHypertensionVisitId() {
		return this.hypertensionVisitId;
	}

	public void setHypertensionVisitId(String hypertensionVisitId) {
		this.hypertensionVisitId = hypertensionVisitId;
	}

	public Integer getHypertensionSymptomId() {
		return this.hypertensionSymptomId;
	}

	public void setHypertensionSymptomId(Integer hypertensionSymptomId) {
		this.hypertensionSymptomId = hypertensionSymptomId;
	}

}
