package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * HypertensionMedications generated by hbm2java
 */
public class HypertensionMedications implements java.io.Serializable {

	private String id;
	private String hypertensionVisitId;
	private String drugName;
	private String usage;
	private String dosage;

	public HypertensionMedications() {
	}

	public HypertensionMedications(String hypertensionVisitId, String drugName,
			String usage, String dosage) {
		this.hypertensionVisitId = hypertensionVisitId;
		this.drugName = drugName;
		this.usage = usage;
		this.dosage = dosage;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getHypertensionVisitId() {
		return this.hypertensionVisitId;
	}

	public void setHypertensionVisitId(String hypertensionVisitId) {
		this.hypertensionVisitId = hypertensionVisitId;
	}

	public String getDrugName() {
		return this.drugName;
	}

	public void setDrugName(String drugName) {
		this.drugName = drugName;
	}

	public String getUsage() {
		return this.usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	public String getDosage() {
		return this.dosage;
	}

	public void setDosage(String dosage) {
		this.dosage = dosage;
	}

}
