package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;

/**
 * InfectionReport generated by hbm2java
 */
public class InfectionReport implements java.io.Serializable {

	private String id;
	private Integer orgId;
	private String reportId;
	private Timestamp date;
	private String reportType;
	private String name;
	private String genearchName;
	private String cardId;
	private String sex;
	private Timestamp birthday;
	private Integer age;
	private String ageUnit;
	private String collaborator;
	private String unit;
	private String phone;
	private String area;
	private String address;
	private String occupation;
	private String sickKind;
	private Timestamp beginDate;
	private Timestamp cureDate;
	private Timestamp dieDate;
	private String firstInfection;
	private String secondInfection;
	private String thirdInfection;
	private String otherInfection;
	private String confirmInfection;
	private String reason;
	private String linkPhone;
	private String reportPerson;
	private String remark;
	private String inputPersonId;
	private Timestamp inputDate;

	public InfectionReport() {
	}

	public InfectionReport(Integer orgId, String inputPersonId,
			Timestamp inputDate) {
		this.orgId = orgId;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
	}

	public InfectionReport(Integer orgId, String reportId, Timestamp date,
			String reportType, String name, String genearchName, String cardId,
			String sex, Timestamp birthday, Integer age, String ageUnit,
			String collaborator, String unit, String phone, String area,
			String address, String occupation, String sickKind,
			Timestamp beginDate, Timestamp cureDate, Timestamp dieDate,
			String firstInfection, String secondInfection,
			String thirdInfection, String otherInfection,
			String confirmInfection, String reason, String linkPhone,
			String reportPerson, String remark, String inputPersonId,
			Timestamp inputDate) {
		this.orgId = orgId;
		this.reportId = reportId;
		this.date = date;
		this.reportType = reportType;
		this.name = name;
		this.genearchName = genearchName;
		this.cardId = cardId;
		this.sex = sex;
		this.birthday = birthday;
		this.age = age;
		this.ageUnit = ageUnit;
		this.collaborator = collaborator;
		this.unit = unit;
		this.phone = phone;
		this.area = area;
		this.address = address;
		this.occupation = occupation;
		this.sickKind = sickKind;
		this.beginDate = beginDate;
		this.cureDate = cureDate;
		this.dieDate = dieDate;
		this.firstInfection = firstInfection;
		this.secondInfection = secondInfection;
		this.thirdInfection = thirdInfection;
		this.otherInfection = otherInfection;
		this.confirmInfection = confirmInfection;
		this.reason = reason;
		this.linkPhone = linkPhone;
		this.reportPerson = reportPerson;
		this.remark = remark;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	public String getReportId() {
		return this.reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	public Timestamp getDate() {
		return this.date;
	}

	public void setDate(Timestamp date) {
		this.date = date;
	}

	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGenearchName() {
		return this.genearchName;
	}

	public void setGenearchName(String genearchName) {
		this.genearchName = genearchName;
	}

	public String getCardId() {
		return this.cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Timestamp getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Timestamp birthday) {
		this.birthday = birthday;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getAgeUnit() {
		return this.ageUnit;
	}

	public void setAgeUnit(String ageUnit) {
		this.ageUnit = ageUnit;
	}

	public String getCollaborator() {
		return this.collaborator;
	}

	public void setCollaborator(String collaborator) {
		this.collaborator = collaborator;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getSickKind() {
		return this.sickKind;
	}

	public void setSickKind(String sickKind) {
		this.sickKind = sickKind;
	}

	public Timestamp getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Timestamp beginDate) {
		this.beginDate = beginDate;
	}

	public Timestamp getCureDate() {
		return this.cureDate;
	}

	public void setCureDate(Timestamp cureDate) {
		this.cureDate = cureDate;
	}

	public Timestamp getDieDate() {
		return this.dieDate;
	}

	public void setDieDate(Timestamp dieDate) {
		this.dieDate = dieDate;
	}

	public String getFirstInfection() {
		return this.firstInfection;
	}

	public void setFirstInfection(String firstInfection) {
		this.firstInfection = firstInfection;
	}

	public String getSecondInfection() {
		return this.secondInfection;
	}

	public void setSecondInfection(String secondInfection) {
		this.secondInfection = secondInfection;
	}

	public String getThirdInfection() {
		return this.thirdInfection;
	}

	public void setThirdInfection(String thirdInfection) {
		this.thirdInfection = thirdInfection;
	}

	public String getOtherInfection() {
		return this.otherInfection;
	}

	public void setOtherInfection(String otherInfection) {
		this.otherInfection = otherInfection;
	}

	public String getConfirmInfection() {
		return this.confirmInfection;
	}

	public void setConfirmInfection(String confirmInfection) {
		this.confirmInfection = confirmInfection;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getLinkPhone() {
		return this.linkPhone;
	}

	public void setLinkPhone(String linkPhone) {
		this.linkPhone = linkPhone;
	}

	public String getReportPerson() {
		return this.reportPerson;
	}

	public void setReportPerson(String reportPerson) {
		this.reportPerson = reportPerson;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getInputPersonId() {
		return this.inputPersonId;
	}

	public void setInputPersonId(String inputPersonId) {
		this.inputPersonId = inputPersonId;
	}

	public Timestamp getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
	}

}
