package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * MedicalExam generated by hbm2java
 */
public class MedicalExam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String fileNo;
	private Timestamp examDate;
	private String doctor;
	private String symptomOther;
	private BigDecimal general01;
	private Integer general02;
	private Integer general03;
	private Integer general04;
	private Integer general05;
	private Integer general06;
	private Integer general07;
	private BigDecimal general08;
	private BigDecimal general09;
	private BigDecimal general10;
	private BigDecimal general11;//null
	private BigDecimal general12;
	private BigDecimal general13;//null
	private String general14;
	private Integer general15;
	private String general16;
	private Integer general17;
	private String life01;
	private String life02;
	private String life03;
	private String life04;
	private String life05other;
	private String life06;
	private Integer life07;
	private Integer life08;
	private Integer life09;
	private String life10;
	private String life11;
	private String life12;
	private Integer life13;
	private Integer life14;
	private Integer life15;
	private String life16other;
	private String life17;//TODO 这里的类型不对
	private String life18;
	private String life19;
	private String life20;
	private Integer life21;
	private String life21other;
	private String life22;
	private Integer life23;
	private String life23other;
	private String life24;
	private Integer life25;
	private String life25other;
	private String life26;
	private Integer life27;
	private String life27other;
	private String life28;
	private Integer life29;
	private String life29other;
	private String viscera01;
	private String viscera02;
	private String viscera02description;
	private String viscera02description1;
	private String viscera02description2;
	private String viscera02description3;
	private String viscera03;
	private BigDecimal viscera04;
	private BigDecimal viscera05;
	private BigDecimal viscera06;
	private BigDecimal viscera07;
	private String viscera08;
	private String viscera09;
	private String body01;
	private String body01other;
	private String body02;
	private String body02other;
	private String body03;
	private String body03other;
	private Integer body04;
	private String body05;
	private String body05other;
	private String body06;
	private String body06other;
	private Integer body07;
	private String body08;
	private String body09;
	private String body09other;
	private String body10;
	private String body10other;
	private String body12;
	private String body12other;
	private String body13;
	private String body13other;
	private String body14;
	private String body14other;
	private String body15;
	private String body15other;
	private String body16;
	private String body17;
	private String body18;
	private String body18other;
	private String body19other;
	private String body20;
	private String body20other;
	private String body21;
	private String body21other;
	private String body22;
	private String body22other;
	private String body23;
	private String body23other;
	private String body24;
	private String body24other;
	private String body25;
	private BigDecimal exam01;
	private BigDecimal exam02;
	private BigDecimal exam03;
	private BigDecimal exam04;
	private BigDecimal exam05;
	private String exam06;
	private String exam07;
	private String exam08;
	private String exam09;
	private String exam10;
	private String exam11;
	private BigDecimal exam12;
	private String exam13;
	private BigDecimal exam14;
	private BigDecimal exam15;
	private BigDecimal exam16;
	private BigDecimal exam17;
	private BigDecimal exam18;
	private BigDecimal exam19;
	private BigDecimal exam20;
	private BigDecimal exam21;
	private BigDecimal exam22;
	private BigDecimal exam23;
	private BigDecimal exam24;
	private BigDecimal exam25;
	private BigDecimal exam26;
	private BigDecimal exam27;
	private String exam28;
	private String exam29;
	private String exam29other;
	private String exam30;
	private String exam30other;
	private String exam31;
	private String exam31other;
	private String exam32;
	private String exam32other;
	private String exam33;
	private String exam33other;
	private String exam34;
	private String chn01;
	private String chn02;
	private String chn03;
	private String chn04;
	private String chn05;
	private String chn06;
	private String chn07;
	private String chn08;
	private String chn09;
	private String problem01other;
	private String problem02other;
	private String problem03other;
	private String problem04other;
	private String problem05other;
	private String problem06;
	private String problem06other;
	private String problem07;
	private String problem07other;
	private String judge01;
	private String judge02;
	private String judge03;
	private String judge04;
	private String judge05;
	private String dangerControlOther1;
	private String dangerControlOther2;
	private String dangerControlOther3;
	private String inputPersonId;
	private Timestamp inputDate;
	private Integer age;
	
	private String oldManHealthEstimate;
	private String oldManLifeEstimate;
	private String execDistrictNum;

	public MedicalExam() {
	}

	public MedicalExam(String fileNo, Timestamp examDate, String inputPersonId,
			Timestamp inputDate) {
		this.fileNo = fileNo;
		this.examDate = examDate;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
	}

	
	

	public MedicalExam(String id, String fileNo, Timestamp examDate,
			String doctor, String symptomOther, BigDecimal general01,
			Integer general02, Integer general03, Integer general04,
			Integer general05, Integer general06, Integer general07,
			BigDecimal general08, BigDecimal general09, BigDecimal general10,
			BigDecimal general11, BigDecimal general12, BigDecimal general13,
			String general14, Integer general15, String general16,
			Integer general17, String life01, String life02, String life03,
			String life04, String life05other, String life06, Integer life07,
			Integer life08, Integer life09, String life10, String life11,
			String life12, Integer life13, Integer life14, Integer life15,
			String life16other, String life17, String life18, String life19,
			String life20, Integer life21, String life21other, String life22,
			Integer life23, String life23other, String life24, Integer life25,
			String life25other, String life26, Integer life27,
			String life27other, String life28, Integer life29,
			String life29other, String viscera01, String viscera02,
			String viscera02description, String viscera03,
			BigDecimal viscera04, BigDecimal viscera05, BigDecimal viscera06,
			BigDecimal viscera07, String viscera08, String viscera09,
			String body01, String body01other, String body02,
			String body02other, String body03, String body03other,
			Integer body04, String body05, String body05other, String body06,
			String body06other, Integer body07, String body08, String body09,
			String body09other, String body10, String body10other,
			String body12, String body12other, String body13,
			String body13other, String body14, String body14other,
			String body15, String body15other, String body16, String body17,
			String body18, String body18other, String body19other,
			String body20, String body20other, String body21,
			String body21other, String body22, String body22other,
			String body23, String body23other, String body24,
			String body24other, String body25, BigDecimal exam01,
			BigDecimal exam02, BigDecimal exam03, BigDecimal exam04,
			BigDecimal exam05, String exam06, String exam07, String exam08,
			String exam09, String exam10, String exam11, BigDecimal exam12,
			String exam13, BigDecimal exam14, BigDecimal exam15,
			BigDecimal exam16, BigDecimal exam17, BigDecimal exam18,
			BigDecimal exam19, BigDecimal exam20, BigDecimal exam21,
			BigDecimal exam22, BigDecimal exam23, BigDecimal exam24,
			BigDecimal exam25, BigDecimal exam26, BigDecimal exam27,
			String exam28, String exam29, String exam29other, String exam30,
			String exam30other, String exam31, String exam31other,
			String exam32, String exam32other, String exam33,
			String exam33other, String exam34, String chn01, String chn02,
			String chn03, String chn04, String chn05, String chn06,
			String chn07, String chn08, String chn09, String problem01other,
			String problem02other, String problem03other,
			String problem04other, String problem05other, String problem06,
			String problem06other, String problem07, String problem07other,
			String judge01, String judge02, String judge03, String judge04,
			String judge05, String dangerControlOther1,
			String dangerControlOther2, String dangerControlOther3,
			String inputPersonId, Timestamp inputDate, Integer age,
			String oldManHealthEstimate, String oldManLifeEstimate,String viscera02description1,
			String viscera02description2,String viscera02description3,String execDistrictNum) {
		super();
		this.id = id;
		this.fileNo = fileNo;
		this.examDate = examDate;
		this.doctor = doctor;
		this.symptomOther = symptomOther;
		this.general01 = general01;
		this.general02 = general02;
		this.general03 = general03;
		this.general04 = general04;
		this.general05 = general05;
		this.general06 = general06;
		this.general07 = general07;
		this.general08 = general08;
		this.general09 = general09;
		this.general10 = general10;
		this.general11 = general11;
		this.general12 = general12;
		this.general13 = general13;
		this.general14 = general14;
		this.general15 = general15;
		this.general16 = general16;
		this.general17 = general17;
		this.life01 = life01;
		this.life02 = life02;
		this.life03 = life03;
		this.life04 = life04;
		this.life05other = life05other;
		this.life06 = life06;
		this.life07 = life07;
		this.life08 = life08;
		this.life09 = life09;
		this.life10 = life10;
		this.life11 = life11;
		this.life12 = life12;
		this.life13 = life13;
		this.life14 = life14;
		this.life15 = life15;
		this.life16other = life16other;
		this.life17 = life17;
		this.life18 = life18;
		this.life19 = life19;
		this.life20 = life20;
		this.life21 = life21;
		this.life21other = life21other;
		this.life22 = life22;
		this.life23 = life23;
		this.life23other = life23other;
		this.life24 = life24;
		this.life25 = life25;
		this.life25other = life25other;
		this.life26 = life26;
		this.life27 = life27;
		this.life27other = life27other;
		this.life28 = life28;
		this.life29 = life29;
		this.life29other = life29other;
		this.viscera01 = viscera01;
		this.viscera02 = viscera02;
		this.viscera02description = viscera02description;
		this.viscera03 = viscera03;
		this.viscera04 = viscera04;
		this.viscera05 = viscera05;
		this.viscera06 = viscera06;
		this.viscera07 = viscera07;
		this.viscera08 = viscera08;
		this.viscera09 = viscera09;
		this.body01 = body01;
		this.body01other = body01other;
		this.body02 = body02;
		this.body02other = body02other;
		this.body03 = body03;
		this.body03other = body03other;
		this.body04 = body04;
		this.body05 = body05;
		this.body05other = body05other;
		this.body06 = body06;
		this.body06other = body06other;
		this.body07 = body07;
		this.body08 = body08;
		this.body09 = body09;
		this.body09other = body09other;
		this.body10 = body10;
		this.body10other = body10other;
		this.body12 = body12;
		this.body12other = body12other;
		this.body13 = body13;
		this.body13other = body13other;
		this.body14 = body14;
		this.body14other = body14other;
		this.body15 = body15;
		this.body15other = body15other;
		this.body16 = body16;
		this.body17 = body17;
		this.body18 = body18;
		this.body18other = body18other;
		this.body19other = body19other;
		this.body20 = body20;
		this.body20other = body20other;
		this.body21 = body21;
		this.body21other = body21other;
		this.body22 = body22;
		this.body22other = body22other;
		this.body23 = body23;
		this.body23other = body23other;
		this.body24 = body24;
		this.body24other = body24other;
		this.body25 = body25;
		this.exam01 = exam01;
		this.exam02 = exam02;
		this.exam03 = exam03;
		this.exam04 = exam04;
		this.exam05 = exam05;
		this.exam06 = exam06;
		this.exam07 = exam07;
		this.exam08 = exam08;
		this.exam09 = exam09;
		this.exam10 = exam10;
		this.exam11 = exam11;
		this.exam12 = exam12;
		this.exam13 = exam13;
		this.exam14 = exam14;
		this.exam15 = exam15;
		this.exam16 = exam16;
		this.exam17 = exam17;
		this.exam18 = exam18;
		this.exam19 = exam19;
		this.exam20 = exam20;
		this.exam21 = exam21;
		this.exam22 = exam22;
		this.exam23 = exam23;
		this.exam24 = exam24;
		this.exam25 = exam25;
		this.exam26 = exam26;
		this.exam27 = exam27;
		this.exam28 = exam28;
		this.exam29 = exam29;
		this.exam29other = exam29other;
		this.exam30 = exam30;
		this.exam30other = exam30other;
		this.exam31 = exam31;
		this.exam31other = exam31other;
		this.exam32 = exam32;
		this.exam32other = exam32other;
		this.exam33 = exam33;
		this.exam33other = exam33other;
		this.exam34 = exam34;
		this.chn01 = chn01;
		this.chn02 = chn02;
		this.chn03 = chn03;
		this.chn04 = chn04;
		this.chn05 = chn05;
		this.chn06 = chn06;
		this.chn07 = chn07;
		this.chn08 = chn08;
		this.chn09 = chn09;
		this.problem01other = problem01other;
		this.problem02other = problem02other;
		this.problem03other = problem03other;
		this.problem04other = problem04other;
		this.problem05other = problem05other;
		this.problem06 = problem06;
		this.problem06other = problem06other;
		this.problem07 = problem07;
		this.problem07other = problem07other;
		this.judge01 = judge01;
		this.judge02 = judge02;
		this.judge03 = judge03;
		this.judge04 = judge04;
		this.judge05 = judge05;
		this.dangerControlOther1 = dangerControlOther1;
		this.dangerControlOther2 = dangerControlOther2;
		this.dangerControlOther3 = dangerControlOther3;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
		this.age = age;
		this.oldManHealthEstimate = oldManHealthEstimate;
		this.oldManLifeEstimate = oldManLifeEstimate;
		this.viscera02description1 = viscera02description1;
		this.viscera02description2 = viscera02description2;
		this.viscera02description3 = viscera02description3;
		this.execDistrictNum = execDistrictNum;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public Timestamp getExamDate() {
		return this.examDate;
	}

	public void setExamDate(Timestamp examDate) {
		this.examDate = examDate;
	}

	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

	public String getSymptomOther() {
		return this.symptomOther;
	}

	public void setSymptomOther(String symptomOther) {
		this.symptomOther = symptomOther;
	}

	public BigDecimal getGeneral01() {
		return this.general01;
	}

	public void setGeneral01(BigDecimal general01) {
		this.general01 = general01;
	}

	public Integer getGeneral02() {
		return this.general02;
	}

	public void setGeneral02(Integer general02) {
		this.general02 = general02;
	}

	public Integer getGeneral03() {
		return this.general03;
	}

	public void setGeneral03(Integer general03) {
		this.general03 = general03;
	}

	public Integer getGeneral04() {
		return this.general04;
	}

	public void setGeneral04(Integer general04) {
		this.general04 = general04;
	}

	public Integer getGeneral05() {
		return this.general05;
	}

	public void setGeneral05(Integer general05) {
		this.general05 = general05;
	}

	public Integer getGeneral06() {
		return this.general06;
	}

	public void setGeneral06(Integer general06) {
		this.general06 = general06;
	}

	public Integer getGeneral07() {
		return this.general07;
	}

	public void setGeneral07(Integer general07) {
		this.general07 = general07;
	}

	public BigDecimal getGeneral08() {
		return this.general08;
	}

	public void setGeneral08(BigDecimal general08) {
		this.general08 = general08;
	}

	public BigDecimal getGeneral09() {
		return this.general09;
	}

	public void setGeneral09(BigDecimal general09) {
		this.general09 = general09;
	}

	public BigDecimal getGeneral10() {
		return this.general10;
	}

	public void setGeneral10(BigDecimal general10) {
		this.general10 = general10;
	}

	public BigDecimal getGeneral11() {
		return this.general11;
	}

	public void setGeneral11(BigDecimal general11) {
		this.general11 = general11;
	}

	public BigDecimal getGeneral12() {
		return this.general12;
	}

	public void setGeneral12(BigDecimal general12) {
		this.general12 = general12;
	}

	public BigDecimal getGeneral13() {
		return this.general13;
	}

	public void setGeneral13(BigDecimal general13) {
		this.general13 = general13;
	}

	public String getGeneral14() {
		return this.general14;
	}

	public void setGeneral14(String general14) {
		this.general14 = general14;
	}

	public Integer getGeneral15() {
		return this.general15;
	}

	public void setGeneral15(Integer general15) {
		this.general15 = general15;
	}

	public String getGeneral16() {
		return this.general16;
	}

	public void setGeneral16(String general16) {
		this.general16 = general16;
	}

	public Integer getGeneral17() {
		return this.general17;
	}

	public void setGeneral17(Integer general17) {
		this.general17 = general17;
	}

	public String getLife01() {
		return this.life01;
	}

	public void setLife01(String life01) {
		this.life01 = life01;
	}

	public String getLife02() {
		return this.life02;
	}

	public void setLife02(String life02) {
		this.life02 = life02;
	}

	public String getLife03() {
		return this.life03;
	}

	public void setLife03(String life03) {
		this.life03 = life03;
	}

	public String getLife04() {
		return this.life04;
	}

	public void setLife04(String life04) {
		this.life04 = life04;
	}

	public String getLife05other() {
		return this.life05other;
	}

	public void setLife05other(String life05other) {
		this.life05other = life05other;
	}

	public String getLife06() {
		return this.life06;
	}

	public void setLife06(String life06) {
		this.life06 = life06;
	}

	public Integer getLife07() {
		return this.life07;
	}

	public void setLife07(Integer life07) {
		this.life07 = life07;
	}

	public Integer getLife08() {
		return this.life08;
	}

	public void setLife08(Integer life08) {
		this.life08 = life08;
	}

	public Integer getLife09() {
		return this.life09;
	}

	public void setLife09(Integer life09) {
		this.life09 = life09;
	}

	public String getLife10() {
		return this.life10;
	}

	public void setLife10(String life10) {
		this.life10 = life10;
	}

	public String getLife11() {
		return this.life11;
	}

	public void setLife11(String life11) {
		this.life11 = life11;
	}

	public String getLife12() {
		return this.life12;
	}

	public void setLife12(String life12) {
		this.life12 = life12;
	}

	public Integer getLife13() {
		return this.life13;
	}

	public void setLife13(Integer life13) {
		this.life13 = life13;
	}

	public Integer getLife14() {
		return this.life14;
	}

	public void setLife14(Integer life14) {
		this.life14 = life14;
	}

	public Integer getLife15() {
		return this.life15;
	}

	public void setLife15(Integer life15) {
		this.life15 = life15;
	}

	public String getLife16other() {
		return this.life16other;
	}

	public void setLife16other(String life16other) {
		this.life16other = life16other;
	}

	public String getLife17() {
		return this.life17;
	}

	public void setLife17(String life17) {
		this.life17 = life17;
	}

	public String getLife18() {
		return this.life18;
	}

	public void setLife18(String life18) {
		this.life18 = life18;
	}

	public String getLife19() {
		return this.life19;
	}

	public void setLife19(String life19) {
		this.life19 = life19;
	}

	public String getLife20() {
		return this.life20;
	}

	public void setLife20(String life20) {
		this.life20 = life20;
	}

	public Integer getLife21() {
		return this.life21;
	}

	public void setLife21(Integer life21) {
		this.life21 = life21;
	}

	public String getLife21other() {
		return this.life21other;
	}

	public void setLife21other(String life21other) {
		this.life21other = life21other;
	}

	public String getLife22() {
		return this.life22;
	}

	public void setLife22(String life22) {
		this.life22 = life22;
	}

	public Integer getLife23() {
		return this.life23;
	}

	public void setLife23(Integer life23) {
		this.life23 = life23;
	}

	public String getLife23other() {
		return this.life23other;
	}

	public void setLife23other(String life23other) {
		this.life23other = life23other;
	}

	public String getLife24() {
		return this.life24;
	}

	public void setLife24(String life24) {
		this.life24 = life24;
	}

	public Integer getLife25() {
		return this.life25;
	}

	public void setLife25(Integer life25) {
		this.life25 = life25;
	}

	public String getLife25other() {
		return this.life25other;
	}

	public void setLife25other(String life25other) {
		this.life25other = life25other;
	}

	public String getViscera01() {
		return this.viscera01;
	}

	public void setViscera01(String viscera01) {
		this.viscera01 = viscera01;
	}

	public String getViscera02() {
		return this.viscera02;
	}

	public void setViscera02(String viscera02) {
		this.viscera02 = viscera02;
	}

	public String getViscera02description() {
		return this.viscera02description;
	}

	public void setViscera02description(String viscera02description) {
		this.viscera02description = viscera02description;
	}

	public String getViscera03() {
		return this.viscera03;
	}

	public void setViscera03(String viscera03) {
		this.viscera03 = viscera03;
	}

	public BigDecimal getViscera04() {
		return this.viscera04;
	}

	public void setViscera04(BigDecimal viscera04) {
		this.viscera04 = viscera04;
	}

	public BigDecimal getViscera05() {
		return this.viscera05;
	}

	public void setViscera05(BigDecimal viscera05) {
		this.viscera05 = viscera05;
	}

	public BigDecimal getViscera06() {
		return this.viscera06;
	}

	public void setViscera06(BigDecimal viscera06) {
		this.viscera06 = viscera06;
	}

	public BigDecimal getViscera07() {
		return this.viscera07;
	}

	public void setViscera07(BigDecimal viscera07) {
		this.viscera07 = viscera07;
	}

	public String getViscera08() {
		return this.viscera08;
	}

	public void setViscera08(String viscera08) {
		this.viscera08 = viscera08;
	}

	public String getViscera09() {
		return this.viscera09;
	}

	public void setViscera09(String viscera09) {
		this.viscera09 = viscera09;
	}

	public String getBody01() {
		return this.body01;
	}

	public void setBody01(String body01) {
		this.body01 = body01;
	}

	public String getBody01other() {
		return this.body01other;
	}

	public void setBody01other(String body01other) {
		this.body01other = body01other;
	}

	public String getBody02() {
		return this.body02;
	}

	public void setBody02(String body02) {
		this.body02 = body02;
	}

	public String getBody02other() {
		return this.body02other;
	}

	public void setBody02other(String body02other) {
		this.body02other = body02other;
	}

	public String getBody03() {
		return this.body03;
	}

	public void setBody03(String body03) {
		this.body03 = body03;
	}

	public String getBody03other() {
		return this.body03other;
	}

	public void setBody03other(String body03other) {
		this.body03other = body03other;
	}

	public Integer getBody04() {
		return this.body04;
	}

	public void setBody04(Integer body04) {
		this.body04 = body04;
	}

	public String getBody05() {
		return this.body05;
	}

	public void setBody05(String body05) {
		this.body05 = body05;
	}

	public String getBody05other() {
		return this.body05other;
	}

	public void setBody05other(String body05other) {
		this.body05other = body05other;
	}

	public String getBody06() {
		return this.body06;
	}

	public void setBody06(String body06) {
		this.body06 = body06;
	}

	public String getBody06other() {
		return this.body06other;
	}

	public void setBody06other(String body06other) {
		this.body06other = body06other;
	}

	public Integer getBody07() {
		return this.body07;
	}

	public void setBody07(Integer body07) {
		this.body07 = body07;
	}

	public String getBody08() {
		return this.body08;
	}

	public void setBody08(String body08) {
		this.body08 = body08;
	}

	public String getBody09() {
		return this.body09;
	}

	public void setBody09(String body09) {
		this.body09 = body09;
	}

	public String getBody09other() {
		return this.body09other;
	}

	public void setBody09other(String body09other) {
		this.body09other = body09other;
	}

	public String getBody10() {
		return this.body10;
	}

	public void setBody10(String body10) {
		this.body10 = body10;
	}

	public String getBody10other() {
		return this.body10other;
	}

	public void setBody10other(String body10other) {
		this.body10other = body10other;
	}

	public String getBody12() {
		return this.body12;
	}

	public void setBody12(String body12) {
		this.body12 = body12;
	}

	public String getBody12other() {
		return this.body12other;
	}

	public void setBody12other(String body12other) {
		this.body12other = body12other;
	}

	public String getBody13() {
		return this.body13;
	}

	public void setBody13(String body13) {
		this.body13 = body13;
	}

	public String getBody13other() {
		return this.body13other;
	}

	public void setBody13other(String body13other) {
		this.body13other = body13other;
	}

	public String getBody14() {
		return this.body14;
	}

	public void setBody14(String body14) {
		this.body14 = body14;
	}

	public String getBody14other() {
		return this.body14other;
	}

	public void setBody14other(String body14other) {
		this.body14other = body14other;
	}

	public String getBody15() {
		return this.body15;
	}

	public void setBody15(String body15) {
		this.body15 = body15;
	}

	public String getBody15other() {
		return this.body15other;
	}

	public void setBody15other(String body15other) {
		this.body15other = body15other;
	}

	public String getBody16() {
		return this.body16;
	}

	public void setBody16(String body16) {
		this.body16 = body16;
	}

	public String getBody17() {
		return this.body17;
	}

	public void setBody17(String body17) {
		this.body17 = body17;
	}

	public String getBody18() {
		return this.body18;
	}

	public void setBody18(String body18) {
		this.body18 = body18;
	}

	public String getBody18other() {
		return this.body18other;
	}

	public void setBody18other(String body18other) {
		this.body18other = body18other;
	}

	public String getBody19other() {
		return this.body19other;
	}

	public void setBody19other(String body19other) {
		this.body19other = body19other;
	}

	public String getBody20() {
		return this.body20;
	}

	public void setBody20(String body20) {
		this.body20 = body20;
	}

	public String getBody20other() {
		return this.body20other;
	}

	public void setBody20other(String body20other) {
		this.body20other = body20other;
	}

	public String getBody21() {
		return this.body21;
	}

	public void setBody21(String body21) {
		this.body21 = body21;
	}

	public String getBody21other() {
		return this.body21other;
	}

	public void setBody21other(String body21other) {
		this.body21other = body21other;
	}

	public String getBody22() {
		return this.body22;
	}

	public void setBody22(String body22) {
		this.body22 = body22;
	}

	public String getBody22other() {
		return this.body22other;
	}

	public void setBody22other(String body22other) {
		this.body22other = body22other;
	}

	public String getBody23() {
		return this.body23;
	}

	public void setBody23(String body23) {
		this.body23 = body23;
	}

	public String getBody23other() {
		return this.body23other;
	}

	public void setBody23other(String body23other) {
		this.body23other = body23other;
	}

	public String getBody24() {
		return this.body24;
	}

	public void setBody24(String body24) {
		this.body24 = body24;
	}

	public String getBody24other() {
		return this.body24other;
	}

	public void setBody24other(String body24other) {
		this.body24other = body24other;
	}

	public String getBody25() {
		return this.body25;
	}

	public void setBody25(String body25) {
		this.body25 = body25;
	}

	public BigDecimal getExam01() {
		return this.exam01;
	}

	public void setExam01(BigDecimal exam01) {
		this.exam01 = exam01;
	}

	public BigDecimal getExam02() {
		return this.exam02;
	}

	public void setExam02(BigDecimal exam02) {
		this.exam02 = exam02;
	}

	public BigDecimal getExam03() {
		return this.exam03;
	}

	public void setExam03(BigDecimal exam03) {
		this.exam03 = exam03;
	}

	public BigDecimal getExam04() {
		return this.exam04;
	}

	public void setExam04(BigDecimal exam04) {
		this.exam04 = exam04;
	}

	public BigDecimal getExam05() {
		return this.exam05;
	}

	public void setExam05(BigDecimal exam05) {
		this.exam05 = exam05;
	}

	public String getExam06() {
		return this.exam06;
	}

	public void setExam06(String exam06) {
		this.exam06 = exam06;
	}

	public String getExam07() {
		return this.exam07;
	}

	public void setExam07(String exam07) {
		this.exam07 = exam07;
	}

	public String getExam08() {
		return this.exam08;
	}

	public void setExam08(String exam08) {
		this.exam08 = exam08;
	}

	public String getExam09() {
		return this.exam09;
	}

	public void setExam09(String exam09) {
		this.exam09 = exam09;
	}

	public String getExam10() {
		return this.exam10;
	}

	public void setExam10(String exam10) {
		this.exam10 = exam10;
	}

	public String getExam11() {
		return this.exam11;
	}

	public void setExam11(String exam11) {
		this.exam11 = exam11;
	}

	public BigDecimal getExam12() {
		return this.exam12;
	}

	public void setExam12(BigDecimal exam12) {
		this.exam12 = exam12;
	}

	public String getExam13() {
		return this.exam13;
	}

	public void setExam13(String exam13) {
		this.exam13 = exam13;
	}

	public BigDecimal getExam14() {
		return this.exam14;
	}

	public void setExam14(BigDecimal exam14) {
		this.exam14 = exam14;
	}

	public BigDecimal getExam15() {
		return this.exam15;
	}

	public void setExam15(BigDecimal exam15) {
		this.exam15 = exam15;
	}

	public BigDecimal getExam16() {
		return this.exam16;
	}

	public void setExam16(BigDecimal exam16) {
		this.exam16 = exam16;
	}

	public BigDecimal getExam17() {
		return this.exam17;
	}

	public void setExam17(BigDecimal exam17) {
		this.exam17 = exam17;
	}

	public BigDecimal getExam18() {
		return this.exam18;
	}

	public void setExam18(BigDecimal exam18) {
		this.exam18 = exam18;
	}

	public BigDecimal getExam19() {
		return this.exam19;
	}

	public void setExam19(BigDecimal exam19) {
		this.exam19 = exam19;
	}

	public BigDecimal getExam20() {
		return this.exam20;
	}

	public void setExam20(BigDecimal exam20) {
		this.exam20 = exam20;
	}

	public BigDecimal getExam21() {
		return this.exam21;
	}

	public void setExam21(BigDecimal exam21) {
		this.exam21 = exam21;
	}

	public BigDecimal getExam22() {
		return this.exam22;
	}

	public void setExam22(BigDecimal exam22) {
		this.exam22 = exam22;
	}

	public BigDecimal getExam23() {
		return this.exam23;
	}

	public void setExam23(BigDecimal exam23) {
		this.exam23 = exam23;
	}

	public BigDecimal getExam24() {
		return this.exam24;
	}

	public void setExam24(BigDecimal exam24) {
		this.exam24 = exam24;
	}

	public BigDecimal getExam25() {
		return this.exam25;
	}

	public void setExam25(BigDecimal exam25) {
		this.exam25 = exam25;
	}

	public BigDecimal getExam26() {
		return this.exam26;
	}

	public void setExam26(BigDecimal exam26) {
		this.exam26 = exam26;
	}

	public BigDecimal getExam27() {
		return this.exam27;
	}

	public void setExam27(BigDecimal exam27) {
		this.exam27 = exam27;
	}

	public String getExam28() {
		return this.exam28;
	}

	public void setExam28(String exam28) {
		this.exam28 = exam28;
	}

	public String getExam29() {
		return this.exam29;
	}

	public void setExam29(String exam29) {
		this.exam29 = exam29;
	}

	public String getExam29other() {
		return this.exam29other;
	}

	public void setExam29other(String exam29other) {
		this.exam29other = exam29other;
	}

	public String getExam30() {
		return this.exam30;
	}

	public void setExam30(String exam30) {
		this.exam30 = exam30;
	}

	public String getExam30other() {
		return this.exam30other;
	}

	public void setExam30other(String exam30other) {
		this.exam30other = exam30other;
	}

	public String getExam31() {
		return this.exam31;
	}

	public void setExam31(String exam31) {
		this.exam31 = exam31;
	}

	public String getExam31other() {
		return this.exam31other;
	}

	public void setExam31other(String exam31other) {
		this.exam31other = exam31other;
	}

	public String getExam32() {
		return this.exam32;
	}

	public void setExam32(String exam32) {
		this.exam32 = exam32;
	}

	public String getExam32other() {
		return this.exam32other;
	}

	public void setExam32other(String exam32other) {
		this.exam32other = exam32other;
	}

	public String getExam33() {
		return this.exam33;
	}

	public void setExam33(String exam33) {
		this.exam33 = exam33;
	}

	public String getExam33other() {
		return this.exam33other;
	}

	public void setExam33other(String exam33other) {
		this.exam33other = exam33other;
	}

	public String getExam34() {
		return this.exam34;
	}

	public void setExam34(String exam34) {
		this.exam34 = exam34;
	}

	public String getChn01() {
		return this.chn01;
	}

	public void setChn01(String chn01) {
		this.chn01 = chn01;
	}

	public String getChn02() {
		return this.chn02;
	}

	public void setChn02(String chn02) {
		this.chn02 = chn02;
	}

	public String getChn03() {
		return this.chn03;
	}

	public void setChn03(String chn03) {
		this.chn03 = chn03;
	}

	public String getChn04() {
		return this.chn04;
	}

	public void setChn04(String chn04) {
		this.chn04 = chn04;
	}

	public String getChn05() {
		return this.chn05;
	}

	public void setChn05(String chn05) {
		this.chn05 = chn05;
	}

	public String getChn06() {
		return this.chn06;
	}

	public void setChn06(String chn06) {
		this.chn06 = chn06;
	}

	public String getChn07() {
		return this.chn07;
	}

	public void setChn07(String chn07) {
		this.chn07 = chn07;
	}

	public String getChn08() {
		return this.chn08;
	}

	public void setChn08(String chn08) {
		this.chn08 = chn08;
	}

	public String getChn09() {
		return this.chn09;
	}

	public void setChn09(String chn09) {
		this.chn09 = chn09;
	}

	public String getProblem01other() {
		return this.problem01other;
	}

	public void setProblem01other(String problem01other) {
		this.problem01other = problem01other;
	}

	public String getProblem02other() {
		return this.problem02other;
	}

	public void setProblem02other(String problem02other) {
		this.problem02other = problem02other;
	}

	public String getProblem03other() {
		return this.problem03other;
	}

	public void setProblem03other(String problem03other) {
		this.problem03other = problem03other;
	}

	public String getProblem04other() {
		return this.problem04other;
	}

	public void setProblem04other(String problem04other) {
		this.problem04other = problem04other;
	}

	public String getProblem05other() {
		return this.problem05other;
	}

	public void setProblem05other(String problem05other) {
		this.problem05other = problem05other;
	}

	public String getProblem06() {
		return this.problem06;
	}

	public void setProblem06(String problem06) {
		this.problem06 = problem06;
	}

	public String getProblem06other() {
		return this.problem06other;
	}

	public void setProblem06other(String problem06other) {
		this.problem06other = problem06other;
	}

	public String getProblem07() {
		return this.problem07;
	}

	public void setProblem07(String problem07) {
		this.problem07 = problem07;
	}

	public String getProblem07other() {
		return this.problem07other;
	}

	public void setProblem07other(String problem07other) {
		this.problem07other = problem07other;
	}

	public String getJudge01() {
		return this.judge01;
	}

	public void setJudge01(String judge01) {
		this.judge01 = judge01;
	}

	public String getJudge02() {
		return this.judge02;
	}

	public void setJudge02(String judge02) {
		this.judge02 = judge02;
	}

	public String getJudge03() {
		return this.judge03;
	}

	public void setJudge03(String judge03) {
		this.judge03 = judge03;
	}

	public String getJudge04() {
		return this.judge04;
	}

	public void setJudge04(String judge04) {
		this.judge04 = judge04;
	}

	public String getJudge05() {
		return this.judge05;
	}

	public void setJudge05(String judge05) {
		this.judge05 = judge05;
	}

	public String getDangerControlOther1() {
		return this.dangerControlOther1;
	}

	public void setDangerControlOther1(String dangerControlOther1) {
		this.dangerControlOther1 = dangerControlOther1;
	}

	public String getDangerControlOther2() {
		return this.dangerControlOther2;
	}

	public void setDangerControlOther2(String dangerControlOther2) {
		this.dangerControlOther2 = dangerControlOther2;
	}

	public String getDangerControlOther3() {
		return this.dangerControlOther3;
	}

	public void setDangerControlOther3(String dangerControlOther3) {
		this.dangerControlOther3 = dangerControlOther3;
	}

	public String getInputPersonId() {
		return this.inputPersonId;
	}

	public void setInputPersonId(String inputPersonId) {
		this.inputPersonId = inputPersonId;
	}

	public Timestamp getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getOldManHealthEstimate() {
		return oldManHealthEstimate;
	}

	public void setOldManHealthEstimate(String oldManHealthEstimate) {
		this.oldManHealthEstimate = oldManHealthEstimate;
	}

	public String getOldManLifeEstimate() {
		return oldManLifeEstimate;
	}

	public void setOldManLifeEstimate(String oldManLifeEstimate) {
		this.oldManLifeEstimate = oldManLifeEstimate;
	}

	public String getLife26() {
		return life26;
	}

	public void setLife26(String life26) {
		this.life26 = life26;
	}

	public Integer getLife27() {
		return life27;
	}

	public void setLife27(Integer life27) {
		this.life27 = life27;
	}

	public String getLife27other() {
		return life27other;
	}

	public void setLife27other(String life27other) {
		this.life27other = life27other;
	}

	public String getLife28() {
		return life28;
	}

	public void setLife28(String life28) {
		this.life28 = life28;
	}

	public Integer getLife29() {
		return life29;
	}

	public void setLife29(Integer life29) {
		this.life29 = life29;
	}

	public String getLife29other() {
		return life29other;
	}

	public void setLife29other(String life29other) {
		this.life29other = life29other;
	}

	public String getViscera02description1() {
		return viscera02description1;
	}

	public void setViscera02description1(String viscera02description1) {
		this.viscera02description1 = viscera02description1;
	}

	public String getViscera02description2() {
		return viscera02description2;
	}

	public void setViscera02description2(String viscera02description2) {
		this.viscera02description2 = viscera02description2;
	}

	public String getViscera02description3() {
		return viscera02description3;
	}

	public void setViscera02description3(String viscera02description3) {
		this.viscera02description3 = viscera02description3;
	}

	public String getExecDistrictNum() {
		return execDistrictNum;
	}

	public void setExecDistrictNum(String execDistrictNum) {
		this.execDistrictNum = execDistrictNum;
	}
	
}
