package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * Opshistory generated by hbm2java
 */
public class Opshistory implements java.io.Serializable {

	private String id;
	private String personalInfoId;
	private String opsname;
	private String opsdate;

	public Opshistory() {
	}

	public Opshistory(String personalInfoId, String opsname, String opsdate) {
		this.personalInfoId = personalInfoId;
		this.opsname = opsname;
		this.opsdate = opsdate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPersonalInfoId() {
		return this.personalInfoId;
	}

	public void setPersonalInfoId(String personalInfoId) {
		this.personalInfoId = personalInfoId;
	}

	public String getOpsname() {
		return this.opsname;
	}

	public void setOpsname(String opsname) {
		this.opsname = opsname;
	}

	public String getOpsdate() {
		return this.opsdate;
	}

	public void setOpsdate(String opsdate) {
		this.opsdate = opsdate;
	}

}
