package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;

/**
 * Reception generated by hbm2java
 */
public class Reception implements java.io.Serializable {

	private String id;
	private String fileNo;
	private Timestamp date;
	private String subjectiveInformation;
	private String impersonalInformation;
	private String evaluation;
	private String curePlan;
	private String doctor;
	private String inputPersonId;
	private Timestamp inputDate;
	private Integer orgId;
	private String execDistrictNum;
	
	public Reception() {
	}

	public Reception(String fileNo, Timestamp date, String inputPersonId,
			Timestamp inputDate) {
		this.fileNo = fileNo;
		this.date = date;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
	}

	public Reception(String fileNo, Timestamp date,
			String subjectiveInformation, String impersonalInformation,
			String evaluation, String curePlan, String doctor,
			String inputPersonId, Timestamp inputDate, Integer orgId,
			String execDistrictNum) {
		this.fileNo = fileNo;
		this.date = date;
		this.subjectiveInformation = subjectiveInformation;
		this.impersonalInformation = impersonalInformation;
		this.evaluation = evaluation;
		this.curePlan = curePlan;
		this.doctor = doctor;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
		this.orgId = orgId;
		this.execDistrictNum = execDistrictNum;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public Timestamp getDate() {
		return this.date;
	}

	public void setDate(Timestamp date) {
		this.date = date;
	}

	public String getSubjectiveInformation() {
		return this.subjectiveInformation;
	}

	public void setSubjectiveInformation(String subjectiveInformation) {
		this.subjectiveInformation = subjectiveInformation;
	}

	public String getImpersonalInformation() {
		return this.impersonalInformation;
	}

	public void setImpersonalInformation(String impersonalInformation) {
		this.impersonalInformation = impersonalInformation;
	}

	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}

	public String getCurePlan() {
		return this.curePlan;
	}

	public void setCurePlan(String curePlan) {
		this.curePlan = curePlan;
	}

	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

	public String getInputPersonId() {
		return this.inputPersonId;
	}

	public void setInputPersonId(String inputPersonId) {
		this.inputPersonId = inputPersonId;
	}

	public Timestamp getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
	}

	public Integer getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	public String getExecDistrictNum() {
		return execDistrictNum;
	}

	public void setExecDistrictNum(String execDistrictNum) {
		this.execDistrictNum = execDistrictNum;
	}

}
