package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

/**
 * SamTaxempcode generated by hbm2java
 */
public class SamTaxempcode implements java.io.Serializable {

	public static final int maskOperator = 0x1;
	public static final int maskDoctor = 0x2;
	public static final int maskNurse = 0x4;
	public static final int maskPublicDoctor = 0x8;
	
	private String loginname;
	private String username;
	private String password;
	private Integer orgId;
	private Timestamp createDate;
	private String validFlag;
	private String districtId;
	private Integer type;
	private Integer isLookAuthority;
	private Integer isStasticAuth;
	private District district;
	private SamTaxorgcode org;
	
	public SamTaxempcode() {
	}

	public SamTaxempcode(String loginname, String username, String password,
			Integer orgId, Timestamp createDate, String validFlag) {
		this.loginname = loginname;
		this.username = username;
		this.password = password;
		this.orgId = orgId;
		this.createDate = createDate;
		this.validFlag = validFlag;
	}

	public SamTaxempcode(String loginname, String username, String password,
			Integer orgId, Timestamp createDate, String validFlag,
			String districtId, Integer type,Integer isLookAuthority,
			Integer isStasticAuth) {
		this.loginname = loginname;
		this.username = username;
		this.password = password;
		this.orgId = orgId;
		this.createDate = createDate;
		this.validFlag = validFlag;
		this.districtId = districtId;
		this.type = type;
		this.isLookAuthority = isLookAuthority;
		this.isStasticAuth = isStasticAuth;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
	
	
	public void setTypeList( List typeList) {
		System.out.println( "setTypeList()");
		if ( typeList != null ) {
			int sum = 0;
			for (Object object : typeList) {
				int t = 0;
				try {
					if ( object instanceof Integer ) {
						t = ((Integer) object).intValue();
					} else {
						t = Integer.valueOf((String)object);
					}
				} catch (NumberFormatException e) {
					e.printStackTrace();
				} catch (Exception e) {
					e.printStackTrace();
				}
				sum += t;
			}
			this.type = sum;
			System.out.println("setTypeList(): " + this.type);
		}
	}
	
	public List<Integer> getTypeList() {
		List<Integer> list = new ArrayList<Integer>();
		if ( isOperator() ) list.add( maskOperator);
		if ( isDoctor() ) list.add( maskDoctor);
		if ( isNurse() ) list.add( maskNurse);
		if ( isPublicDoctor() ) list.add( maskPublicDoctor);
		System.out.println( "getTypeList(): " + list.size());
		return list;
	}
	
	public District getDistrict() {
		return district;
	}
	public void setDistrict(District district) {
		this.district = district;
	}
	public SamTaxorgcode getOrg() {
		return org;
	}
	public void setOrg(SamTaxorgcode org) {
		this.org = org;
	}
	
	public boolean isOperator() {
		return whichType(maskOperator);
	}
	public boolean isDoctor() {
		return whichType(maskDoctor);
	}
	public boolean isNurse() {
		return whichType(maskNurse);
	}
	public boolean isPublicDoctor() {
		return whichType(maskPublicDoctor);
	}
	
	public Integer getIsLookAuthority() {
		return isLookAuthority;
	}

	public void setIsLookAuthority(Integer isLookAuthority) {
		this.isLookAuthority = isLookAuthority;
	}

	private boolean whichType(int flag) {
		if ( this.type != null ) {
			return ( this.type & flag ) == flag;
		}
		return false;
	}

	public Integer getIsStasticAuth() {
		return isStasticAuth;
	}

	public void setIsStasticAuth(Integer isStasticAuth) {
		this.isStasticAuth = isStasticAuth;
	}
	
}
