package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * Sickness generated by hbm2java
 */
public class Sickness implements java.io.Serializable {

	private Integer id;
	private String name;
	private String number;
	private String structNumber;
	private String parentNumber;
	private String description;
	private Integer parentId;
	private Integer level;
	private Integer isDetail;
	private String namePng;

	public Sickness() {
	}

	public Sickness(Integer parentId, Integer level, Integer isDetail,
			String namePng) {
		this.parentId = parentId;
		this.level = level;
		this.isDetail = isDetail;
		this.namePng = namePng;
	}

	public Sickness(String name, String number, String structNumber,
			String parentNumber, String description, Integer parentId,
			Integer level, Integer isDetail, String namePng) {
		this.name = name;
		this.number = number;
		this.structNumber = structNumber;
		this.parentNumber = parentNumber;
		this.description = description;
		this.parentId = parentId;
		this.level = level;
		this.isDetail = isDetail;
		this.namePng = namePng;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getStructNumber() {
		return this.structNumber;
	}

	public void setStructNumber(String structNumber) {
		this.structNumber = structNumber;
	}

	public String getParentNumber() {
		return this.parentNumber;
	}

	public void setParentNumber(String parentNumber) {
		this.parentNumber = parentNumber;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getIsDetail() {
		return this.isDetail;
	}

	public void setIsDetail(Integer isDetail) {
		this.isDetail = isDetail;
	}

	public String getNamePng() {
		return this.namePng;
	}

	public void setNamePng(String namePng) {
		this.namePng = namePng;
	}

}
