package cn.net.tongfang.framework.security.vo;

// Generated 2011-8-3 10:36:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SickInfo generated by hbm2java
 */
public class SickInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String fileNo;
	private String name;
	private String sex;
	private String address;
	private Boolean isDiabetesVisit;
	private Boolean isHypertensionVisit;
	private Boolean isFuriousInfo;
	private Date birthday;
	private String allergies;

	public SickInfo() {
	}

	public SickInfo(String id, String fileNo, String name, String sex) {
		this.id = id;
		this.fileNo = fileNo;
		this.name = name;
		this.sex = sex;
	}

	public SickInfo(String id, String fileNo, String name, String sex,
			String address, Boolean isDiabetesVisit,
			Boolean isHypertensionVisit, Boolean isFuriousInfo, Date birthday,
			String allergies) {
		this.id = id;
		this.fileNo = fileNo;
		this.name = name;
		this.sex = sex;
		this.address = address;
		this.isDiabetesVisit = isDiabetesVisit;
		this.isHypertensionVisit = isHypertensionVisit;
		this.isFuriousInfo = isFuriousInfo;
		this.birthday = birthday;
		this.allergies = allergies;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Boolean getIsDiabetesVisit() {
		return this.isDiabetesVisit;
	}

	public void setIsDiabetesVisit(Boolean isDiabetesVisit) {
		this.isDiabetesVisit = isDiabetesVisit;
	}

	public Boolean getIsHypertensionVisit() {
		return this.isHypertensionVisit;
	}

	public void setIsHypertensionVisit(Boolean isHypertensionVisit) {
		this.isHypertensionVisit = isHypertensionVisit;
	}

	public Boolean getIsFuriousInfo() {
		return this.isFuriousInfo;
	}

	public void setIsFuriousInfo(Boolean isFuriousInfo) {
		this.isFuriousInfo = isFuriousInfo;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAllergies() {
		return this.allergies;
	}

	public void setAllergies(String allergies) {
		this.allergies = allergies;
	}

}
