package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;

/**
 * Stat generated by hbm2java
 */
public class Stat implements java.io.Serializable {

	private String id;
	private String org;
	private Integer orgId;
	private String districtNumber;
	private String reporter;
	private String checker;
	private String tel;
	private String email;
	private String reportMonth;
	private Timestamp reportDate;
	private String inputPersonId;
	private Timestamp inputDate;
	private Integer basicResNum;
	private Integer basicFloatNum;
	private Integer basicBirthNum;
	private Integer basicBabyNum;
	private Integer basicPregnantNum;
	private Integer basicChildNum;
	private Integer basicOldNum;
	private Integer basicHypNum;
	private Integer basicDiabNum;
	private Integer basicFuriousNum;
	private Integer basicDoctorNum;
	private Integer basicNurseNum;
	private Integer basicPhsicianNum;
	private Integer basicBedNum;
	private Integer fileNum;
	private Integer eduPaperCategoryNum;
	private Integer eduPaperNum;
	private Integer eduAvNum;
	private Integer eduAvCategoryNum;
	private Integer eduBarNum;
	private Integer eduBarReplaceNum;
	private Integer eduActivityNum;
	private Integer eduActivityPeopleNum;
	private Integer eduTalkNum;
	private Integer eduTalkPeopleNum;
	private Integer childFileNum;
	private Integer childBabyVisitNum;
	private Integer childBabyMoonNum;
	private Integer childVisitNum;
	private Integer pregnantEarlyNum;
	private Integer pregnantEarlyVisitNum;
	private Integer pregnantMidOneVisitNum;
	private Integer pregnantMidTwoVisitNum;
	private Integer pregnantLateOneVisitNum;
	private Integer pregnantLateTwoVisitNum;
	private Integer pregnantNatalVisitNum;
	private Integer pregnantNatalExamNum;
	private Integer pregnantNatalNum;
	private Integer oldFileNum;
	private Integer oldExamNum;
	private Integer vaccBabyNum;
	private Integer vaccNeedleNum;
	private Integer vaccHepatitisNum;
	private Integer vaccAbnormalNum;
	private Integer vaccInformNum;
	private Integer vaccHepatitisResupplyNum;
	private Integer infectANum;
	private Integer infectBNum;
	private Integer infectCNum;
	private Integer infectTimelyNum;
	private Integer infectTransNum;
	private Integer infectInvestNum;
	private Integer infectVisitNum;
	private Integer hypFirstExamNum;
	private Integer hypDiscoverNum;
	private Integer hypFileNum;
	private Integer hypVisitNum;
	private Integer hypExamNum;
	private Integer hypControlNum;
	private Integer diabPeopleNum;
	private Integer diabDiscoverNum;
	private Integer diabFileNum;
	private Integer diabVisitNum;
	private Integer diabExamNum;
	private Integer diabControlNum;
	private Integer furiousFileNum;
	private Integer furiousVisitNum;
	private Integer furiousExamNum;
	private Integer furiousGoodNum;
	private Integer yearBasicResNum;
	private Integer yearBasicFloatNum;
	private Integer yearBasicBirthNum;
	private Integer yearBasicBabyNum;
	private Integer yearBasicPregnantNum;
	private Integer yearBasicChildNum;
	private Integer yearBasicOldNum;
	private Integer yearBasicHypNum;
	private Integer yearBasicDiabNum;
	private Integer yearBasicFuriousNum;
	private Integer yearBasicDoctorNum;
	private Integer yearBasicNurseNum;
	private Integer yearBasicPhsicianNum;
	private Integer yearBasicBedNum;
	private Integer yearFileNum;
	private Integer yearEduPaperCategoryNum;
	private Integer yearEduPaperNum;
	private Integer yearEduAvNum;
	private Integer yearEduAvCategoryNum;
	private Integer yearEduBarNum;
	private Integer yearEduBarReplaceNum;
	private Integer yearEduActivityNum;
	private Integer yearEduActivityPeopleNum;
	private Integer yearEduTalkNum;
	private Integer yearEduTalkPeopleNum;
	private Integer yearChildFileNum;
	private Integer yearChildBabyVisitNum;
	private Integer yearChildBabyMoonNum;
	private Integer yearChildVisitNum;
	private Integer yearPregnantEarlyNum;
	private Integer yearPregnantEarlyVisitNum;
	private Integer yearPregnantMidOneVisitNum;
	private Integer yearPregnantMidTwoVisitNum;
	private Integer yearPregnantLateOneVisitNum;
	private Integer yearPregnantLateTwoVisitNum;
	private Integer yearPregnantNatalVisitNum;
	private Integer yearPregnantNatalExamNum;
	private Integer yearPregnantNatalNum;
	private Integer yearOldFileNum;
	private Integer yearOldExamNum;
	private Integer yearVaccBabyNum;
	private Integer yearVaccNeedleNum;
	private Integer yearVaccHepatitisNum;
	private Integer yearVaccAbnormalNum;
	private Integer yearVaccInformNum;
	private Integer yearVaccHepatitisResupplyNum;
	private Integer yearInfectANum;
	private Integer yearInfectBNum;
	private Integer yearInfectCNum;
	private Integer yearInfectTimelyNum;
	private Integer yearInfectTransNum;
	private Integer yearInfectInvestNum;
	private Integer yearInfectVisitNum;
	private Integer yearHypFirstExamNum;
	private Integer yearHypDiscoverNum;
	private Integer yearHypFileNum;
	private Integer yearHypVisitNum;
	private Integer yearHypExamNum;
	private Integer yearHypControlNum;
	private Integer yearDiabPeopleNum;
	private Integer yearDiabDiscoverNum;
	private Integer yearDiabFileNum;
	private Integer yearDiabVisitNum;
	private Integer yearDiabExamNum;
	private Integer yearDiabControlNum;
	private Integer yearFuriousFileNum;
	private Integer yearFuriousVisitNum;
	private Integer yearFuriousExamNum;
	private Integer yearFuriousGoodNum;

	public Stat() {
	}

	public Stat(String org, Integer orgId, String districtNumber,
			String reporter, String checker, String tel, String email,
			String reportMonth, Timestamp reportDate, String inputPersonId,
			Timestamp inputDate, Integer basicResNum, Integer basicFloatNum,
			Integer basicBirthNum, Integer basicBabyNum,
			Integer basicPregnantNum, Integer basicChildNum,
			Integer basicOldNum, Integer basicHypNum, Integer basicDiabNum,
			Integer basicFuriousNum, Integer basicDoctorNum,
			Integer basicNurseNum, Integer basicPhsicianNum,
			Integer basicBedNum, Integer fileNum, Integer eduPaperCategoryNum,
			Integer eduPaperNum, Integer eduAvNum, Integer eduAvCategoryNum,
			Integer eduBarNum, Integer eduBarReplaceNum,
			Integer eduActivityNum, Integer eduActivityPeopleNum,
			Integer eduTalkNum, Integer eduTalkPeopleNum, Integer childFileNum,
			Integer childBabyVisitNum, Integer childBabyMoonNum,
			Integer childVisitNum, Integer pregnantEarlyNum,
			Integer pregnantEarlyVisitNum, Integer pregnantMidOneVisitNum,
			Integer pregnantMidTwoVisitNum, Integer pregnantLateOneVisitNum,
			Integer pregnantLateTwoVisitNum, Integer pregnantNatalVisitNum,
			Integer pregnantNatalExamNum, Integer pregnantNatalNum,
			Integer oldFileNum, Integer oldExamNum, Integer vaccBabyNum,
			Integer vaccNeedleNum, Integer vaccHepatitisNum,
			Integer vaccAbnormalNum, Integer vaccInformNum,
			Integer vaccHepatitisResupplyNum, Integer infectANum,
			Integer infectBNum, Integer infectCNum, Integer infectTimelyNum,
			Integer infectTransNum, Integer infectInvestNum,
			Integer infectVisitNum, Integer hypFirstExamNum,
			Integer hypDiscoverNum, Integer hypFileNum, Integer hypVisitNum,
			Integer hypExamNum, Integer hypControlNum, Integer diabPeopleNum,
			Integer diabDiscoverNum, Integer diabFileNum, Integer diabVisitNum,
			Integer diabExamNum, Integer diabControlNum,
			Integer furiousFileNum, Integer furiousVisitNum,
			Integer furiousExamNum, Integer furiousGoodNum,
			Integer yearBasicResNum, Integer yearBasicFloatNum,
			Integer yearBasicBirthNum, Integer yearBasicBabyNum,
			Integer yearBasicPregnantNum, Integer yearBasicChildNum,
			Integer yearBasicOldNum, Integer yearBasicHypNum,
			Integer yearBasicDiabNum, Integer yearBasicFuriousNum,
			Integer yearBasicDoctorNum, Integer yearBasicNurseNum,
			Integer yearBasicPhsicianNum, Integer yearBasicBedNum,
			Integer yearFileNum, Integer yearEduPaperCategoryNum,
			Integer yearEduPaperNum, Integer yearEduAvNum,
			Integer yearEduAvCategoryNum, Integer yearEduBarNum,
			Integer yearEduBarReplaceNum, Integer yearEduActivityNum,
			Integer yearEduActivityPeopleNum, Integer yearEduTalkNum,
			Integer yearEduTalkPeopleNum, Integer yearChildFileNum,
			Integer yearChildBabyVisitNum, Integer yearChildBabyMoonNum,
			Integer yearChildVisitNum, Integer yearPregnantEarlyNum,
			Integer yearPregnantEarlyVisitNum,
			Integer yearPregnantMidOneVisitNum,
			Integer yearPregnantMidTwoVisitNum,
			Integer yearPregnantLateOneVisitNum,
			Integer yearPregnantLateTwoVisitNum,
			Integer yearPregnantNatalVisitNum,
			Integer yearPregnantNatalExamNum, Integer yearPregnantNatalNum,
			Integer yearOldFileNum, Integer yearOldExamNum,
			Integer yearVaccBabyNum, Integer yearVaccNeedleNum,
			Integer yearVaccHepatitisNum, Integer yearVaccAbnormalNum,
			Integer yearVaccInformNum, Integer yearVaccHepatitisResupplyNum,
			Integer yearInfectANum, Integer yearInfectBNum,
			Integer yearInfectCNum, Integer yearInfectTimelyNum,
			Integer yearInfectTransNum, Integer yearInfectInvestNum,
			Integer yearInfectVisitNum, Integer yearHypFirstExamNum,
			Integer yearHypDiscoverNum, Integer yearHypFileNum,
			Integer yearHypVisitNum, Integer yearHypExamNum,
			Integer yearHypControlNum, Integer yearDiabPeopleNum,
			Integer yearDiabDiscoverNum, Integer yearDiabFileNum,
			Integer yearDiabVisitNum, Integer yearDiabExamNum,
			Integer yearDiabControlNum, Integer yearFuriousFileNum,
			Integer yearFuriousVisitNum, Integer yearFuriousExamNum,
			Integer yearFuriousGoodNum) {
		this.org = org;
		this.orgId = orgId;
		this.districtNumber = districtNumber;
		this.reporter = reporter;
		this.checker = checker;
		this.tel = tel;
		this.email = email;
		this.reportMonth = reportMonth;
		this.reportDate = reportDate;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
		this.basicResNum = basicResNum;
		this.basicFloatNum = basicFloatNum;
		this.basicBirthNum = basicBirthNum;
		this.basicBabyNum = basicBabyNum;
		this.basicPregnantNum = basicPregnantNum;
		this.basicChildNum = basicChildNum;
		this.basicOldNum = basicOldNum;
		this.basicHypNum = basicHypNum;
		this.basicDiabNum = basicDiabNum;
		this.basicFuriousNum = basicFuriousNum;
		this.basicDoctorNum = basicDoctorNum;
		this.basicNurseNum = basicNurseNum;
		this.basicPhsicianNum = basicPhsicianNum;
		this.basicBedNum = basicBedNum;
		this.fileNum = fileNum;
		this.eduPaperCategoryNum = eduPaperCategoryNum;
		this.eduPaperNum = eduPaperNum;
		this.eduAvNum = eduAvNum;
		this.eduAvCategoryNum = eduAvCategoryNum;
		this.eduBarNum = eduBarNum;
		this.eduBarReplaceNum = eduBarReplaceNum;
		this.eduActivityNum = eduActivityNum;
		this.eduActivityPeopleNum = eduActivityPeopleNum;
		this.eduTalkNum = eduTalkNum;
		this.eduTalkPeopleNum = eduTalkPeopleNum;
		this.childFileNum = childFileNum;
		this.childBabyVisitNum = childBabyVisitNum;
		this.childBabyMoonNum = childBabyMoonNum;
		this.childVisitNum = childVisitNum;
		this.pregnantEarlyNum = pregnantEarlyNum;
		this.pregnantEarlyVisitNum = pregnantEarlyVisitNum;
		this.pregnantMidOneVisitNum = pregnantMidOneVisitNum;
		this.pregnantMidTwoVisitNum = pregnantMidTwoVisitNum;
		this.pregnantLateOneVisitNum = pregnantLateOneVisitNum;
		this.pregnantLateTwoVisitNum = pregnantLateTwoVisitNum;
		this.pregnantNatalVisitNum = pregnantNatalVisitNum;
		this.pregnantNatalExamNum = pregnantNatalExamNum;
		this.pregnantNatalNum = pregnantNatalNum;
		this.oldFileNum = oldFileNum;
		this.oldExamNum = oldExamNum;
		this.vaccBabyNum = vaccBabyNum;
		this.vaccNeedleNum = vaccNeedleNum;
		this.vaccHepatitisNum = vaccHepatitisNum;
		this.vaccAbnormalNum = vaccAbnormalNum;
		this.vaccInformNum = vaccInformNum;
		this.vaccHepatitisResupplyNum = vaccHepatitisResupplyNum;
		this.infectANum = infectANum;
		this.infectBNum = infectBNum;
		this.infectCNum = infectCNum;
		this.infectTimelyNum = infectTimelyNum;
		this.infectTransNum = infectTransNum;
		this.infectInvestNum = infectInvestNum;
		this.infectVisitNum = infectVisitNum;
		this.hypFirstExamNum = hypFirstExamNum;
		this.hypDiscoverNum = hypDiscoverNum;
		this.hypFileNum = hypFileNum;
		this.hypVisitNum = hypVisitNum;
		this.hypExamNum = hypExamNum;
		this.hypControlNum = hypControlNum;
		this.diabPeopleNum = diabPeopleNum;
		this.diabDiscoverNum = diabDiscoverNum;
		this.diabFileNum = diabFileNum;
		this.diabVisitNum = diabVisitNum;
		this.diabExamNum = diabExamNum;
		this.diabControlNum = diabControlNum;
		this.furiousFileNum = furiousFileNum;
		this.furiousVisitNum = furiousVisitNum;
		this.furiousExamNum = furiousExamNum;
		this.furiousGoodNum = furiousGoodNum;
		this.yearBasicResNum = yearBasicResNum;
		this.yearBasicFloatNum = yearBasicFloatNum;
		this.yearBasicBirthNum = yearBasicBirthNum;
		this.yearBasicBabyNum = yearBasicBabyNum;
		this.yearBasicPregnantNum = yearBasicPregnantNum;
		this.yearBasicChildNum = yearBasicChildNum;
		this.yearBasicOldNum = yearBasicOldNum;
		this.yearBasicHypNum = yearBasicHypNum;
		this.yearBasicDiabNum = yearBasicDiabNum;
		this.yearBasicFuriousNum = yearBasicFuriousNum;
		this.yearBasicDoctorNum = yearBasicDoctorNum;
		this.yearBasicNurseNum = yearBasicNurseNum;
		this.yearBasicPhsicianNum = yearBasicPhsicianNum;
		this.yearBasicBedNum = yearBasicBedNum;
		this.yearFileNum = yearFileNum;
		this.yearEduPaperCategoryNum = yearEduPaperCategoryNum;
		this.yearEduPaperNum = yearEduPaperNum;
		this.yearEduAvNum = yearEduAvNum;
		this.yearEduAvCategoryNum = yearEduAvCategoryNum;
		this.yearEduBarNum = yearEduBarNum;
		this.yearEduBarReplaceNum = yearEduBarReplaceNum;
		this.yearEduActivityNum = yearEduActivityNum;
		this.yearEduActivityPeopleNum = yearEduActivityPeopleNum;
		this.yearEduTalkNum = yearEduTalkNum;
		this.yearEduTalkPeopleNum = yearEduTalkPeopleNum;
		this.yearChildFileNum = yearChildFileNum;
		this.yearChildBabyVisitNum = yearChildBabyVisitNum;
		this.yearChildBabyMoonNum = yearChildBabyMoonNum;
		this.yearChildVisitNum = yearChildVisitNum;
		this.yearPregnantEarlyNum = yearPregnantEarlyNum;
		this.yearPregnantEarlyVisitNum = yearPregnantEarlyVisitNum;
		this.yearPregnantMidOneVisitNum = yearPregnantMidOneVisitNum;
		this.yearPregnantMidTwoVisitNum = yearPregnantMidTwoVisitNum;
		this.yearPregnantLateOneVisitNum = yearPregnantLateOneVisitNum;
		this.yearPregnantLateTwoVisitNum = yearPregnantLateTwoVisitNum;
		this.yearPregnantNatalVisitNum = yearPregnantNatalVisitNum;
		this.yearPregnantNatalExamNum = yearPregnantNatalExamNum;
		this.yearPregnantNatalNum = yearPregnantNatalNum;
		this.yearOldFileNum = yearOldFileNum;
		this.yearOldExamNum = yearOldExamNum;
		this.yearVaccBabyNum = yearVaccBabyNum;
		this.yearVaccNeedleNum = yearVaccNeedleNum;
		this.yearVaccHepatitisNum = yearVaccHepatitisNum;
		this.yearVaccAbnormalNum = yearVaccAbnormalNum;
		this.yearVaccInformNum = yearVaccInformNum;
		this.yearVaccHepatitisResupplyNum = yearVaccHepatitisResupplyNum;
		this.yearInfectANum = yearInfectANum;
		this.yearInfectBNum = yearInfectBNum;
		this.yearInfectCNum = yearInfectCNum;
		this.yearInfectTimelyNum = yearInfectTimelyNum;
		this.yearInfectTransNum = yearInfectTransNum;
		this.yearInfectInvestNum = yearInfectInvestNum;
		this.yearInfectVisitNum = yearInfectVisitNum;
		this.yearHypFirstExamNum = yearHypFirstExamNum;
		this.yearHypDiscoverNum = yearHypDiscoverNum;
		this.yearHypFileNum = yearHypFileNum;
		this.yearHypVisitNum = yearHypVisitNum;
		this.yearHypExamNum = yearHypExamNum;
		this.yearHypControlNum = yearHypControlNum;
		this.yearDiabPeopleNum = yearDiabPeopleNum;
		this.yearDiabDiscoverNum = yearDiabDiscoverNum;
		this.yearDiabFileNum = yearDiabFileNum;
		this.yearDiabVisitNum = yearDiabVisitNum;
		this.yearDiabExamNum = yearDiabExamNum;
		this.yearDiabControlNum = yearDiabControlNum;
		this.yearFuriousFileNum = yearFuriousFileNum;
		this.yearFuriousVisitNum = yearFuriousVisitNum;
		this.yearFuriousExamNum = yearFuriousExamNum;
		this.yearFuriousGoodNum = yearFuriousGoodNum;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	public Integer getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	public String getDistrictNumber() {
		return this.districtNumber;
	}

	public void setDistrictNumber(String districtNumber) {
		this.districtNumber = districtNumber;
	}

	public String getReporter() {
		return this.reporter;
	}

	public void setReporter(String reporter) {
		this.reporter = reporter;
	}

	public String getChecker() {
		return this.checker;
	}

	public void setChecker(String checker) {
		this.checker = checker;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getReportMonth() {
		return this.reportMonth;
	}

	public void setReportMonth(String reportMonth) {
		this.reportMonth = reportMonth;
	}

	public Timestamp getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Timestamp reportDate) {
		this.reportDate = reportDate;
	}

	public String getInputPersonId() {
		return this.inputPersonId;
	}

	public void setInputPersonId(String inputPersonId) {
		this.inputPersonId = inputPersonId;
	}

	public Timestamp getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
	}

	public Integer getBasicResNum() {
		return this.basicResNum;
	}

	public void setBasicResNum(Integer basicResNum) {
		this.basicResNum = basicResNum;
	}

	public Integer getBasicFloatNum() {
		return this.basicFloatNum;
	}

	public void setBasicFloatNum(Integer basicFloatNum) {
		this.basicFloatNum = basicFloatNum;
	}

	public Integer getBasicBirthNum() {
		return this.basicBirthNum;
	}

	public void setBasicBirthNum(Integer basicBirthNum) {
		this.basicBirthNum = basicBirthNum;
	}

	public Integer getBasicBabyNum() {
		return this.basicBabyNum;
	}

	public void setBasicBabyNum(Integer basicBabyNum) {
		this.basicBabyNum = basicBabyNum;
	}

	public Integer getBasicPregnantNum() {
		return this.basicPregnantNum;
	}

	public void setBasicPregnantNum(Integer basicPregnantNum) {
		this.basicPregnantNum = basicPregnantNum;
	}

	public Integer getBasicChildNum() {
		return this.basicChildNum;
	}

	public void setBasicChildNum(Integer basicChildNum) {
		this.basicChildNum = basicChildNum;
	}

	public Integer getBasicOldNum() {
		return this.basicOldNum;
	}

	public void setBasicOldNum(Integer basicOldNum) {
		this.basicOldNum = basicOldNum;
	}

	public Integer getBasicHypNum() {
		return this.basicHypNum;
	}

	public void setBasicHypNum(Integer basicHypNum) {
		this.basicHypNum = basicHypNum;
	}

	public Integer getBasicDiabNum() {
		return this.basicDiabNum;
	}

	public void setBasicDiabNum(Integer basicDiabNum) {
		this.basicDiabNum = basicDiabNum;
	}

	public Integer getBasicFuriousNum() {
		return this.basicFuriousNum;
	}

	public void setBasicFuriousNum(Integer basicFuriousNum) {
		this.basicFuriousNum = basicFuriousNum;
	}

	public Integer getBasicDoctorNum() {
		return this.basicDoctorNum;
	}

	public void setBasicDoctorNum(Integer basicDoctorNum) {
		this.basicDoctorNum = basicDoctorNum;
	}

	public Integer getBasicNurseNum() {
		return this.basicNurseNum;
	}

	public void setBasicNurseNum(Integer basicNurseNum) {
		this.basicNurseNum = basicNurseNum;
	}

	public Integer getBasicPhsicianNum() {
		return this.basicPhsicianNum;
	}

	public void setBasicPhsicianNum(Integer basicPhsicianNum) {
		this.basicPhsicianNum = basicPhsicianNum;
	}

	public Integer getBasicBedNum() {
		return this.basicBedNum;
	}

	public void setBasicBedNum(Integer basicBedNum) {
		this.basicBedNum = basicBedNum;
	}

	public Integer getFileNum() {
		return this.fileNum;
	}

	public void setFileNum(Integer fileNum) {
		this.fileNum = fileNum;
	}

	public Integer getEduPaperCategoryNum() {
		return this.eduPaperCategoryNum;
	}

	public void setEduPaperCategoryNum(Integer eduPaperCategoryNum) {
		this.eduPaperCategoryNum = eduPaperCategoryNum;
	}

	public Integer getEduPaperNum() {
		return this.eduPaperNum;
	}

	public void setEduPaperNum(Integer eduPaperNum) {
		this.eduPaperNum = eduPaperNum;
	}

	public Integer getEduAvNum() {
		return this.eduAvNum;
	}

	public void setEduAvNum(Integer eduAvNum) {
		this.eduAvNum = eduAvNum;
	}

	public Integer getEduAvCategoryNum() {
		return this.eduAvCategoryNum;
	}

	public void setEduAvCategoryNum(Integer eduAvCategoryNum) {
		this.eduAvCategoryNum = eduAvCategoryNum;
	}

	public Integer getEduBarNum() {
		return this.eduBarNum;
	}

	public void setEduBarNum(Integer eduBarNum) {
		this.eduBarNum = eduBarNum;
	}

	public Integer getEduBarReplaceNum() {
		return this.eduBarReplaceNum;
	}

	public void setEduBarReplaceNum(Integer eduBarReplaceNum) {
		this.eduBarReplaceNum = eduBarReplaceNum;
	}

	public Integer getEduActivityNum() {
		return this.eduActivityNum;
	}

	public void setEduActivityNum(Integer eduActivityNum) {
		this.eduActivityNum = eduActivityNum;
	}

	public Integer getEduActivityPeopleNum() {
		return this.eduActivityPeopleNum;
	}

	public void setEduActivityPeopleNum(Integer eduActivityPeopleNum) {
		this.eduActivityPeopleNum = eduActivityPeopleNum;
	}

	public Integer getEduTalkNum() {
		return this.eduTalkNum;
	}

	public void setEduTalkNum(Integer eduTalkNum) {
		this.eduTalkNum = eduTalkNum;
	}

	public Integer getEduTalkPeopleNum() {
		return this.eduTalkPeopleNum;
	}

	public void setEduTalkPeopleNum(Integer eduTalkPeopleNum) {
		this.eduTalkPeopleNum = eduTalkPeopleNum;
	}

	public Integer getChildFileNum() {
		return this.childFileNum;
	}

	public void setChildFileNum(Integer childFileNum) {
		this.childFileNum = childFileNum;
	}

	public Integer getChildBabyVisitNum() {
		return this.childBabyVisitNum;
	}

	public void setChildBabyVisitNum(Integer childBabyVisitNum) {
		this.childBabyVisitNum = childBabyVisitNum;
	}

	public Integer getChildBabyMoonNum() {
		return this.childBabyMoonNum;
	}

	public void setChildBabyMoonNum(Integer childBabyMoonNum) {
		this.childBabyMoonNum = childBabyMoonNum;
	}

	public Integer getChildVisitNum() {
		return this.childVisitNum;
	}

	public void setChildVisitNum(Integer childVisitNum) {
		this.childVisitNum = childVisitNum;
	}

	public Integer getPregnantEarlyNum() {
		return this.pregnantEarlyNum;
	}

	public void setPregnantEarlyNum(Integer pregnantEarlyNum) {
		this.pregnantEarlyNum = pregnantEarlyNum;
	}

	public Integer getPregnantEarlyVisitNum() {
		return this.pregnantEarlyVisitNum;
	}

	public void setPregnantEarlyVisitNum(Integer pregnantEarlyVisitNum) {
		this.pregnantEarlyVisitNum = pregnantEarlyVisitNum;
	}

	public Integer getPregnantMidOneVisitNum() {
		return this.pregnantMidOneVisitNum;
	}

	public void setPregnantMidOneVisitNum(Integer pregnantMidOneVisitNum) {
		this.pregnantMidOneVisitNum = pregnantMidOneVisitNum;
	}

	public Integer getPregnantMidTwoVisitNum() {
		return this.pregnantMidTwoVisitNum;
	}

	public void setPregnantMidTwoVisitNum(Integer pregnantMidTwoVisitNum) {
		this.pregnantMidTwoVisitNum = pregnantMidTwoVisitNum;
	}

	public Integer getPregnantLateOneVisitNum() {
		return this.pregnantLateOneVisitNum;
	}

	public void setPregnantLateOneVisitNum(Integer pregnantLateOneVisitNum) {
		this.pregnantLateOneVisitNum = pregnantLateOneVisitNum;
	}

	public Integer getPregnantLateTwoVisitNum() {
		return this.pregnantLateTwoVisitNum;
	}

	public void setPregnantLateTwoVisitNum(Integer pregnantLateTwoVisitNum) {
		this.pregnantLateTwoVisitNum = pregnantLateTwoVisitNum;
	}

	public Integer getPregnantNatalVisitNum() {
		return this.pregnantNatalVisitNum;
	}

	public void setPregnantNatalVisitNum(Integer pregnantNatalVisitNum) {
		this.pregnantNatalVisitNum = pregnantNatalVisitNum;
	}

	public Integer getPregnantNatalExamNum() {
		return this.pregnantNatalExamNum;
	}

	public void setPregnantNatalExamNum(Integer pregnantNatalExamNum) {
		this.pregnantNatalExamNum = pregnantNatalExamNum;
	}

	public Integer getPregnantNatalNum() {
		return this.pregnantNatalNum;
	}

	public void setPregnantNatalNum(Integer pregnantNatalNum) {
		this.pregnantNatalNum = pregnantNatalNum;
	}

	public Integer getOldFileNum() {
		return this.oldFileNum;
	}

	public void setOldFileNum(Integer oldFileNum) {
		this.oldFileNum = oldFileNum;
	}

	public Integer getOldExamNum() {
		return this.oldExamNum;
	}

	public void setOldExamNum(Integer oldExamNum) {
		this.oldExamNum = oldExamNum;
	}

	public Integer getVaccBabyNum() {
		return this.vaccBabyNum;
	}

	public void setVaccBabyNum(Integer vaccBabyNum) {
		this.vaccBabyNum = vaccBabyNum;
	}

	public Integer getVaccNeedleNum() {
		return this.vaccNeedleNum;
	}

	public void setVaccNeedleNum(Integer vaccNeedleNum) {
		this.vaccNeedleNum = vaccNeedleNum;
	}

	public Integer getVaccHepatitisNum() {
		return this.vaccHepatitisNum;
	}

	public void setVaccHepatitisNum(Integer vaccHepatitisNum) {
		this.vaccHepatitisNum = vaccHepatitisNum;
	}

	public Integer getVaccAbnormalNum() {
		return this.vaccAbnormalNum;
	}

	public void setVaccAbnormalNum(Integer vaccAbnormalNum) {
		this.vaccAbnormalNum = vaccAbnormalNum;
	}

	public Integer getVaccInformNum() {
		return this.vaccInformNum;
	}

	public void setVaccInformNum(Integer vaccInformNum) {
		this.vaccInformNum = vaccInformNum;
	}

	public Integer getVaccHepatitisResupplyNum() {
		return this.vaccHepatitisResupplyNum;
	}

	public void setVaccHepatitisResupplyNum(Integer vaccHepatitisResupplyNum) {
		this.vaccHepatitisResupplyNum = vaccHepatitisResupplyNum;
	}

	public Integer getInfectANum() {
		return this.infectANum;
	}

	public void setInfectANum(Integer infectANum) {
		this.infectANum = infectANum;
	}

	public Integer getInfectBNum() {
		return this.infectBNum;
	}

	public void setInfectBNum(Integer infectBNum) {
		this.infectBNum = infectBNum;
	}

	public Integer getInfectCNum() {
		return this.infectCNum;
	}

	public void setInfectCNum(Integer infectCNum) {
		this.infectCNum = infectCNum;
	}

	public Integer getInfectTimelyNum() {
		return this.infectTimelyNum;
	}

	public void setInfectTimelyNum(Integer infectTimelyNum) {
		this.infectTimelyNum = infectTimelyNum;
	}

	public Integer getInfectTransNum() {
		return this.infectTransNum;
	}

	public void setInfectTransNum(Integer infectTransNum) {
		this.infectTransNum = infectTransNum;
	}

	public Integer getInfectInvestNum() {
		return this.infectInvestNum;
	}

	public void setInfectInvestNum(Integer infectInvestNum) {
		this.infectInvestNum = infectInvestNum;
	}

	public Integer getInfectVisitNum() {
		return this.infectVisitNum;
	}

	public void setInfectVisitNum(Integer infectVisitNum) {
		this.infectVisitNum = infectVisitNum;
	}

	public Integer getHypFirstExamNum() {
		return this.hypFirstExamNum;
	}

	public void setHypFirstExamNum(Integer hypFirstExamNum) {
		this.hypFirstExamNum = hypFirstExamNum;
	}

	public Integer getHypDiscoverNum() {
		return this.hypDiscoverNum;
	}

	public void setHypDiscoverNum(Integer hypDiscoverNum) {
		this.hypDiscoverNum = hypDiscoverNum;
	}

	public Integer getHypFileNum() {
		return this.hypFileNum;
	}

	public void setHypFileNum(Integer hypFileNum) {
		this.hypFileNum = hypFileNum;
	}

	public Integer getHypVisitNum() {
		return this.hypVisitNum;
	}

	public void setHypVisitNum(Integer hypVisitNum) {
		this.hypVisitNum = hypVisitNum;
	}

	public Integer getHypExamNum() {
		return this.hypExamNum;
	}

	public void setHypExamNum(Integer hypExamNum) {
		this.hypExamNum = hypExamNum;
	}

	public Integer getHypControlNum() {
		return this.hypControlNum;
	}

	public void setHypControlNum(Integer hypControlNum) {
		this.hypControlNum = hypControlNum;
	}

	public Integer getDiabPeopleNum() {
		return this.diabPeopleNum;
	}

	public void setDiabPeopleNum(Integer diabPeopleNum) {
		this.diabPeopleNum = diabPeopleNum;
	}

	public Integer getDiabDiscoverNum() {
		return this.diabDiscoverNum;
	}

	public void setDiabDiscoverNum(Integer diabDiscoverNum) {
		this.diabDiscoverNum = diabDiscoverNum;
	}

	public Integer getDiabFileNum() {
		return this.diabFileNum;
	}

	public void setDiabFileNum(Integer diabFileNum) {
		this.diabFileNum = diabFileNum;
	}

	public Integer getDiabVisitNum() {
		return this.diabVisitNum;
	}

	public void setDiabVisitNum(Integer diabVisitNum) {
		this.diabVisitNum = diabVisitNum;
	}

	public Integer getDiabExamNum() {
		return this.diabExamNum;
	}

	public void setDiabExamNum(Integer diabExamNum) {
		this.diabExamNum = diabExamNum;
	}

	public Integer getDiabControlNum() {
		return this.diabControlNum;
	}

	public void setDiabControlNum(Integer diabControlNum) {
		this.diabControlNum = diabControlNum;
	}

	public Integer getFuriousFileNum() {
		return this.furiousFileNum;
	}

	public void setFuriousFileNum(Integer furiousFileNum) {
		this.furiousFileNum = furiousFileNum;
	}

	public Integer getFuriousVisitNum() {
		return this.furiousVisitNum;
	}

	public void setFuriousVisitNum(Integer furiousVisitNum) {
		this.furiousVisitNum = furiousVisitNum;
	}

	public Integer getFuriousExamNum() {
		return this.furiousExamNum;
	}

	public void setFuriousExamNum(Integer furiousExamNum) {
		this.furiousExamNum = furiousExamNum;
	}

	public Integer getFuriousGoodNum() {
		return this.furiousGoodNum;
	}

	public void setFuriousGoodNum(Integer furiousGoodNum) {
		this.furiousGoodNum = furiousGoodNum;
	}

	public Integer getYearBasicResNum() {
		return this.yearBasicResNum;
	}

	public void setYearBasicResNum(Integer yearBasicResNum) {
		this.yearBasicResNum = yearBasicResNum;
	}

	public Integer getYearBasicFloatNum() {
		return this.yearBasicFloatNum;
	}

	public void setYearBasicFloatNum(Integer yearBasicFloatNum) {
		this.yearBasicFloatNum = yearBasicFloatNum;
	}

	public Integer getYearBasicBirthNum() {
		return this.yearBasicBirthNum;
	}

	public void setYearBasicBirthNum(Integer yearBasicBirthNum) {
		this.yearBasicBirthNum = yearBasicBirthNum;
	}

	public Integer getYearBasicBabyNum() {
		return this.yearBasicBabyNum;
	}

	public void setYearBasicBabyNum(Integer yearBasicBabyNum) {
		this.yearBasicBabyNum = yearBasicBabyNum;
	}

	public Integer getYearBasicPregnantNum() {
		return this.yearBasicPregnantNum;
	}

	public void setYearBasicPregnantNum(Integer yearBasicPregnantNum) {
		this.yearBasicPregnantNum = yearBasicPregnantNum;
	}

	public Integer getYearBasicChildNum() {
		return this.yearBasicChildNum;
	}

	public void setYearBasicChildNum(Integer yearBasicChildNum) {
		this.yearBasicChildNum = yearBasicChildNum;
	}

	public Integer getYearBasicOldNum() {
		return this.yearBasicOldNum;
	}

	public void setYearBasicOldNum(Integer yearBasicOldNum) {
		this.yearBasicOldNum = yearBasicOldNum;
	}

	public Integer getYearBasicHypNum() {
		return this.yearBasicHypNum;
	}

	public void setYearBasicHypNum(Integer yearBasicHypNum) {
		this.yearBasicHypNum = yearBasicHypNum;
	}

	public Integer getYearBasicDiabNum() {
		return this.yearBasicDiabNum;
	}

	public void setYearBasicDiabNum(Integer yearBasicDiabNum) {
		this.yearBasicDiabNum = yearBasicDiabNum;
	}

	public Integer getYearBasicFuriousNum() {
		return this.yearBasicFuriousNum;
	}

	public void setYearBasicFuriousNum(Integer yearBasicFuriousNum) {
		this.yearBasicFuriousNum = yearBasicFuriousNum;
	}

	public Integer getYearBasicDoctorNum() {
		return this.yearBasicDoctorNum;
	}

	public void setYearBasicDoctorNum(Integer yearBasicDoctorNum) {
		this.yearBasicDoctorNum = yearBasicDoctorNum;
	}

	public Integer getYearBasicNurseNum() {
		return this.yearBasicNurseNum;
	}

	public void setYearBasicNurseNum(Integer yearBasicNurseNum) {
		this.yearBasicNurseNum = yearBasicNurseNum;
	}

	public Integer getYearBasicPhsicianNum() {
		return this.yearBasicPhsicianNum;
	}

	public void setYearBasicPhsicianNum(Integer yearBasicPhsicianNum) {
		this.yearBasicPhsicianNum = yearBasicPhsicianNum;
	}

	public Integer getYearBasicBedNum() {
		return this.yearBasicBedNum;
	}

	public void setYearBasicBedNum(Integer yearBasicBedNum) {
		this.yearBasicBedNum = yearBasicBedNum;
	}

	public Integer getYearFileNum() {
		return this.yearFileNum;
	}

	public void setYearFileNum(Integer yearFileNum) {
		this.yearFileNum = yearFileNum;
	}

	public Integer getYearEduPaperCategoryNum() {
		return this.yearEduPaperCategoryNum;
	}

	public void setYearEduPaperCategoryNum(Integer yearEduPaperCategoryNum) {
		this.yearEduPaperCategoryNum = yearEduPaperCategoryNum;
	}

	public Integer getYearEduPaperNum() {
		return this.yearEduPaperNum;
	}

	public void setYearEduPaperNum(Integer yearEduPaperNum) {
		this.yearEduPaperNum = yearEduPaperNum;
	}

	public Integer getYearEduAvNum() {
		return this.yearEduAvNum;
	}

	public void setYearEduAvNum(Integer yearEduAvNum) {
		this.yearEduAvNum = yearEduAvNum;
	}

	public Integer getYearEduAvCategoryNum() {
		return this.yearEduAvCategoryNum;
	}

	public void setYearEduAvCategoryNum(Integer yearEduAvCategoryNum) {
		this.yearEduAvCategoryNum = yearEduAvCategoryNum;
	}

	public Integer getYearEduBarNum() {
		return this.yearEduBarNum;
	}

	public void setYearEduBarNum(Integer yearEduBarNum) {
		this.yearEduBarNum = yearEduBarNum;
	}

	public Integer getYearEduBarReplaceNum() {
		return this.yearEduBarReplaceNum;
	}

	public void setYearEduBarReplaceNum(Integer yearEduBarReplaceNum) {
		this.yearEduBarReplaceNum = yearEduBarReplaceNum;
	}

	public Integer getYearEduActivityNum() {
		return this.yearEduActivityNum;
	}

	public void setYearEduActivityNum(Integer yearEduActivityNum) {
		this.yearEduActivityNum = yearEduActivityNum;
	}

	public Integer getYearEduActivityPeopleNum() {
		return this.yearEduActivityPeopleNum;
	}

	public void setYearEduActivityPeopleNum(Integer yearEduActivityPeopleNum) {
		this.yearEduActivityPeopleNum = yearEduActivityPeopleNum;
	}

	public Integer getYearEduTalkNum() {
		return this.yearEduTalkNum;
	}

	public void setYearEduTalkNum(Integer yearEduTalkNum) {
		this.yearEduTalkNum = yearEduTalkNum;
	}

	public Integer getYearEduTalkPeopleNum() {
		return this.yearEduTalkPeopleNum;
	}

	public void setYearEduTalkPeopleNum(Integer yearEduTalkPeopleNum) {
		this.yearEduTalkPeopleNum = yearEduTalkPeopleNum;
	}

	public Integer getYearChildFileNum() {
		return this.yearChildFileNum;
	}

	public void setYearChildFileNum(Integer yearChildFileNum) {
		this.yearChildFileNum = yearChildFileNum;
	}

	public Integer getYearChildBabyVisitNum() {
		return this.yearChildBabyVisitNum;
	}

	public void setYearChildBabyVisitNum(Integer yearChildBabyVisitNum) {
		this.yearChildBabyVisitNum = yearChildBabyVisitNum;
	}

	public Integer getYearChildBabyMoonNum() {
		return this.yearChildBabyMoonNum;
	}

	public void setYearChildBabyMoonNum(Integer yearChildBabyMoonNum) {
		this.yearChildBabyMoonNum = yearChildBabyMoonNum;
	}

	public Integer getYearChildVisitNum() {
		return this.yearChildVisitNum;
	}

	public void setYearChildVisitNum(Integer yearChildVisitNum) {
		this.yearChildVisitNum = yearChildVisitNum;
	}

	public Integer getYearPregnantEarlyNum() {
		return this.yearPregnantEarlyNum;
	}

	public void setYearPregnantEarlyNum(Integer yearPregnantEarlyNum) {
		this.yearPregnantEarlyNum = yearPregnantEarlyNum;
	}

	public Integer getYearPregnantEarlyVisitNum() {
		return this.yearPregnantEarlyVisitNum;
	}

	public void setYearPregnantEarlyVisitNum(Integer yearPregnantEarlyVisitNum) {
		this.yearPregnantEarlyVisitNum = yearPregnantEarlyVisitNum;
	}

	public Integer getYearPregnantMidOneVisitNum() {
		return this.yearPregnantMidOneVisitNum;
	}

	public void setYearPregnantMidOneVisitNum(Integer yearPregnantMidOneVisitNum) {
		this.yearPregnantMidOneVisitNum = yearPregnantMidOneVisitNum;
	}

	public Integer getYearPregnantMidTwoVisitNum() {
		return this.yearPregnantMidTwoVisitNum;
	}

	public void setYearPregnantMidTwoVisitNum(Integer yearPregnantMidTwoVisitNum) {
		this.yearPregnantMidTwoVisitNum = yearPregnantMidTwoVisitNum;
	}

	public Integer getYearPregnantLateOneVisitNum() {
		return this.yearPregnantLateOneVisitNum;
	}

	public void setYearPregnantLateOneVisitNum(
			Integer yearPregnantLateOneVisitNum) {
		this.yearPregnantLateOneVisitNum = yearPregnantLateOneVisitNum;
	}

	public Integer getYearPregnantLateTwoVisitNum() {
		return this.yearPregnantLateTwoVisitNum;
	}

	public void setYearPregnantLateTwoVisitNum(
			Integer yearPregnantLateTwoVisitNum) {
		this.yearPregnantLateTwoVisitNum = yearPregnantLateTwoVisitNum;
	}

	public Integer getYearPregnantNatalVisitNum() {
		return this.yearPregnantNatalVisitNum;
	}

	public void setYearPregnantNatalVisitNum(Integer yearPregnantNatalVisitNum) {
		this.yearPregnantNatalVisitNum = yearPregnantNatalVisitNum;
	}

	public Integer getYearPregnantNatalExamNum() {
		return this.yearPregnantNatalExamNum;
	}

	public void setYearPregnantNatalExamNum(Integer yearPregnantNatalExamNum) {
		this.yearPregnantNatalExamNum = yearPregnantNatalExamNum;
	}

	public Integer getYearPregnantNatalNum() {
		return this.yearPregnantNatalNum;
	}

	public void setYearPregnantNatalNum(Integer yearPregnantNatalNum) {
		this.yearPregnantNatalNum = yearPregnantNatalNum;
	}

	public Integer getYearOldFileNum() {
		return this.yearOldFileNum;
	}

	public void setYearOldFileNum(Integer yearOldFileNum) {
		this.yearOldFileNum = yearOldFileNum;
	}

	public Integer getYearOldExamNum() {
		return this.yearOldExamNum;
	}

	public void setYearOldExamNum(Integer yearOldExamNum) {
		this.yearOldExamNum = yearOldExamNum;
	}

	public Integer getYearVaccBabyNum() {
		return this.yearVaccBabyNum;
	}

	public void setYearVaccBabyNum(Integer yearVaccBabyNum) {
		this.yearVaccBabyNum = yearVaccBabyNum;
	}

	public Integer getYearVaccNeedleNum() {
		return this.yearVaccNeedleNum;
	}

	public void setYearVaccNeedleNum(Integer yearVaccNeedleNum) {
		this.yearVaccNeedleNum = yearVaccNeedleNum;
	}

	public Integer getYearVaccHepatitisNum() {
		return this.yearVaccHepatitisNum;
	}

	public void setYearVaccHepatitisNum(Integer yearVaccHepatitisNum) {
		this.yearVaccHepatitisNum = yearVaccHepatitisNum;
	}

	public Integer getYearVaccAbnormalNum() {
		return this.yearVaccAbnormalNum;
	}

	public void setYearVaccAbnormalNum(Integer yearVaccAbnormalNum) {
		this.yearVaccAbnormalNum = yearVaccAbnormalNum;
	}

	public Integer getYearVaccInformNum() {
		return this.yearVaccInformNum;
	}

	public void setYearVaccInformNum(Integer yearVaccInformNum) {
		this.yearVaccInformNum = yearVaccInformNum;
	}

	public Integer getYearVaccHepatitisResupplyNum() {
		return this.yearVaccHepatitisResupplyNum;
	}

	public void setYearVaccHepatitisResupplyNum(
			Integer yearVaccHepatitisResupplyNum) {
		this.yearVaccHepatitisResupplyNum = yearVaccHepatitisResupplyNum;
	}

	public Integer getYearInfectANum() {
		return this.yearInfectANum;
	}

	public void setYearInfectANum(Integer yearInfectANum) {
		this.yearInfectANum = yearInfectANum;
	}

	public Integer getYearInfectBNum() {
		return this.yearInfectBNum;
	}

	public void setYearInfectBNum(Integer yearInfectBNum) {
		this.yearInfectBNum = yearInfectBNum;
	}

	public Integer getYearInfectCNum() {
		return this.yearInfectCNum;
	}

	public void setYearInfectCNum(Integer yearInfectCNum) {
		this.yearInfectCNum = yearInfectCNum;
	}

	public Integer getYearInfectTimelyNum() {
		return this.yearInfectTimelyNum;
	}

	public void setYearInfectTimelyNum(Integer yearInfectTimelyNum) {
		this.yearInfectTimelyNum = yearInfectTimelyNum;
	}

	public Integer getYearInfectTransNum() {
		return this.yearInfectTransNum;
	}

	public void setYearInfectTransNum(Integer yearInfectTransNum) {
		this.yearInfectTransNum = yearInfectTransNum;
	}

	public Integer getYearInfectInvestNum() {
		return this.yearInfectInvestNum;
	}

	public void setYearInfectInvestNum(Integer yearInfectInvestNum) {
		this.yearInfectInvestNum = yearInfectInvestNum;
	}

	public Integer getYearInfectVisitNum() {
		return this.yearInfectVisitNum;
	}

	public void setYearInfectVisitNum(Integer yearInfectVisitNum) {
		this.yearInfectVisitNum = yearInfectVisitNum;
	}

	public Integer getYearHypFirstExamNum() {
		return this.yearHypFirstExamNum;
	}

	public void setYearHypFirstExamNum(Integer yearHypFirstExamNum) {
		this.yearHypFirstExamNum = yearHypFirstExamNum;
	}

	public Integer getYearHypDiscoverNum() {
		return this.yearHypDiscoverNum;
	}

	public void setYearHypDiscoverNum(Integer yearHypDiscoverNum) {
		this.yearHypDiscoverNum = yearHypDiscoverNum;
	}

	public Integer getYearHypFileNum() {
		return this.yearHypFileNum;
	}

	public void setYearHypFileNum(Integer yearHypFileNum) {
		this.yearHypFileNum = yearHypFileNum;
	}

	public Integer getYearHypVisitNum() {
		return this.yearHypVisitNum;
	}

	public void setYearHypVisitNum(Integer yearHypVisitNum) {
		this.yearHypVisitNum = yearHypVisitNum;
	}

	public Integer getYearHypExamNum() {
		return this.yearHypExamNum;
	}

	public void setYearHypExamNum(Integer yearHypExamNum) {
		this.yearHypExamNum = yearHypExamNum;
	}

	public Integer getYearHypControlNum() {
		return this.yearHypControlNum;
	}

	public void setYearHypControlNum(Integer yearHypControlNum) {
		this.yearHypControlNum = yearHypControlNum;
	}

	public Integer getYearDiabPeopleNum() {
		return this.yearDiabPeopleNum;
	}

	public void setYearDiabPeopleNum(Integer yearDiabPeopleNum) {
		this.yearDiabPeopleNum = yearDiabPeopleNum;
	}

	public Integer getYearDiabDiscoverNum() {
		return this.yearDiabDiscoverNum;
	}

	public void setYearDiabDiscoverNum(Integer yearDiabDiscoverNum) {
		this.yearDiabDiscoverNum = yearDiabDiscoverNum;
	}

	public Integer getYearDiabFileNum() {
		return this.yearDiabFileNum;
	}

	public void setYearDiabFileNum(Integer yearDiabFileNum) {
		this.yearDiabFileNum = yearDiabFileNum;
	}

	public Integer getYearDiabVisitNum() {
		return this.yearDiabVisitNum;
	}

	public void setYearDiabVisitNum(Integer yearDiabVisitNum) {
		this.yearDiabVisitNum = yearDiabVisitNum;
	}

	public Integer getYearDiabExamNum() {
		return this.yearDiabExamNum;
	}

	public void setYearDiabExamNum(Integer yearDiabExamNum) {
		this.yearDiabExamNum = yearDiabExamNum;
	}

	public Integer getYearDiabControlNum() {
		return this.yearDiabControlNum;
	}

	public void setYearDiabControlNum(Integer yearDiabControlNum) {
		this.yearDiabControlNum = yearDiabControlNum;
	}

	public Integer getYearFuriousFileNum() {
		return this.yearFuriousFileNum;
	}

	public void setYearFuriousFileNum(Integer yearFuriousFileNum) {
		this.yearFuriousFileNum = yearFuriousFileNum;
	}

	public Integer getYearFuriousVisitNum() {
		return this.yearFuriousVisitNum;
	}

	public void setYearFuriousVisitNum(Integer yearFuriousVisitNum) {
		this.yearFuriousVisitNum = yearFuriousVisitNum;
	}

	public Integer getYearFuriousExamNum() {
		return this.yearFuriousExamNum;
	}

	public void setYearFuriousExamNum(Integer yearFuriousExamNum) {
		this.yearFuriousExamNum = yearFuriousExamNum;
	}

	public Integer getYearFuriousGoodNum() {
		return this.yearFuriousGoodNum;
	}

	public void setYearFuriousGoodNum(Integer yearFuriousGoodNum) {
		this.yearFuriousGoodNum = yearFuriousGoodNum;
	}

}
