package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * SystemParameter generated by hbm2java
 */
public class SystemParameter implements java.io.Serializable {

	private String id;
	private String value;
	private String descr;

	public SystemParameter() {
	}

	public SystemParameter(String id) {
		this.id = id;
	}

	public SystemParameter(String id, String value, String descr) {
		this.id = id;
		this.value = value;
		this.descr = descr;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

}
