package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * TraumaHistory generated by hbm2java
 */
public class TraumaHistory implements java.io.Serializable {

	private String id;
	private String personalInfoId;
	private String traumaName;
	private String traumaDate;

	public TraumaHistory() {
	}

	public TraumaHistory(String personalInfoId, String traumaName,
			String traumaDate) {
		this.personalInfoId = personalInfoId;
		this.traumaName = traumaName;
		this.traumaDate = traumaDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPersonalInfoId() {
		return this.personalInfoId;
	}

	public void setPersonalInfoId(String personalInfoId) {
		this.personalInfoId = personalInfoId;
	}

	public String getTraumaName() {
		return this.traumaName;
	}

	public void setTraumaName(String traumaName) {
		this.traumaName = traumaName;
	}

	public String getTraumaDate() {
		return this.traumaDate;
	}

	public void setTraumaDate(String traumaDate) {
		this.traumaDate = traumaDate;
	}

}
