package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * UpgrowthStandard generated by hbm2java
 */
public class UpgrowthStandard implements java.io.Serializable {

	private Integer id;
	private String number;
	private Integer upgrowthStandardTypeId;
	private String name;
	private Integer forbidden;

	public UpgrowthStandard() {
	}

	public UpgrowthStandard(Integer id, String number,
			Integer upgrowthStandardTypeId, String name, Integer forbidden) {
		this.id = id;
		this.number = number;
		this.upgrowthStandardTypeId = upgrowthStandardTypeId;
		this.name = name;
		this.forbidden = forbidden;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Integer getUpgrowthStandardTypeId() {
		return this.upgrowthStandardTypeId;
	}

	public void setUpgrowthStandardTypeId(Integer upgrowthStandardTypeId) {
		this.upgrowthStandardTypeId = upgrowthStandardTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getForbidden() {
		return this.forbidden;
	}

	public void setForbidden(Integer forbidden) {
		this.forbidden = forbidden;
	}

}
