package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * UpgrowthStandardSub generated by hbm2java
 */
public class UpgrowthStandardSub implements java.io.Serializable {

	private Integer id;
	private Integer upgrowthStandardId;
	private Integer yearOld;
	private Integer monthOld;
	private BigDecimal consultHeight;
	private BigDecimal boyValueLow;
	private BigDecimal boyValueMiddle;
	private BigDecimal girlValueLow;
	private BigDecimal girlValueMiddle;

	public UpgrowthStandardSub() {
	}

	public UpgrowthStandardSub(Integer id, Integer upgrowthStandardId,
			Integer yearOld, Integer monthOld, BigDecimal consultHeight,
			BigDecimal boyValueLow, BigDecimal boyValueMiddle,
			BigDecimal girlValueLow, BigDecimal girlValueMiddle) {
		this.id = id;
		this.upgrowthStandardId = upgrowthStandardId;
		this.yearOld = yearOld;
		this.monthOld = monthOld;
		this.consultHeight = consultHeight;
		this.boyValueLow = boyValueLow;
		this.boyValueMiddle = boyValueMiddle;
		this.girlValueLow = girlValueLow;
		this.girlValueMiddle = girlValueMiddle;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUpgrowthStandardId() {
		return this.upgrowthStandardId;
	}

	public void setUpgrowthStandardId(Integer upgrowthStandardId) {
		this.upgrowthStandardId = upgrowthStandardId;
	}

	public Integer getYearOld() {
		return this.yearOld;
	}

	public void setYearOld(Integer yearOld) {
		this.yearOld = yearOld;
	}

	public Integer getMonthOld() {
		return this.monthOld;
	}

	public void setMonthOld(Integer monthOld) {
		this.monthOld = monthOld;
	}

	public BigDecimal getConsultHeight() {
		return this.consultHeight;
	}

	public void setConsultHeight(BigDecimal consultHeight) {
		this.consultHeight = consultHeight;
	}

	public BigDecimal getBoyValueLow() {
		return this.boyValueLow;
	}

	public void setBoyValueLow(BigDecimal boyValueLow) {
		this.boyValueLow = boyValueLow;
	}

	public BigDecimal getBoyValueMiddle() {
		return this.boyValueMiddle;
	}

	public void setBoyValueMiddle(BigDecimal boyValueMiddle) {
		this.boyValueMiddle = boyValueMiddle;
	}

	public BigDecimal getGirlValueLow() {
		return this.girlValueLow;
	}

	public void setGirlValueLow(BigDecimal girlValueLow) {
		this.girlValueLow = girlValueLow;
	}

	public BigDecimal getGirlValueMiddle() {
		return this.girlValueMiddle;
	}

	public void setGirlValueMiddle(BigDecimal girlValueMiddle) {
		this.girlValueMiddle = girlValueMiddle;
	}

}
