package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;

/**
 * VaccinationRec generated by hbm2java
 */
public class VaccinationRec implements java.io.Serializable {

	private String id;
	private String vaccinationId;
	private Integer vaccineInfoId;
	private Integer order;
	private Timestamp makeDate;
	private String position;
	private String batch;
	private String usefulLife;
	private String producer;
	private String doctor;
	private String description;
	private String recorder;
	private String patchStatus;

	public VaccinationRec() {
	}

	public VaccinationRec(String vaccinationId, Integer vaccineInfoId,
			Integer order, Timestamp makeDate, String position, String batch,
			String usefulLife, String producer, String doctor,
			String description) {
		this.vaccinationId = vaccinationId;
		this.vaccineInfoId = vaccineInfoId;
		this.order = order;
		this.makeDate = makeDate;
		this.position = position;
		this.batch = batch;
		this.usefulLife = usefulLife;
		this.producer = producer;
		this.doctor = doctor;
		this.description = description;
	}

	public VaccinationRec(String vaccinationId, Integer vaccineInfoId,
			Integer order, Timestamp makeDate, String position, String batch,
			String usefulLife, String producer, String doctor,
			String description, String recorder, String patchStatus) {
		this.vaccinationId = vaccinationId;
		this.vaccineInfoId = vaccineInfoId;
		this.order = order;
		this.makeDate = makeDate;
		this.position = position;
		this.batch = batch;
		this.usefulLife = usefulLife;
		this.producer = producer;
		this.doctor = doctor;
		this.description = description;
		this.recorder = recorder;
		this.patchStatus = patchStatus;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getVaccinationId() {
		return this.vaccinationId;
	}

	public void setVaccinationId(String vaccinationId) {
		this.vaccinationId = vaccinationId;
	}

	public Integer getVaccineInfoId() {
		return this.vaccineInfoId;
	}

	public void setVaccineInfoId(Integer vaccineInfoId) {
		this.vaccineInfoId = vaccineInfoId;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public Timestamp getMakeDate() {
		return this.makeDate;
	}

	public void setMakeDate(Timestamp makeDate) {
		this.makeDate = makeDate;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	public String getUsefulLife() {
		return this.usefulLife;
	}

	public void setUsefulLife(String usefulLife) {
		this.usefulLife = usefulLife;
	}

	public String getProducer() {
		return this.producer;
	}

	public void setProducer(String producer) {
		this.producer = producer;
	}

	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRecorder() {
		return this.recorder;
	}

	public void setRecorder(String recorder) {
		this.recorder = recorder;
	}

	public String getPatchStatus() {
		return this.patchStatus;
	}

	public void setPatchStatus(String patchStatus) {
		this.patchStatus = patchStatus;
	}

}
