package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;

/**
 * Vaccination generated by hbm2java
 */
public class Vaccination implements java.io.Serializable {

	private String id;
	private String fileNo;
	private String inputPersonId;
	private Timestamp inputDate;
	private String name;
	private String sex;
	private Timestamp birthday;
	private String guardian;
	private String relation;
	private String tel;
	private String address;
	private String registerAddress;
	private Timestamp inDate;
	private Timestamp outDate;
	private String outReason;
	private String abnormalHistory;
	private String taboo;
	private String infectiousHistory;
	private Timestamp buildDate;
	private String doctor;
	private String execDistrictNum;
	public Vaccination() {
	}

	public Vaccination(String fileNo, String inputPersonId, Timestamp inputDate) {
		this.fileNo = fileNo;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
	}

	public Vaccination(String fileNo, String inputPersonId,
			Timestamp inputDate, String name, String sex, Timestamp birthday,
			String guardian, String relation, String tel, String address,
			String registerAddress, Timestamp inDate, Timestamp outDate,
			String outReason, String abnormalHistory, String taboo,
			String infectiousHistory, Timestamp buildDate, String doctor,
			String execDistrictNum) {
		this.fileNo = fileNo;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
		this.name = name;
		this.sex = sex;
		this.birthday = birthday;
		this.guardian = guardian;
		this.relation = relation;
		this.tel = tel;
		this.address = address;
		this.registerAddress = registerAddress;
		this.inDate = inDate;
		this.outDate = outDate;
		this.outReason = outReason;
		this.abnormalHistory = abnormalHistory;
		this.taboo = taboo;
		this.infectiousHistory = infectiousHistory;
		this.buildDate = buildDate;
		this.doctor = doctor;
		this.execDistrictNum = execDistrictNum;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public String getInputPersonId() {
		return this.inputPersonId;
	}

	public void setInputPersonId(String inputPersonId) {
		this.inputPersonId = inputPersonId;
	}

	public Timestamp getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Timestamp getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Timestamp birthday) {
		this.birthday = birthday;
	}

	public String getGuardian() {
		return this.guardian;
	}

	public void setGuardian(String guardian) {
		this.guardian = guardian;
	}

	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getRegisterAddress() {
		return this.registerAddress;
	}

	public void setRegisterAddress(String registerAddress) {
		this.registerAddress = registerAddress;
	}

	public Timestamp getInDate() {
		return this.inDate;
	}

	public void setInDate(Timestamp inDate) {
		this.inDate = inDate;
	}

	public Timestamp getOutDate() {
		return this.outDate;
	}

	public void setOutDate(Timestamp outDate) {
		this.outDate = outDate;
	}

	public String getOutReason() {
		return this.outReason;
	}

	public void setOutReason(String outReason) {
		this.outReason = outReason;
	}

	public String getAbnormalHistory() {
		return this.abnormalHistory;
	}

	public void setAbnormalHistory(String abnormalHistory) {
		this.abnormalHistory = abnormalHistory;
	}

	public String getTaboo() {
		return this.taboo;
	}

	public void setTaboo(String taboo) {
		this.taboo = taboo;
	}

	public String getInfectiousHistory() {
		return this.infectiousHistory;
	}

	public void setInfectiousHistory(String infectiousHistory) {
		this.infectiousHistory = infectiousHistory;
	}

	public Timestamp getBuildDate() {
		return this.buildDate;
	}

	public void setBuildDate(Timestamp buildDate) {
		this.buildDate = buildDate;
	}

	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

	public String getExecDistrictNum() {
		return execDistrictNum;
	}

	public void setExecDistrictNum(String execDistrictNum) {
		this.execDistrictNum = execDistrictNum;
	}

}
