package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.sql.Timestamp;

/**
 * VaccinateHistory generated by hbm2java
 */
public class VaccinateHistory implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private String bacterinName;
	private Timestamp vdate;
	private String hostpital;

	public VaccinateHistory() {
	}

	public VaccinateHistory(String medicalExamId, String bacterinName) {
		this.medicalExamId = medicalExamId;
		this.bacterinName = bacterinName;
	}

	public VaccinateHistory(String medicalExamId, String bacterinName,
			Timestamp vdate, String hostpital) {
		this.medicalExamId = medicalExamId;
		this.bacterinName = bacterinName;
		this.vdate = vdate;
		this.hostpital = hostpital;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public String getBacterinName() {
		return this.bacterinName;
	}

	public void setBacterinName(String bacterinName) {
		this.bacterinName = bacterinName;
	}

	public Timestamp getVdate() {
		return this.vdate;
	}

	public void setVdate(Timestamp vdate) {
		this.vdate = vdate;
	}

	public String getHostpital() {
		return this.hostpital;
	}

	public void setHostpital(String hostpital) {
		this.hostpital = hostpital;
	}

}
