package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * VasSick generated by hbm2java
 */
public class VasSick implements java.io.Serializable {

	private String id;
	private String medicalExamId;
	private Integer vasSickId;

	public VasSick() {
	}

	public VasSick(String medicalExamId, Integer vasSickId) {
		this.medicalExamId = medicalExamId;
		this.vasSickId = vasSickId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMedicalExamId() {
		return this.medicalExamId;
	}

	public void setMedicalExamId(String medicalExamId) {
		this.medicalExamId = medicalExamId;
	}

	public Integer getVasSickId() {
		return this.vasSickId;
	}

	public void setVasSickId(Integer vasSickId) {
		this.vasSickId = vasSickId;
	}

}
