CREATE TABLE [dbo].[ChildrenMediExam3]
(
[ID] [char] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[InputPersonID] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[InputDate] [datetime] NOT NULL,
[VisitDate] [datetime] NULL,
[Weight] [decimal] (10, 2) NULL,
[WeightScore] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Height] [decimal] (10, 2) NULL,
[HeightScore] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Body] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Face] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FaceOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Eyes] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[EyesOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Ears] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[EarsOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Heart] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[HeartOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Liver] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[LiverOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Walk] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[WalkOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Behaiviour] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BehaiviourOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Sociality] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SocialityOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Sickness] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[SicknessOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Allergy] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[AllergyOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Transfer] [bit] NULL,
[TransReason] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[TransUnit] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DirectOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[VisitDoctor] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[HighRiskSearch] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ForeignId] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChildrenMediExam3] ADD CONSTRAINT [pk_ChildrenMediExam3] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
