CREATE TABLE [dbo].[FirstVistBeforeBorn]
(
[ID] [char] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[InputPersonID] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[InputDate] [datetime] NOT NULL,
[VisitDate] [datetime] NOT NULL,
[DiastolicPressure] [decimal] (10, 2) NULL,
[SystolicPressure] [decimal] (10, 2) NULL,
[Evaluation] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Transfer] [bit] NULL,
[TransReason] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[TransUnit] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[VisitDoctor] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[NextVisitDate] [datetime] NULL,
[Weeks] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[HusbandName] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[HusbandAge] [int] NULL,
[HusbandTel] [nvarchar] (11) COLLATE Chinese_PRC_CI_AS NULL,
[Gravidity] [int] NULL,
[Parity] [int] NULL,
[LastMenses] [datetime] NULL,
[EDC] [datetime] NULL,
[PastHistoryOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FamilyHistoryOther] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[OPSHistory] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[OPSHistoryOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Pregnant1] [int] NULL,
[Pregnant2] [int] NULL,
[Pregnant3] [int] NULL,
[Pregnant4] [int] NULL,
[Height] [decimal] (10, 2) NULL,
[Weight] [decimal] (10, 2) NULL,
[Habitus] [decimal] (10, 2) NULL,
[Exam01] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam01Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam02] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam02Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam03] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam03Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam04] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam04Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam05] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam05Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam06] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam06Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam07] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam07Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam08] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Exam09] [decimal] (10, 5) NULL,
[Exam10] [decimal] (10, 5) NULL,
[Exam11] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam12] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam13] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam14] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam15] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam16] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam17] [decimal] (10, 5) NULL,
[Exam18] [decimal] (10, 5) NULL,
[Exam19] [decimal] (10, 5) NULL,
[Exam20] [decimal] (10, 5) NULL,
[Exam21] [decimal] (10, 5) NULL,
[Exam22] [decimal] (10, 5) NULL,
[Exam23] [decimal] (10, 5) NULL,
[Exam24] [decimal] (10, 5) NULL,
[Exam25] [decimal] (10, 5) NULL,
[Exam26] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam26Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam27] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam28] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BeforeBornDirectOther] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[BornAge] [int] NULL,
[Parity1] [int] NULL,
[PersonalHistoryOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Pregnant5] [int] NULL,
[BloodTypeAbo] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[bloodTypeRh] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BloodSugar] [decimal] (10, 2) NULL,
[femeClean] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[hepatitis01] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[hepatitis02] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[hepatitis03] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[hepatitis04] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[hepatitis05] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[exam29] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[beforeBornCheckDirectOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[High_Risk] [nvarchar] (2) COLLATE Chinese_PRC_CI_AS NULL,
[High_Risk_Remark] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[ExecDistrictNum] [nvarchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[HighRiskSearch] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PresentIllnessHistory] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[MenarcheAge] [int] NULL,
[CycleOne] [int] NULL,
[CycleTwo] [int] NULL,
[VacuumExtraction] [int] NULL,
[Forceps] [int] NULL,
[Breech] [int] NULL,
[EndChildbirthDate] [datetime] NULL,
[ContraceptiveHistoryOther] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[EndAbortionDate] [datetime] NULL,
[NewbornDeath] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[NewbornDeathDate] [datetime] NULL,
[NewbornDeathReason] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[BirthDefects] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BirthDefectsName] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[PrematureBirth] [int] NULL,
[SurvivalMale] [int] NULL,
[SurvivalFemale] [int] NULL,
[ComplicationHistory] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[HeartRate] [int] NULL,
[BreathingRate] [int] NULL,
[Liver] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[LiverOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[Spleen] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SpleenOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[Breast] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BreastOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[OtherExam] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[OtherExamOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[HIVDetectDate] [datetime] NULL,
[SyphilisDetectDate] [datetime] NULL,
[HepatitisBDetectDate] [datetime] NULL,
[DiagnosisRemark] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[ForeignId] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FirstVistBeforeBorn] ADD CONSTRAINT [pk_FirstVistBeforeBorn] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [pmhs_firstVistBeforeBorn] ON [dbo].[FirstVistBeforeBorn] ([FileNo]) ON [PRIMARY]
GO
