CREATE TABLE [dbo].[PersonalInfoBackUp]
(
[ID] [char] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNoSub] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Sex] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Birthday] [datetime] NULL,
[IDNumber] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[WorkUnit] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TEL] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Linkman] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[LinkmanTEL] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[ResideType] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Folk] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FolkOther] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[BloodTypeABO] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[BloodTypeRH] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Education] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Occupation] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MaritalStatus] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[PaymentModeOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[AllergiesOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[fHistoryOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[mHistoryOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[bHistoryOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[fmHistoryOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[GeneticHistory] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[GeneticHistoryOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DisabilityStatusOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[InputPersonID] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[InputDate] [datetime] NULL,
[farmStatus] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[HomeID] [varchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[Kitchen] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Bunkers] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DrinkingWater] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Toilet] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Poultry] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[TownStatus] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[bornStatus] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PersonalInfoBackUp] ADD CONSTRAINT [pk_PersonalInfoBackUp] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
