CREATE TABLE [dbo].[vacc]
(
[FileNo] [varchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[updatedate] [datetime] NOT NULL,
[DownloadFlag] [smallint] NOT NULL CONSTRAINT [DF__vacc__DownloadFl__60E75331] DEFAULT ((0)),
[儿童内码] [nvarchar] (16) COLLATE Chinese_PRC_CI_AS NOT NULL,
[儿童编码] [nvarchar] (18) COLLATE Chinese_PRC_CI_AS NULL,
[儿童姓名] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[儿童性别] [nvarchar] (2) COLLATE Chinese_PRC_CI_AS NOT NULL,
[免疫卡号] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[免疫卡属性] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[出生日期] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[户口地址] [nvarchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[家庭住址] [nvarchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[通讯地址] [nvarchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[家庭电话] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[邮件地址] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[呼机] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[手机号码] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[短信息定制] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[定制时间] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[父亲姓名] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[父亲单位] [nvarchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[父亲电话] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[母亲姓名] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[母亲单位] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[母亲电话] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[母亲HB] [nvarchar] (5) COLLATE Chinese_PRC_CI_AS NULL,
[是否保偿] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[开始保偿日期] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[结束保偿日期] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[保偿金额] [real] NULL,
[儿童区域划分] [nvarchar] (3) COLLATE Chinese_PRC_CI_AS NOT NULL,
[户籍属性] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[户籍变化] [nvarchar] (5) COLLATE Chinese_PRC_CI_AS NULL,
[户口属性] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[是否有禁忌症] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[在册情况] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[在册备注] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[在册日期] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[在册变化] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[建卡日期] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[发卡日期] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[儿童接种地点] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[备注] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[接种疫苗] [nvarchar] (400) COLLATE Chinese_PRC_CI_AS NULL,
[接种时间1] [nvarchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[接种时间2] [nvarchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[登记时间1] [nvarchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[登记时间2] [nvarchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[疫苗接种地点1] [nvarchar] (250) COLLATE Chinese_PRC_CI_AS NULL,
[疫苗接种地点2] [nvarchar] (250) COLLATE Chinese_PRC_CI_AS NULL,
[疫苗接种地点3] [nvarchar] (250) COLLATE Chinese_PRC_CI_AS NULL,
[疫苗接种地点4] [nvarchar] (250) COLLATE Chinese_PRC_CI_AS NULL,
[接种标记] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[原位置] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[现位置] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[数据状态] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NOT NULL,
[修改日期] [varchar] (23) COLLATE Chinese_PRC_CI_AS NULL,
[上传时间] [datetime] NULL,
[异地接种] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[上传标志] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[打印预约单日期] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[全程服务] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[全程服务内容] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[选择] [bit] NULL,
[字段1] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[字段2] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[疫苗批号] [varchar] (2200) COLLATE Chinese_PRC_CI_AS NULL,
[免费疫苗] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[当日就诊号] [int] NULL,
[就诊日期] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[备用就诊号] [int] NULL,
[人份] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[接种医师] [varchar] (2200) COLLATE Chinese_PRC_CI_AS NULL,
[接种位置] [varchar] (1200) COLLATE Chinese_PRC_CI_AS NULL,
[终端号] [varchar] (6) COLLATE Chinese_PRC_CI_AS NULL,
[登记医师] [varchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[就诊确认日期] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[儿童身份证] [varchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[出生证编号] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[出生时间] [nvarchar] (5) COLLATE Chinese_PRC_CI_AS NULL,
[出生医院] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[胎次] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[出生体重] [nvarchar] (5) COLLATE Chinese_PRC_CI_AS NULL,
[父亲手机] [nvarchar] (15) COLLATE Chinese_PRC_CI_AS NULL,
[母亲手机] [nvarchar] (15) COLLATE Chinese_PRC_CI_AS NULL,
[户口县国标] [nvarchar] (6) COLLATE Chinese_PRC_CI_AS NULL,
[传染病史] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[过敏史] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[接种反应史] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[禁忌症] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[建卡单位] [nvarchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[建卡人] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[唯一码] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[是否入园] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[入园年度] [nvarchar] (4) COLLATE Chinese_PRC_CI_AS NULL,
[幼儿园编码] [nvarchar] (4) COLLATE Chinese_PRC_CI_AS NULL,
[卡介苗接种时间] [nvarchar] (5) COLLATE Chinese_PRC_CI_AS NULL,
[乙肝接种时间] [nvarchar] (5) COLLATE Chinese_PRC_CI_AS NULL,
[生产企业] [varchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[民族] [varchar] (2) COLLATE Chinese_PRC_CI_AS NULL,
[接种时间] [varchar] (500) COLLATE Chinese_PRC_CI_AS NULL,
[票据编码] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[票据发放日期] [varchar] (16) COLLATE Chinese_PRC_CI_AS NULL,
[发卡单位] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[下载时间] [datetime] NULL,
[下载单位] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[字段3] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[字段4] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[字段5] [varchar] (36) COLLATE Chinese_PRC_CI_AS NULL,
[职业] [varchar] (2) COLLATE Chinese_PRC_CI_AS NULL,
[上传单位] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[字段6] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[字段7] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[字段8] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[字段9] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[字段10] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[母亲身份证] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[父亲身份证] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[健康档案编码] [varchar] (36) COLLATE Chinese_PRC_CI_AS NULL,
[疤痕] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[接种途径] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[使用票据] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[字段11] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[迁移时间] [varchar] (25) COLLATE Chinese_PRC_CI_AS NULL,
[回传] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[新生儿] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[新生儿ID] [varchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[归属门诊] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[查重删除] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[字段12] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[省迁移] [varchar] (1) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
