CREATE TABLE [dbo].[ChildrenDeathSurvey02]
(
[ID] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DBabyName] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FMotherAge] [int] NULL,
[FMotherFolk] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FMotherFolkOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FMotherEducation] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FMotherOccupation] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FMotherLocalResidence] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FAvgIncome] [decimal] (10, 2) NULL,
[FAddress] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FAddressOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[MBeforeExam] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MBeforeExamTime] [int] NULL,
[MUnBeforeExamReason] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[MComplication] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MComplicationRemarks] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[MChildFetal] [int] NULL,
[MChildYeild] [int] NULL,
[MChildWeekly] [int] NULL,
[MBirthWay] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[MBirthAddress] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MBirthAddressReason] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[MChildDoctor] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MChokeHistory] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MException] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MIsHealth] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MUnHealthRemarks] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[DBUException] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[DBUContinuedDay] [int] NULL,
[DBUStep] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[DBUReason] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DBUReasonCustom] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[DBUReasonOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[DBUFHelp] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DBUFHelpOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[DBUHelp] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DBUHelpOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[DBFirstSelectHosp] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DBContinuedTime] [int] NULL,
[DBDiagnoseHosp] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DBDiagnose] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[DBCureDay] [int] NULL,
[DBCommunityReason] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DBCommunityReasonOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[DBQuitCureReason] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DBQuitCureReasonOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[TDContinueDay] [int] NULL,
[TDIsNeedTrans] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TDFirstRemainTime] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TDFirstRouteRemainTime] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TDSecondRemainTime] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TDSecondRouteRemainTime] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TDSecondTranReason] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[TDFHelp] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TDFHelpOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[TDHelp] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TDHelpOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[BDTime] [datetime] NULL,
[DBAge] [int] NULL,
[BDAddress] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[BDAddressOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[BDDiagnose] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[BDBaseByDiagnose] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TUnit] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TOptPerson] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TDate] [datetime] NULL,
[InputPersonID] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[InputDate] [datetime] NULL,
[ExecDistrictNum] [nvarchar] (32) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChildrenDeathSurvey02] ADD CONSTRAINT [PK__Children__3214EC272E90DD8E] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ChildrenDeathSurvey02] ON [dbo].[ChildrenDeathSurvey02] ([FileNo]) ON [PRIMARY]
GO
