USE [pmhs]
GO

/****** Object:  Table [dbo].[Pointer]    Script Date: 01/04/2014 18:21:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Pointer](
	[Id] [varchar](200) NOT NULL,
	[OrganId] [varchar](20) NOT NULL,
	[OrganName] [varchar](200) NOT NULL,
 CONSTRAINT [PK_Pointer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

