CREATE TABLE [dbo].[MedicalExam]
(
[ID] [char] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ExamDate] [datetime] NOT NULL,
[Doctor] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[SymptomOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[General01] [decimal] (10, 5) NULL,
[General02] [int] NULL,
[General03] [int] NULL,
[General04] [int] NULL,
[General05] [int] NULL,
[General06] [int] NULL,
[General07] [int] NULL,
[General08] [decimal] (10, 2) NULL,
[General09] [decimal] (10, 2) NULL,
[General10] [decimal] (10, 2) NULL,
[General11] [decimal] (10, 5) NULL,
[General12] [decimal] (10, 2) NULL,
[General13] [decimal] (10, 2) NULL,
[General14] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[General15] [int] NULL,
[General16] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[General17] [int] NULL,
[Life01] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Life02] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Life03] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Life04] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Life05Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Life06] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Life07] [int] NULL,
[Life08] [int] NULL,
[Life09] [int] NULL,
[Life10] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Life11] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Life12] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Life13] [int] NULL,
[Life14] [int] NULL,
[Life15] [bit] NULL,
[Life16Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Life17] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Life18] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Life19] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Life20] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Life21] [bit] NULL,
[Life21Other] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Life22] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Life23] [bit] NULL,
[Life23Other] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Life24] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Life25] [bit] NULL,
[Life25Other] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Viscera01] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Viscera02] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Viscera02Description] [nvarchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[Viscera03] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Viscera04] [decimal] (10, 2) NULL,
[Viscera05] [decimal] (10, 2) NULL,
[Viscera06] [decimal] (10, 2) NULL,
[Viscera07] [decimal] (10, 2) NULL,
[Viscera08] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Viscera09] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body01] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body01Other] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Body02] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body02Other] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Body03] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body03Other] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Body04] [bit] NULL,
[Body05] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body05Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body06] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body06Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body07] [int] NULL,
[Body08] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body09] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body09Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body10] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body10Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body12] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body12Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body13] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body13Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body14] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body14Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body15] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body15Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body16] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body17] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body18] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body18Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body19Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body20] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body20Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body21] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body21Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body22] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body22Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body23] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body23Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body24] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Body24Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Body25] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Exam01] [decimal] (10, 5) NULL,
[Exam02] [decimal] (10, 5) NULL,
[Exam03] [decimal] (10, 5) NULL,
[Exam04] [decimal] (10, 5) NULL,
[Exam05] [decimal] (10, 5) NULL,
[Exam06] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Exam07] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam08] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam09] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam10] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam11] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam12] [decimal] (10, 5) NULL,
[Exam13] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam14] [decimal] (10, 5) NULL,
[Exam15] [decimal] (10, 5) NULL,
[Exam16] [decimal] (10, 5) NULL,
[Exam17] [decimal] (10, 5) NULL,
[Exam18] [decimal] (10, 5) NULL,
[Exam19] [decimal] (10, 5) NULL,
[Exam20] [decimal] (10, 5) NULL,
[Exam21] [decimal] (10, 5) NULL,
[Exam22] [decimal] (10, 5) NULL,
[Exam23] [decimal] (10, 2) NULL,
[Exam24] [decimal] (10, 2) NULL,
[Exam25] [decimal] (10, 2) NULL,
[Exam26] [decimal] (10, 2) NULL,
[Exam27] [decimal] (10, 2) NULL,
[Exam28] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam29] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam29Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Exam30] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam30Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Exam31] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam31Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Exam32] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam32Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Exam33] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam33Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Exam34] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[CHN01] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CHN02] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CHN03] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CHN04] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CHN05] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CHN06] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CHN07] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CHN08] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[CHN09] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Problem01Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Problem02Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Problem03Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Problem04Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Problem05Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Problem06] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Problem06Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Problem07] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Problem07Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Judge01] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Judge02] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Judge03] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Judge04] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Judge05] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[DangerControlOther1] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DangerControlOther2] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DangerControlOther3] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[InputPersonID] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[InputDate] [datetime] NOT NULL,
[Age] [int] NULL,
[OldManHealthEstimate] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[OldManLifeEstimate] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Life26] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Life27] [bit] NULL,
[Life27Other] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Life28] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Life29] [bit] NULL,
[Life29Other] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Viscera02Description1] [nvarchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[Viscera02Description2] [nvarchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[Viscera02Description3] [nvarchar] (40) COLLATE Chinese_PRC_CI_AS NULL,
[ExecDistrictNum] [nvarchar] (32) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MedicalExam] ADD CONSTRAINT [pk_MedicalExam] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [pmhs_medicalExam] ON [dbo].[MedicalExam] ([FileNo]) ON [PRIMARY]
GO
