CREATE TABLE [dbo].[HealthFileChildren]
(
[ID] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Name] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Sex] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[AllergiesHistory] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FatherName] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[MotherName] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[BuildDate] [datetime] NULL,
[BuildUnit] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ResidenceProvence] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ResidenceCity] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ResidenceCounty] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ResidenceTownship] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ResidenceVillage] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ResidenceGroup] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[AddressProvence] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[AddressCity] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[AddressCounty] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[AddressTownship] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[AddressVillage] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[AddressGroup] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TEL] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Birthday] [datetime] NULL,
[Weight] [decimal] (10, 2) NULL,
[Height] [decimal] (10, 2) NULL,
[ApgarOneMinuts] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ApgarFiveMinuts] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[abo] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[rh] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Weekly] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Gravidity] [int] NULL,
[Parity] [int] NULL,
[NumberOfBirths] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[BormWays] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BirthOrgName] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[FatherAge] [int] NULL,
[FatherNation] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FatherEducational] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FatherOccupation] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MotherAge] [int] NULL,
[MotherNation] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MotherEducational] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MotherOccupation] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MontherExceptions] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[MontherExceptionOhter] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[ChildrenExceptions] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ChildrenException1] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ChildrenExceptionOhter] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[BirthDefect] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[BirthDefectOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[ChildIllScreening] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ChildIllScreeningOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[ChildHereditary] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ChildHereditaryOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[InputPersonID] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[InputDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HealthFileChildren] ADD CONSTRAINT [PK__HealthFi__3214EC27569ECEE8] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
