CREATE TABLE [dbo].[BabySkin]
(
[BabyVisitID] [char] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ID] [char] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[BabySkinID] [int] NOT NULL CONSTRAINT [DF__BabySkin__BabySk__4242D080] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BabySkin] ADD CONSTRAINT [pk_BabySkin] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
