CREATE TABLE [dbo].[ChildrenDeathSurvey01]
(
[ID] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[DBabyName] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DBabyHospital] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FMotherAge] [int] NULL,
[FMotherFolk] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FMotherFolkOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FMotherEducation] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FMotherOccupation] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FMotherLocalResidence] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[FAvgIncome] [decimal] (10, 2) NULL,
[FAddress] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FAddressOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[MBeforeExam] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MBeforeExamTime] [int] NULL,
[MUnBeforeExamReason] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[MComplication] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MComplicationRemarks] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[MChildFetal] [int] NULL,
[MChildYeild] [int] NULL,
[MChildWeekly] [int] NULL,
[MBirthWay] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[MBirthAddress] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MBirthAddressReason] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[MChildDoctor] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MChokeHistory] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MException] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MIsHealth] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[MUnHealthRemarks] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[PStartDate] [datetime] NULL,
[PHospAndDepart] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PDiagnoses] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[PDealRemarks] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[TIsNeedTrans] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TFirstRemainTime] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TFirstRouteRemainTime] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TSecondRemainTime] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TSecondRouteRemainTime] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TSecondTranReason] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[TDoctorDeal] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TDoctorDealDetails] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[DDiagnose] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[DDiagnoseProc] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[BDDiagnose] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[BDReason] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[BDDissect] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[BDDiscuss] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TUnit] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TOptPerson] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[TDate] [datetime] NULL,
[InputPersonID] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[InputDate] [datetime] NULL,
[ExecDistrictNum] [nvarchar] (32) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChildrenDeathSurvey01] ADD CONSTRAINT [PK__Children__3214EC272BB470E3] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ChildrenDeathSurvey01] ON [dbo].[ChildrenDeathSurvey01] ([FileNo]) ON [PRIMARY]
GO
