CREATE TABLE [dbo].[BabyBarrierReg]
(
[ID] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Name] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Sex] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Nation] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Birthday] [datetime] NULL,
[Age] [int] NULL,
[AgeMonth] [int] NULL,
[AgeDay] [int] NULL,
[AgeHours] [int] NULL,
[FamilyAddress] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Post] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Tel] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FatherName] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[FatherAge] [int] NULL,
[FatherOccupation] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[MotherName] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[MotherAge] [int] NULL,
[MotherOccupation] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ScreeningWay] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[ScreeningDate] [datetime] NULL,
[ScreeningResult] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[FetalNumber] [int] NULL,
[YieldNumber] [int] NULL,
[Weight] [decimal] (10, 2) NULL,
[FetalWay] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[ChildBirthWay] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[BirthDefact] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[BirthDefactOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BirthDistress] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Apgar] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ApgarOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[YieldHurt] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[YieldHurtOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[AmnioticFluid] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ChildBirthException] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Deformity] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[DeformityOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Infection] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[InfectionReason] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[InfectionCourse] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Ill] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[IllReason] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[IllCourse] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[HeadHurt] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[HeadHurtOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[OtitisHistory] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[OtitisHistoryOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NICU] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[NICUReason] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NICUDate] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Ventilator] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[VentilatorReason] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[VentilatorDate] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[OtherReaction] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[ChildBirthAge] [int] NULL,
[AbortionHistory] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[AbortionDate] [datetime] NULL,
[AbortionReasion] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[AbortionWay] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[InfectionHistory] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[InfectionHistoryOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[InfectionHistoryWeek] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[InfectionHistory1] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[InfectionHistory1Other] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[InfectionHistory1Week] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ContactHistory] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ContactHistoryDate] [datetime] NULL,
[ContactHistoryWeek] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[AppHistory] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[AppHistoryDrugName] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[AppHistoryDrugDate] [datetime] NULL,
[ContactHistory1] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ContactHistory1Date] [datetime] NULL,
[Smoking] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Dreaking] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Drugging] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[IllHistory] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[IllHistoryOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ExceptionHistory] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ExceptionHistoryOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[FamilySmoking] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FamilyDreaking] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[FamilyDrugging] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Deaf] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DeafRelation] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DeafSituation] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Intermarriage] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[IntermarriageRelation] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[HearExamResult] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[DiagnosisResult] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[DiagnosisDoctor] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[OtotoxicityDrugHistoryID] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[InputPersonID] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[InputDate] [datetime] NULL,
[ExecDistrictNum] [nvarchar] (32) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
