CREATE TABLE [dbo].[VisitAfterBorn]
(
[ID] [char] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[InputPersonID] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[InputDate] [datetime] NOT NULL,
[VisitDate] [datetime] NULL,
[DiastolicPressure] [decimal] (10, 2) NULL,
[SystolicPressure] [decimal] (10, 2) NULL,
[Result] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ResultOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[AfterBornDirectOther] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Transfer] [bit] NULL,
[TransReason] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[TransUnit] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[VisitDoctor] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[NextVisitDate] [datetime] NULL,
[BodyHeat] [decimal] (10, 2) NULL,
[Health] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Mind] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Breast] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BreastOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Lochia] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[LochiaOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Metra] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[MetraOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Wound] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[WoundOther] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[RecordType] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[High_Risk] [nvarchar] (2) COLLATE Chinese_PRC_CI_AS NULL,
[High_Risk_Remark] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[ExecDistrictNum] [nvarchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[HighRiskSearch] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Item] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[parities] [int] NULL,
[PostnatalDays] [int] NULL,
[Weight] [decimal] (10, 2) NULL,
[Cervix] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[CervixOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Attachment] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[AttachmentOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Vulva] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[VulvaOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[PulseRate] [int] NULL,
[Milk] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Swelling] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Nipple] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[PalaceHeight] [decimal] (10, 2) NULL,
[WoundHealing] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Lochia01] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Lochia02] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ForeignId] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VisitAfterBorn] ADD CONSTRAINT [pk_VisitAfterBorn] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [pmhs_visitAfterBorn] ON [dbo].[VisitAfterBorn] ([FileNo]) ON [PRIMARY]
GO
