CREATE TABLE [dbo].[ChildBirthRecord]
(
[ID] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[ChildbirthYear] [int] NULL,
[ChildbirthMonth] [int] NULL,
[ChildbirthDay] [int] NULL,
[Flooding] [decimal] (10, 2) NULL,
[ChildbirthAddress] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[BorthWeekly] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ChildbirthWay] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DeliverWay] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[LacerationOfPerineum] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[OuterFissure] [int] NULL,
[BloodPressure] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Deal] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Comorbidity] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ComorbidityOther] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[CriticalWoman] [nvarchar] (2) COLLATE Chinese_PRC_CI_AS NULL,
[CriticalSymptom] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BabySurvive] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[BabyBirth] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[BabyBirthOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BabyComorbidity] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[BabyComorbidityOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[NurseTime] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Diagnosis] [nvarchar] (200) COLLATE Chinese_PRC_CI_AS NULL,
[CertifiId] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[InputPersonId] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[InputDate] [datetime] NULL,
[ExecDistrictNum] [nvarchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[TotalLaborHours] [int] NULL,
[OneLaborHours] [int] NULL,
[TwoLaborHours] [int] NULL,
[TwoLaborMinutes] [int] NULL,
[ThreeLaborMinutes] [int] NULL,
[PlacentaParturitionDate] [datetime] NULL,
[PlacentaParturitionWay] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[IsComplete] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[isNotComplete] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CervicalLaceration] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[CervicalLacerationPosition01] [int] NULL,
[CervicalLacerationPosition02] [int] NULL,
[Bleeding01] [decimal] (10, 2) NULL,
[Bleeding02] [decimal] (10, 2) NULL,
[Complication] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[ComplicationName] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Apgar01] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Apgar02] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Suffocation] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[SuffocationOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[SuffocationOther01] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BirthTrauma] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[BirthTraumaOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[BirthDefects] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[BirthDefectsOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[DischargeDiagnosis01] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[DischargeDiagnosis02] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[DiseaseScreeningOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[totalLaborMinutes] [int] NULL CONSTRAINT [DF__ChildBirt__total__444B1483] DEFAULT ((0)),
[oneLaborMinutes] [int] NULL CONSTRAINT [DF__ChildBirt__oneLa__453F38BC] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChildBirthRecord] ADD CONSTRAINT [PK_ChildBirthRecord] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
