CREATE TABLE [dbo].[ChildrenMediExam]
(
[ID] [char] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[FileNo] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NOT NULL,
[InputPersonID] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL,
[InputDate] [datetime] NOT NULL,
[DataType] [int] NOT NULL,
[CheckItem] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL,
[VisitDate] [datetime] NULL,
[Weight] [decimal] (10, 2) NULL,
[WeightScore] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Height] [decimal] (10, 2) NULL,
[HeightScore] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Face] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[FaceOther] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Eyes] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[EyesOther] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Ears] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[EarsOther] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Heart] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[HeartOther] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Walk] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[WalkOther] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Transfer] [nvarchar] (1) COLLATE Chinese_PRC_CI_AS NULL,
[TransReason] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[TransUnit] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[DirectOther] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[NextVisitDate] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[VisitDoctor] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam01] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam01Other] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Exam02] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Exam03] [decimal] (10, 2) NULL,
[Exam04] [decimal] (10, 2) NULL,
[Exam05] [int] NULL,
[Exam06] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam06Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam07] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam07Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam08] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam08Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam09] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam10] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam11] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam11Other] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam12] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[ActivityTime] [numeric] (10, 2) NULL,
[WDCount] [numeric] (10, 2) NULL,
[Evaluate] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[State] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Head] [decimal] (10, 2) NULL,
[Exam13] [bit] NULL,
[Exam14] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam15] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam15Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Exam16] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[Exam16Other] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Exam17] [int] NULL,
[Hearing] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[High_Risk] [nvarchar] (2) COLLATE Chinese_PRC_CI_AS NULL,
[High_Risk_Remark] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[ExecDistrictNum] [nvarchar] (32) COLLATE Chinese_PRC_CI_AS NULL,
[HighRiskSearch] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[EvaluateOther] [nvarchar] (1000) COLLATE Chinese_PRC_CI_AS NULL,
[BreastMilk] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[ForeignId] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ChildrenMediExam] ADD CONSTRAINT [pk_ChildrenMediExam] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [pmhs_childrenMediExam] ON [dbo].[ChildrenMediExam] ([FileNo]) ON [PRIMARY]
GO
