CREATE TABLE [dbo].[WomanPhysicalItems]
(
[ID] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[MedicalExamID] [nvarchar] (36) COLLATE Chinese_PRC_CI_AS NOT NULL,
[Pressure] [nvarchar] (20) COLLATE Chinese_PRC_CI_AS NULL,
[OnlinePhoto] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Pleura] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[MikTooth] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[DecayedTooth] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[ThroatFlat] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[LeftEyes] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[RightEyes] [nvarchar] (10) COLLATE Chinese_PRC_CI_AS NULL,
[Lung] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Heart] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[LymphNode] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Liver] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[Spleen] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[NerveMental] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Pelvis] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[Illness] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[Evaluate] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[DietDirect] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[EarlyDirect] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[ProtectDirect] [nvarchar] (max) COLLATE Chinese_PRC_CI_AS NULL,
[InputPersonId] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[InputDate] [datetime] NULL,
[DirectAge] [nvarchar] (50) COLLATE Chinese_PRC_CI_AS NULL,
[pelvisOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[nerveMentalOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[backbone] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[backboneOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[hearing] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[hearingOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[nose] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[noseother] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[spleenOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[liverOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[heartChildOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[lungOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[genitals] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[genitalsOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[ears] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[earsOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[skins] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[skinsOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[beforeSkull01] [decimal] (10, 2) NULL,
[beforeSkull02] [decimal] (10, 2) NULL,
[fourLimbs] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[fourLimbsOther] [nvarchar] (100) COLLATE Chinese_PRC_CI_AS NULL,
[throatFlatRemark] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[lymphNodeRemark] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL,
[pleuraRemark] [nvarchar] (30) COLLATE Chinese_PRC_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[WomanPhysicalItems] ADD CONSTRAINT [PK_WomanPhysicalItems] PRIMARY KEY CLUSTERED  ([MedicalExamID]) ON [PRIMARY]
GO
